### ISSUE TITLE
Feature Request: GetTags functionality

### ISSUE THREAD

**Issue by zyuhel** [oscarotero/Embed#100]
:) What do you think  about adding get tags method for adapter. It should return array of string tags. 
for random page it could use opengraph/keywords. 
youtube returns tags in opengraph video subtag (og:video:tag) (http://iframely.com/debug gets it but very strangely.).
For custom adapters a function to retrieve them could be written.  
Or do you think this is not needed , and should not be in library?

**Comment by oscarotero** [comment]
Yes, why not :)
It can be relatively easy to implement. If you want to create a PR, it's welcome. But I prefer to use a diferent branch while the feature is not stable, so we can release a new 2.5.x version with the latest fixed and create a new 2.6.x with this new feature.

**Comment by zyuhel** [comment]
Ok, but if i'm right i couldn't make a different branch. So when i will have changes ready. i will post here and you could make a branch so i can make pull request to it.

**Comment by oscarotero** [comment]
I just created the `feature/tags` branch, so you can update your fork to get it. Thank you

**Comment by oscarotero** [comment]
[v.2.6.0 released](https://github.com/oscarotero/Embed/releases/tag/v2.6.0) with this feature
