### ISSUE TITLE
Dot replaced by underscores in some URLS

### ISSUE THREAD

**Issue by edhelas** [oscarotero/Embed#101]
Embed doesn't grab correctly this URL
https://nl.movim.eu/?node/blabla.movim.eu/random/1fb06a3cc05c4490bf659c227b39a9aa

It seems that you have this issue on your project :
* http://stackoverflow.com/questions/68651/get-php-to-stop-replacing-characters-in-get-or-post-arrays
* https://github.com/symfony/symfony/issues/9009

I was also affected by this issue in my project, I used this fix https://github.com/edhelas/movim/blob/master/system/Route.php#L35

**Comment by oscarotero** [comment]
Interesting. I just commit a fix for this. Thanks

**Comment by oscarotero** [comment]
Bugfix released (https://github.com/oscarotero/Embed/releases/tag/v2.5.10)
