### ISSUE TITLE
Support schema.org

### ISSUE THREAD

**Issue by mastito03** [oscarotero/Embed#111]
It's just a suggestion. but if html provider support schema.org, I think it will be good as it can collect more information.

or maybe as new provider

**Comment by oscarotero** [comment]
Yeah, I thought about it and a new provider is the best approach. But I need to do some research about it.
Feel free to contribute if you want.
Thank you.

**Comment by mastito03** [comment]
schema.org support 3 different encoding, RDFa, Microdata and JSON-LD.
which one you think best for the implementation of the first?

**Comment by zyuhel** [comment]
It seems that in real world microdata is more often to meet :)

**Comment by oscarotero** [comment]
I think JSON-LD is the future, increasingly used and the easiest to implement, because it's only a json.
Creating a provider for this is easy, because it only have to search the script element, parse the containing json and store it in a bag. The problem I see is *how* to use this information, because there's a lot of schemas, with many entities, etc. Keep in mind that the scope of this library is to provide a way to access to standard values like title, url, description, image, etc. Maybe we can start with a `JsonLd` provider and them, if it's useful, implement the `Microdata`. What do you think?

**Comment by mastito03** [comment]
Most information can be stored in bag. It's just extra information that
might be useful.

And for schema maybe we can use most basic schema (parent schema) for
reference.

**Comment by mastito03** [comment]
you can use https://schema.org/Thing as base schema

**Comment by oscarotero** [comment]
Well, I've created a JsonLd provider here (3565a14ec2369819fc1c8ae6b503e6b8f30c0012). Currently only get the json-ld of the page and save it in the bag but does nothing more yet.

I've checking the json-ld values returned by some pages. For example, in http://abanca.com, the json-ld is:
```
Array
(
    [@context] => http://schema.org
    [@type] => Organization
    [name] => ABANCA
    [url] => https://www.abanca.com
    [logo] => https://www.abanca.com/img/logo-social.jpg
    [sameAs] => Array
        (
            [0] => https://www.facebook.com/SomosABANCA
            [1] => https://twitter.com/somosABANCA
            [2] => https://www.youtube.com/user/somosABANCAtv
            [3] => https://www.flickr.com/photos/125188945@N05/
        )

    [contactPoint] => Array
        (
            [0] => Array
                (
                    [@type] => ContactPoint
                    [telephone] => +34-981 910 522
                    [contactType] => customer service
                )

        )

)
```
In my webpage (http://oscarotero.com/en/)
```
Array
(
    [@context] => http://schema.org
    [@type] => Person
    [name] => Oscar Otero
    [jobTitle] => Web designer and developer
    [url] => http://oscarotero.com
    [image] => http://oscarotero.com/image.jpg
    [email] => oom@oscarotero.com
    [sameAs] => Array
        (
            [0] => mailto:oom@oscarotero.com
            [1] => http://dag.gal/gl/oscarotero/
        )

)
```

http://nextfractal.nextbreakpoint.com/
```
Array
(
    [@context] => http://schema.org
    [@type] => SoftwareApplication
    [name] => NextFractal
    [image] => http://nextfractal.nextbreakpoint.com/nextfractal.png
    [url] => https://github.com/nextbreakpoint/nextfractal
    [author] => Array
        (
            [@type] => Person
            [name] => Andrea Medeghini
        )

    [applicationCategory] => fractals
    [operatingSystem] => Mac, Windows, Linux
    [downloadUrl] => https://github.com/nextbreakpoint/nextfractal/releases
    [requirements] => NextFractal requires Java SDK 8 or later, a computer with multi-core CPU, a modern graphics card, and 1Gb of RAM
)
```

I don't know yet how to consume this data, because there are many schema types (Organization, Person, SoftwareApplication, etc), and there can be schemas inside other schema (for example the author of SofwareApplication).

**Comment by mastito03** [comment]
I think best approach is using most basic schema (https://schema.org/Thing) because all schema are children of Thing

for basic property can be use as is
- name  as title
- url as url
- description description
 
for image is depend on it's type

an for other property like author, video, code which depend on schema, we can ignore it for now or use https://schema.org/CreativeWork as base. it base of many other rich schema

just pull some #113

**Comment by oscarotero** [comment]
After thinking abot this, I don't think this is a good idea. It's fine as an extra, but not to get the standard values of the url (title, description, etc). The main reason is that json-ld is to link data between different sites, not to get clean data of the current page.

Let's take, for example the site http://abanca.com (a spanish bank). All pages of the site have the same json-ld data, so all pages have the same title, description, url, etc. Maybe, a better approach is provide this data as a standard value, like title, description, etc, instead use it to get other values. I mean:

```php
$info = Embed::create($url);

//the title of the page
$info->title;

//the scheme of the page
$info->scheme;
```

Currently there's something similar: `$info->source` that returns the rss/atom feed (not documented).

**Comment by mastito03** [comment]
Maybe for json-ld, this approach not good. But i think it's fine with other
format as long as main entity is known.
Because other format is using real page as data.

As for me. I don't really problem about standar data as long as all data on
the bag.

**Comment by mastito03** [comment]
I think again your approach using schema as new standard value is great choice.
as this new value is an simple way to get data from other encoding (microdata, RDFa) without checking bag manually. :+1:

**Comment by oscarotero** [comment]
Ok.There's the fact that a webpage can contains several microdata structures, right? So maybe Embed could return an array with all data structures found. Something like this:

```php
//Get all data schemes found in the page
$data = $info->data;

foreach ($data as $type => $schemes) {
    echo $type; //the scheme type (json-ld, RDFa, etc)

    foreach ($schemes as $scheme) {
        var_dump($scheme); //array with the data structure
    }
}
```
just an idea.

**Comment by mastito03** [comment]
I think it's good idea. as it can separate type.
because if it merge all encoding, we can get dirty data from RDFa as it's used by opengraph and twitter card encoding too.

**Comment by oscarotero** [comment]
Finally, I added a `linkedData` property to allow to fetch the json-ld data from the html code. Supporting other scheme types requires a time that I don't have. But feel free to add a PR if you like to implement it.
