### ISSUE TITLE
Curl Resolver: Check if the cookie file is writeable

### ISSUE THREAD

**Issue by patkar** [oscarotero/Embed#114]
If the path for $tmpCookies in the curl resolver is not writeable, curl doesn't raise an error. Instead it doesn't call the write callback and spits the response into the output buffer. This is not an obvious error, so I think it would be good to check if the path is writeable and raise an informational exception.

**Comment by oscarotero** [comment]
Good point! I didn't know about this behaviour.
I just commit a fix for this.
Thanks
