### ISSUE TITLE
URL returns 404 error

### ISSUE THREAD

**Issue by gametalk** [oscarotero/Embed#119]
https://oscarotero.com/embed2/demo/index.php?url=http%3A%2F%2Fus.battle.net%2Foverwatch%2Fen%2Fmedia%2F

**Comment by oscarotero** [comment]
Seems the problem is in the url parser, that removes the trailing slash of the path, so the path `http://us.battle.net/overwatch/en/media/` is valid but `http://us.battle.net/overwatch/en/media` is not.
I've released 2.6.4 to fix that and now it works fine.
Thanks for the error reporting.
