### ISSUE TITLE
Add a download size limit in the configuration

### ISSUE THREAD

**Issue by edhelas** [oscarotero/Embed#121]
To prevent high-load issues on the server would it be possible to add a download size limit in Embed (that can, for example be limited this way http://stackoverflow.com/a/3431799) ?

I'd like to use Embed to automatically get pictures when URLs are shared on my project but I'd also like to prevent to download huge pictures on my server.

**Comment by oscarotero** [comment]
This feature is currently available.

The `Embed\ImageInfo\Curl` class (used to get the image info) downloads the first bytes of the image and, when it's enought to get the mimetype and dimmensions, the transfer is aborted.

You can check it here: https://github.com/oscarotero/Embed/blob/master/src/ImageInfo/Curl.php#L149

**Comment by edhelas** [comment]
Ok, I'll do some tests on my side. Thanks.
