### ISSUE TITLE
Google+ support?

### ISSUE THREAD

**Issue by BlackKite84** [oscarotero/Embed#124]
https://plus.google.com/+TheKedosZone/posts/9MuuGyxJYbL (video)
https://plus.google.com/+carlsenverlag/posts/2hibgWrmhp1 (image)
https://plus.google.com/108237807162530290429/posts/4Hze1ewJ12r (Gif)

**Comment by oscarotero** [comment]
Done!
Not all posts can be embedded. Your links, for instance are not allowed. I don't know why. Others can:

https://oscarotero.com/embed2/demo/index.php?url=https%3A%2F%2Fplus.google.com%2Fu%2F0%2F%2BStephanHovnanian%2Fposts%2F6apV9FHgo4k
