### ISSUE TITLE
Fetching license/copyright information about media.

### ISSUE THREAD

**Issue by ju1ius** [oscarotero/Embed#125]
Hi,

There doesn't seem to be a mechanism for retrieving attribution (licensing, copyright, etc...) information related to the embeddable content.
Are you planning on adding support for this ?

**Comment by oscarotero** [comment]
I had not thought of that but it's a good idea. Do you know how to fetch this information?

**Comment by ju1ius** [comment]
hummm...
* The rel attribute can take the "license" value.
* There's the [CC-REL rdfa vocab](https://wiki.creativecommons.org/wiki/CC_REL)
* Dublin Core has [this thing](http://dublincore.org/documents/dcmi-terms/#terms-license) too
* Schema.org has the [license](https://schema.org/license) property of CreativeWork objects
* Unfortunately I don't think OpenGraph & OEmbed have standard properties for this.

I've seen however OEmbed responses with a "license" attribute (Flickr I think).

And that's about all I can think of atm... :thought_balloon:

**Comment by JanPetterMG** [comment]
+1
Some sites is using ````/license.txt```` as in ````http://example.com/license.txt````
At least WordPress is using it, because one of the easiest methods to detect if a webpage is built using WP, is actually to check the licence content.

**Comment by zyuhel** [comment]
Dublincore/microformats can give much more than just license info. 
Theoretically this could be achieved by adding new provider, like it is done for OpenGraph. 
But it will take much time, and it will be reinventing the wheel, because there are already exists some microformats php parsers, may be optional provider using some other library will do the trick returning raw data for the ones who need it?

**Comment by ju1ius** [comment]
@zyuhel AFAICT, there's already a minimal [DC provider](https://github.com/oscarotero/Embed/blob/master/src/Providers/Dcterms.php).
Implementing a real RDFa (or JSON-LD) parser is a **really** hard job though and is IMO outside the scope of this lib. It would be much better to rely on existing, battle tested implementations like [easyrdf](http://www.easyrdf.org/) or [lanthaler/JsonLD](https://github.com/lanthaler/JsonLD).
.

**Comment by zyuhel** [comment]
@ju1ius that is what i am talking about, make optional provider that will rely on other library, but make it optional because not everyone want to use that overhead

**Comment by ju1ius** [comment]
@zyuhel  :+1:

**Comment by zyuhel** [comment]
Flickr oembed returns license data :) although it is pretty useless. generally it is something like "All Rights Reserved" 
but sometimes we get full info

    [license] => Attribution License
    [license_url] => https://creativecommons.org/licenses/by/2.0/
    [license_id] => 4

wikimedia has <link rel="copyright" href="//creativecommons.org/licenses/by-sa/3.0/" />

So flickr and wikimedia data can be provided using current codebase. :)

**Comment by oscarotero** [comment]
To use more complicate providers like RDFa or JSON-LD, that require to use external libraries as dependencies, maybe they can be implemented as addons, in a different package. So anyone can install and use them if needed. For example:

```php
use Embed\Embed;
use Embed\Providers\Rdfa;
use Embed\Providers\JsonLd;

$info = Embed::create($url, [
    'extraProviders' => [
        Rdfa::class,
        JsonLd::class,
    ]
]);
```

This allows anyone to create its own providers in addition to the defaults.
To fetch the license, we can use the providers that are currently included (with limited functionality) but leaving the door opened to add more powerfull providers.

**Comment by oscarotero** [comment]
There's a very basic implementation of license using oembed's `license_url` and html's `copyright` tags. It returns only the url (not the license name) to use a common way across all providers. Having the url, it's easy to get the name, avoiding different names returned by difterent providers.

I think it's enough for this first release and can be improved in the future.
