### ISSUE TITLE
WebP

### ISSUE THREAD

**Issue by BlackKite84** [oscarotero/Embed#126]
No Image Found

https://oscarotero.com/embed2/demo/index.php?url=https%3A%2F%2Fwww.gstatic.com%2Fwebp%2Fgallery3%2F1_webp_ll.webp

or Twitter Card Info Faild

https://oscarotero.com/embed2/demo/index.php?url=https%3A%2F%2Fplus.google.com%2F118202655369167522956%2Fposts%2FQ9jtERbixNG

See twittercards.imagesUrls

**Comment by oscarotero** [comment]
Currently webp is not supported. This is because it's not instaled in php by default, only available in php +5.5 and not supported by non-blink browsers (http://caniuse.com/#search=webp).

And about twitter card, I'll check why the image found in twittercards is not valid. Thanks.

**Comment by oscarotero** [comment]
Fixed twittercards issue. Thanks for the feedback.
