### ISSUE TITLE
How can set Config (update save)

### ISSUE THREAD

**Issue by BlackKite84** [oscarotero/Embed#128]
How can Set Config

`//Load library (if you don't have composer or any psr-4 compatible loader):
include('src/autoloader.php');

//Load any url:
$info = Embed\Embed::create('https://www.youtube.com/watch?v=PP1xn5wHtxE');`

i will set

`            'getBiggerImage' => false,
            'getBiggerIcon' => false,`

like this? 

`$info = Embed\Embed::create('https://www.youtube.com/watch?v=PP1xn5wHtxE',array('getBiggerImage' => true,'getBiggerIcon' => true,));`

**Comment by oscarotero** [comment]
You must place this options in the adapter configuration:

```php
 $info = Embed\Embed::create('https://www.youtube.com/watch?v=PP1xn5wHtxE', [
    'adapter' => [
        'config' => [
            'getBiggerImage' => false,
            'getBiggerIcon' => false
        ]
    ]
]);
