### ISSUE TITLE
2.7 currently breaks

### ISSUE THREAD

**Issue by rickshawhobo** [oscarotero/Embed#134]
FYI @oscarotero I thought you'd like to know the current branch of 2.7 dev is broken with this error

Call to undefined function Embed\ImageInfo\Curl::getImagesInfo()

on Line 385 of Embed\Adapters\Adapter.php

**Comment by oscarotero** [comment]
Thanks for the feedback :+1:
It's currently fixed.

**Comment by rickshawhobo** [comment]
@oscarotero curious why you were using that weird syntax
`-        $fn = "{$this->imageClass}::getImagesInfo";		`

**Comment by oscarotero** [comment]
This is the same than `$this->imageClass.'::getImagesInfo'`, but faster.
