### ISSUE TITLE
Extract youtube and vimeo ID

### ISSUE THREAD

**Issue by kamov** [oscarotero/Embed#136]
Hi,
I need to store only youtube and vimeo id.
I see that oembed don't provide this information,
only full url.
I can extract from url, but I guess if exist a way to do this with Embed lib.
Maybe using request class?
Thanks

**Comment by oscarotero** [comment]
The Request class extends Url class, so it has a lot of methods to retrieve url info. For example:

```php
$request = new Request('https://www.youtube.com/watch?v=kUylIQy-IgI');
$id = $request->getQueryParameter('watch');
```
Also, you can get the request from the Embed instance:

```php
$info = Embed::create('https://www.youtube.com/watch?v=kUylIQy-IgI');
if ($info->providerName === 'Youtube') {
    $request = $info->getRequest();
    $id = $request->getQueryParameter('watch');
}
```

**Comment by kamov** [comment]
Awesome! Thanks!
I have found a workaround, but this looks cleaner.
For get from vimeo.com/VIDEO-ID ?

**Comment by oscarotero** [comment]
```php
$id = $request->getDirectoryPosition(0);
```

**Comment by kamov** [comment]
Perfect, thanks!

**Comment by kamov** [comment]
I just test with youtube, and don't work, video id is null..
however don't worry, I will keep my solution with preg_match.

 if($info->providerName == 'youtube') {
                $request = new Request($info->url);
// also this not work:
//$request = $info->getRequest();

                $videoId = $request->getQueryParameter('watch');
            }

**Comment by oscarotero** [comment]
Ah, the query parameter is `v` instead `watch`

**Comment by kamov** [comment]
Ah, right.. good catch. I will try again. Thanks!

**Comment by garbinmarcelo** [comment]
Hello, how can I do this in version 4?

**Comment by oscarotero** [comment]
Version 4 uses Psr-7 standard interface for all HTTTP related stuff (https://www.php-fig.org/psr/psr-7/#35-psrhttpmessageuriinterface)
You can get the uri like this:

```php
$uri = $info->getUri(); //Get the PSR-7 UriInterface
$query = $uri->getQuery(); //Returns the query (as string)
parse_str($query, $parsed); //Parse the query to an array

$videoId = $parsed['watch']; //Get the value
```

**Comment by garbinmarcelo** [comment]
> Version 4 uses Psr-7 standard interface for all HTTTP related stuff (https://www.php-fig.org/psr/psr-7/#35-psrhttpmessageuriinterface)
> You can get the uri like this:
> 
> ```
> $uri = $info->getUri(); //Get the PSR-7 UriInterface
> $query = $uri->getQuery(); //Returns the query (as string)
> parse_str($query, $parsed); //Parse the query to an array
> 
> $videoId = $parsed['watch']; //Get the value
> ```

Ok, I had seen `parse_str` to solve this, but I believed there could be something related like in version 3 (`getQueryParameter('v');`). I honestly didn't know much about Psr-7.

In that case I will use this solution. Resolved the issue! :smile: :beers:

Thanks for returning is a great package.
