### ISSUE TITLE
Embed twitter in fullwidth

### ISSUE THREAD

**Issue by kamov** [oscarotero/Embed#137]
How to display twitter in fullwidth so it become responsive?
Now seem that I can change width of iframe, but there is inside the iframe div element fixed width, so I can't change that.
Thanks

**Comment by oscarotero** [comment]
I don't think you can do this unless using javascript to change the styles of the elements inside the iframe. Any way, this is a twitter issue, not an Embed issue.

**Comment by kamov** [comment]
Ok, thanks. I guess if maybe this is configurable during request to twitter.
