### ISSUE TITLE
Embed google map

### ISSUE THREAD

**Issue by kamov** [oscarotero/Embed#139]
Hi,
there is a way to embed a google map?
Thanks

**Comment by oscarotero** [comment]
Yes, but you need to configure the google provider (more info: https://github.com/oscarotero/Embed#google)

**Comment by kamov** [comment]
Thanks! After setting key, I can just add link to map ? 
I tested on your demo but not work, maybe you don't enable.
The link of documentation under google show how to embed using iframe.
The link is the same as iframe src?

**Comment by kamov** [comment]
The link of iframe is like:
https://www.google.com/maps/embed/v1/place?q=place_id:ChIJ8RFCavcthEcR4PihLiEEjO8&key=...

which require key, so I guess how end users know about key.

**Comment by oscarotero** [comment]
The demo does not have the google provider configured. You need to register your app in google and generate an api key. Then configure the google provider: 
```php
$url = 'https://www.google.es/maps/place/Tordoia,+A+Coru%C3%B1a/@43.0870993,-8.6410403,12z/data=!3m1!4b1!4m2!3m1!1s0xd2ef4006f1ef489:0x404f58273ca55a0';

$info = Embed::create($url, [
    'providers' => [
        'google' => [
            'key' => //here your api key
        ]
    ]
])
```

**Comment by kamov** [comment]
Thanks!

**Comment by robclancy** [comment]
@oscarotero there is no longer docs for providers? I had to use the 3.x branch to get those docs.

**Comment by oscarotero** [comment]
v4 does not have support for gmail oembed jet.

**Comment by robclancy** [comment]
I never realized we are using 3.x. This is for google maps not gmail though. Will they not work with 4.x?

**Comment by oscarotero** [comment]
Sorry, I mean gmaps (not gmail). v4.x does not have adapters for Google at this moment. Maybe I will implement someday, when I have some free time. But if you want to work on this, that's would great.
