### ISSUE TITLE
Get only embed src from Youtube's link

### ISSUE THREAD

**Issue by borz93** [oscarotero/Embed#140]
Hi!
Thanks for this library, works perfect.
As the title says, is there any way to obtain only the "src" from "$video->code"?
Thanks for your time!

EDIT: I use this regular expressions to obtain it:

`preg_match('/src="([^"]+)"/', $video->code, $match);`
 `$url = $match[1];`

But if there is any native or best way.

**Comment by oscarotero** [comment]
Hello.
No, there isn't, so your regular expression is a good way.
Cheers.
