### ISSUE TITLE
Embed facebook video or post

### ISSUE THREAD

**Issue by raxan** [oscarotero/Embed#141]
Hi,
I have issue with embed of facebook video.

I notice that each embed include javascript code, is possible to avoid this, and include just 1 time?

A second issue is that when I add embed via ajax, then embed is not show, I need to reload page.

Maybe exist a better way to handle this using their api?

Any suggestions is welcome.

Thanks!

**Comment by oscarotero** [comment]
Sorry but this is out of the scope of this library. The main aim of Embed is to get the page info as is, without modifications. If you want to edit the code, you have to do by yourself (using a regular expression or parsing the html, for instance).
And about the second issue, if you are using jquery, I think it removes the script tags for security purposes. You have to use `jQuery.parseHTML()`.

**Comment by raxan** [comment]
Thanks.
I was able to fix issue, is required to call FB.XFBML.parse(); after ajax.
And the js code can be included after <body> 

```html
<div id="fb-root"></div>
<script>(function(d, s, id) {
var js, fjs = d.getElementsByTagName(s)[0];
if (d.getElementById(id)) return;
js = d.createElement(s); js.id = id;
js.src = "https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.3";
fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
```

However, with many embed, is very slow.. I need to find a way to lazyload them.

Thanks for your library!

**Comment by misner** [comment]
Raxan, I am running into exactly the same issue: did you manage to lazy load Embeds from facebook ?
