### ISSUE TITLE
embeds code dimensions

### ISSUE THREAD

**Issue by EazyServer** [oscarotero/Embed#142]
Hi, first I would like to thank you for this awesome work :)

Second, is it possible to preset the dimensions of the embed code? 
For example all youtube videos `$info->code` ifram are 480px, is it possible to set to different val?

Thanks

**Comment by oscarotero** [comment]
Hello.
No, but you can use css for this purpose as is explained in #65

**Comment by EazyServer** [comment]
Thanks for pointing it out 👍
