### ISSUE TITLE
Tests actively using live environments?

### ISSUE THREAD

**Issue by Firesphere** [oscarotero/Embed#143]
From the looks of it, your tests all run against an actual live environment, getting real data from the embed method. Is that correct? If so, that's a strange choice on testing.

**Comment by oscarotero** [comment]
Yes that's correct. The reason is to allow to detect possible API changes or deprecate shutted down pages (like rdio.com). I know that it's strange and sometimes a bit nightmare, but because this library is intended to use in the real (and wild) world, this is a way to catch possible real issues.

**Comment by Firesphere** [comment]
Makes sense.
