### ISSUE TITLE
Implement Facebook Oembed

### ISSUE THREAD

**Issue by Firesphere** [oscarotero/Embed#144]
As per documentation, Facebook now has an Oembed endpoint:
https://developers.facebook.com/docs/plugins/oembed-endpoints

**Comment by oscarotero** [comment]
Good news!

As I can see, the oembed endpoint is discovered automatically via the `<link>` tag so no changes are needed. But this deprecates the use of the facebook api, so the custom adapter, provider and the need to configure an api key will be removed. Easier = Better

Thank you.

**Comment by oscarotero** [comment]
The version 2.7.1 has been released removing the facebook specific implementation in favor of the generic oembed provider.

**Comment by Firesphere** [comment]
Cool, seems to work fine for me! I'll have to write a test for my own specific implementation, but visual inspection shows it's all good.
