### ISSUE TITLE
Fails when OEmbed endpoint returns an array for certain data

### ISSUE THREAD

**Issue by stevecoug** [oscarotero/Embed#145]
http://www.hookem.com/story/texas-shortstop-joe-baker-arrested-public-intoxication/

This OEmbed endpoint returns an array for the thumbnail_url. This gets added to the Bag, but when you try to get the image, it fails trying to trim() an Array.

Here's an example that will break it:

$config = [ "resolver" => [ "class" => 'Embed\\RequestResolvers\\Curl', ], ];

$url = "http://www.hookem.com/story/texas-shortstop-joe-baker-arrested-public-intoxication/";
$og = \Embed\Embed::create($url, $config);

$image = $og->image;

PHP Warning:  trim() expects parameter 1 to be string, array given in /www/code/vendor/embed/embed/src/Url.php on line 495

I can work around the problem by checking for array values in Providers/OEmbed.php line 195 -- the thumbnail_url check in getImagesUrls(), but I don't think that's a good long term solution.

**Comment by oscarotero** [comment]
Hi, Steve.
Yes, the returned value must be checked and use an `array_merge` if the type is an array. And this might be done with the other values (thumbnai and image). If you want to send a PR with this fix, I appreciate it.
Thank you.

**Comment by oscarotero** [comment]
The version 2.7.1 has been released including this fix. Thanks
