### ISSUE TITLE
Facebook oEmbed does not work for company pages

### ISSUE THREAD

**Issue by Nebel54** [oscarotero/Embed#147]
I stumbled over a problem today, trying to embed this facebook post using the current master branch:
https://www.facebook.com/TheIndependentOnline/posts/10153659888571636

If you look at the json+oembed link in the browser, the valid oembed url is returned: https://www.facebook.com/plugins/post/oembed.json/?url=https%3A%2F%2Fwww.facebook.com%2FTheIndependentOnline%2Fposts%2F10153659888571636

But if you try to fetch the same url as anonymous user (or via guzzle), facebook internally redirects you to https://www.facebook.com/TheIndependentOnline/ and the returned oEmbed-Link is wrong:
https://www.facebook.com/plugins/page/oembed.json/?url=https%3A%2F%2Fwww.facebook.com%2FTheIndependentOnline%2F

To make things a bit more interesting, normal user posts are still embed-able.

So I'm not sure what the best approach to handle this problem is. I think either, facebook needs to stop this unpredictable behaviour (not sure if this will happen), or the facebook adapter needs to be re-implemented again.

**Comment by Nebel54** [comment]
Related to #144

**Comment by oscarotero** [comment]
mmm, I cannot reproduce this error.
In the demo page it works fine: https://oscarotero.com/embed2/demo/index.php?url=https%3A%2F%2Fwww.facebook.com%2FTheIndependentOnline%2Fposts%2F10153659888571636

May be something related with your ip address or something like that?

**Comment by Nebel54** [comment]
Thanks for the quick reply. Thats weird, i already checked it and made the same curl request on two of our liveservers. Everywhere is the post id missing in the json+oembed link.

Is the demo page running on the current master version?

**Comment by oscarotero** [comment]
Yes, the demo is up-to-date with master, running with the default configuration (curl resolver).

**Comment by oscarotero** [comment]
And seems like travis can run it without problems: https://travis-ci.org/oscarotero/Embed/builds/133399693

**Comment by Nebel54** [comment]
Wow, thanks for your efforts. I'm convinced now, that everything *should* work ;) I'll do some more tests from home and report back.

**Comment by Nebel54** [comment]
Ha! Just tried the same curl request from our server in Straßbourg. It works from there. Maybe facebook just gives Austrian and German IPs a special treatment :(

**Comment by oscarotero** [comment]
I don't know :(. Maybe it's something that can be posted to facebook developers forum (if there's any).

**Comment by Grienauer** [comment]
@oscarotero you can close this issue.
this bug was fixed by facebook (because now it works and the redirect is gone).

thx!

**Comment by oscarotero** [comment]
Good to know!
