### ISSUE TITLE
new Facebook video oembed endpoint

### ISSUE THREAD

**Issue by Grienauer** [oscarotero/Embed#148]
Facebook has now an own endpoint for video posts.

Now, a video post embeded with the library will only show the text but not the video itself.
Here a test video post: https://www.facebook.com/acolono/videos/10154107990797381/

check ist via https://developers.facebook.com/docs/plugins/embedded-posts
you will only see the post text but no video

if you test it with https://developers.facebook.com/docs/plugins/embedded-video-player
just the video will be shown

the oembed endpoint has now a separated /video/ url
documentation: https://developers.facebook.com/docs/plugins/oembed-endpoints

hope this is a minor fix :)

**Comment by oscarotero** [comment]
Thanks for the feedback. I've added an oembed provider for facebook with these two endpoints.
