### ISSUE TITLE
providerName sometimes returns part of domain

### ISSUE THREAD

**Issue by jamestowers** [oscarotero/Embed#150]
For the url `http://www.redrooster.org.uk`, providerName returns `org`

**Comment by oscarotero** [comment]
Thank you for the feedback. I've commited a change to fix this.
Currenly only the domains `co`, `com` and now `org` are considered but I don't know how to get all possible combinations of first level domains with two parts. For example, is it possible to have a `*.info.uk`, `*.net.uk`...?

**Comment by jamestowers** [comment]
Speedy, thanks!
I'm not sure what other .uk domains there are to be honest, `*.gov.uk` is the only one I can think of right now.

**Comment by oscarotero** [comment]
I found this: https://en.wikipedia.org/wiki/Second-level_domain 🎉

**Comment by jamestowers** [comment]
Ah nice!

**Comment by oscarotero** [comment]
Ok, finally I found and used this list with all combinations allowed: https://publicsuffix.org/list/public_suffix_list.dat
