### ISSUE TITLE
open_basedir restriction

### ISSUE THREAD

**Issue by ojfrs** [oscarotero/Embed#151]
I'm using v1.8.3 because i'm on PHP 5.3
I run into the issue of safe_mode and open_basedir restriction.
I'm ok with safe_mode which is turned off.
But i can't delete open_basedir values, because my website would not run.

So is there a solution to run the script in my case ?

Thanks

**Comment by oscarotero** [comment]
Hello. Sorry but I don't understand your problem. What error are you getting?

**Comment by eusonlito** [comment]
Maybe this error:

```
Warning: curl_setopt() [function.curl-setopt]: CURLOPT_FOLLOWLOCATION 
cannot be activated when in safe_mode or an open_basedir is set in ...
```

**Comment by oscarotero** [comment]
Ok, there's a 1.8.4 release implementing the fix created by @eusonlito
