### ISSUE TITLE
How can I configure what request return?

### ISSUE THREAD

**Issue by fehmathais** [oscarotero/Embed#152]
Hello, I'm implementing this package to solve links stored in my databases and convert to link embed in views. Is there any possibility to configure what request returns?

I would like just links embeded.

**Comment by oscarotero** [comment]
Hello. I don't understand what do you mean with "configure what request returns". You can use an array as second argument to configure some aspects (as explained in README), for example:
```php
$info = Embed::create($url, $config);
```
