### ISSUE TITLE
Suggestion Adding discovery for oembed code

### ISSUE THREAD

**Issue by onigetoc** [oscarotero/Embed#157]
For example, all Wordpress website now have the oembed url in the Header
`<link rel="alternate" type="application/json+oembed" href="http://example.com/wp-json/oembed/1.0/embed?url=http%3A%2F%example.com%2article%2title" />`

**Comment by oscarotero** [comment]
Hello. This feature is already implemented. You know any url that does not work?

**Comment by onigetoc** [comment]
Sorry for that, i just saw that the code do not appear in your demo but the code is there,
example: https://oscarotero.com/embed2/demo/index.php?url=http://reveilletoi.com/spiritualite/la-mediumnite-et-le-monde-de-la-mort

**Comment by oscarotero** [comment]
Ah, ok. It's because the demo is in `https` and the embed code is `http`, so it's not safe mix content.
