### ISSUE TITLE
Support open graph

### ISSUE THREAD

**Issue by onigetoc** [oscarotero/Embed#159]
Hi, me again.
I wanted more infos like Author name. 
From this example URL: https://broadly.vice.com/en_us/article/even-a-tiny-bit-of-exercise-will-help-you-not-die-study-says
I find out a lot of Open graph informations. Like image, author, type, link ect.
Example: 
`<meta property="og:type" name="og:type" content="article" />`

**Comment by onigetoc** [comment]
I find ou there a opengraph.php in your scripts, but i cannot get the author.
For this example, it mean that if author have no result, we should have the open graph author name.

**Comment by oscarotero** [comment]
Hello. Thanks, I've fixed the author in opengraph. And about other values, Embed provides a set a standard values, but the providers can contain more info, depending of each site. You can get these values directly in this way:
```php
$info = Embed::create('https://broadly.vice.com/en_us/article/even-a-tiny-bit-of-exercise-will-help-you-not-die-study-says');

//Get the opengraph provider
$opengraph = $info->getProvider('opengraph');

//Get the data collected by opengraph
$data = $opengraph->bag->getAll();

//Or get a specific value
$type = $opengraph->bag->get('type'); //article
```

**Comment by onigetoc** [comment]
Great. 
thank you for this update and tips.
I also saw that you added snipplr.
