### ISSUE TITLE
Some sites returning incorrect title/description/image, etc no matter the URL

### ISSUE THREAD

**Issue by f1294823** [oscarotero/Embed#160]
I've found that every WIRED.com article returns the same title and description no matter the URL.

Here's a couple example URLs:

[https://oscarotero.com/embed2/demo/index.php?url=http%3A%2F%2Fwww.wired.com%2F%3Fp%3D2064839](https://oscarotero.com/embed2/demo/index.php?url=http%3A%2F%2Fwww.wired.com%2F%3Fp%3D2064839)
[https://oscarotero.com/embed2/demo/index.php?url=http%3A%2F%2Fwww.wired.com%2F%3Fp%3D2065285](https://oscarotero.com/embed2/demo/index.php?url=http%3A%2F%2Fwww.wired.com%2F%3Fp%3D2065285)
[https://oscarotero.com/embed2/demo/index.php?url=http%3A%2F%2Fwww.wired.com%2F%3Fp%3D2065652](https://oscarotero.com/embed2/demo/index.php?url=http%3A%2F%2Fwww.wired.com%2F%3Fp%3D2065652)

All of these articles return the same title:

> WIRED

And the same description:

> Get in-depth coverage of current and future trends in technology, and how they are shaping business, entertainment, communications, science, politics, and culture at Wired.com.

And the same _everything_, even though each article has completely different content (try going to each of the 3 links above).

What's going on here? Why is it returning these results?

**Comment by oscarotero** [comment]
Seems like wired returns always `wired.com` as the canonical url in the opengraph provider.
I've fixed this accepting only canonical urls not pointing to homepage.
Thanks
