### ISSUE TITLE
How to catch the embed url of videos? (not embed code)

### ISSUE THREAD

**Issue by sullysheperd** [oscarotero/Embed#162]
Hi 
Thank you for your great package. 

This should be simple but I can't figure it: How can I fetch the embed url of a video? The package currently gives me the embed code, but I need the value of "src" of it. For example:

`<iframe width="480" height="270" src="https://www.youtube.com/embed/RrCLGWue3Y4?feature=oembed" frameborder="0" allowfullscreen></iframe>`

I need "https://www.youtube.com/embed/RrCLGWue3Y4?feature=oembed". 

(in case you're wondering why, it's because that's what semantic's embed plugin needs to work). Thanks

**Comment by oscarotero** [comment]
The embed code is returned by youtube, using the oEmbed API, so to fetch the src value, you need a regular expression or something like this.
But I can see in the collected data https://oscarotero.com/embed2/demo/index.php?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DRrCLGWue3Y4 that twitter has the value `player` that returns the url of the video, so I guess you can get it from here:
```php
$info = Embed::create($url);
$twitter = $info->getProvider('twittercards');
$src = $twitter->bag->get('player');
```

**Comment by sullysheperd** [comment]
Thank you! Works like a charm. It'll be great to add it to the docs, it seems like regular user. 

Thanks again
