### ISSUE TITLE
Not really a issue but need some help to get external URL content

### ISSUE THREAD

**Issue by onigetoc** [oscarotero/Embed#164]
I want to create a Wordpress plugin with your great code.

But whit some shared server, i got error 403 when trying to retrieve a remote website informations. it mean that you can't make external url query like this: http://mywebsite.com/?url=http://www.externalwebsite.com
php, json request ect... will not work.

In the Wordpress codex, there's is a way to get a remote website header or body info with a Wordpress function that make it possible even on some restricted server. 
With the function: wp_remote_get (It worked on some smaller projects where CURL or file_get_contents didn't work)
https://codex.wordpress.org/Function_Reference/wp_remote_get

In your project, where can i replace the CURL or the main way where you get the remote website content with this Wordpress function?

If you have time for this, let me know.

Regard.

**Comment by oscarotero** [comment]
You need to create a request resolver class implementing the `RequestResolverInterface`, as you can see here: https://github.com/oscarotero/Embed/tree/master/src/RequestResolvers
To get the images info (width, height, mime type, etc) you have to create a class implementing the `ImageInfoInterface` (to get the info of one image) and `ImagesInfoInterface` to get the info of serveral images at once (https://github.com/oscarotero/Embed/tree/master/src/ImageInfo)
Once you get the class, need to configure Embed to use these classes instead the defaults:

```php
$info = Embed::create($url, [
     'resolver' => [
        'class' => 'WordpressRequestResolver',
    ],
     'image' => [
        'class' => 'WordpressImageInfo',
    ]
]);
```

**Comment by onigetoc** [comment]
Thank you, i will try it.

**Comment by onigetoc** [comment]
Hi, i watched these files but do not really understand how to include my Wordpress functions in it.
I want to create i kind of Oembed everything that will look like the Wordpress Oembed.
demo: http://codesniff.com/Embed/demo/embed-all.php?url=https%3A%2F%2Fwordpress.org%2Fplugins%2Fcrelly-slider%2F

**Comment by oscarotero** [comment]
First, you must create a wordress based request resolver, implementing the `RequestResolverInterface`. Here's an incomplete example:

```php
use Embed\RequestResolvers\RequestResolverInterface;

class WordpressRequestResolver implements RequestResolverInterface
{
    private $url;
    private $config;
    private $response;

    public function __construct($url, array $config)
    {
        $this->url = $url;
        $this->config = $config;
    }

    public function getHttpCode()
    {
        $response = $this->getResponse();
        return $response['response']['code'];
    }

    public function getMimeType()
    {
        // Get the content-type of the url, for example: text/html.
    }

    public function getError()
    {
        // Returns the connection error if exists.
    }

    public function getContent()
    {
        $response = $this->getResponse();
        return $response['body'];
    }

    public function getUrl()
    {
        //returns the final url (after possible redirections)
    }

    public function getRequestInfo()
    {
        //returns info for debug purposes
    }

    public function getHeaders()
    {
        $response = $this->getResponse();
        return $response['headers'];
    }

    private function getResponse()
    {
        if ($this->response === null) {
            $this->response = wp_remote_get( $this->url, $this-config);
        }
        return $this->response;
    }
}
```

And then, configure Embed to use this class instead the default (which use curl).

**Comment by neverything** [comment]
Hey @onigetoc have you ever built the plugin? Is it somehow available?
