### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by landman** [oscarotero/Embed#165]
Hey (-:

I often get this error:
(for example with Buzzfeed RSS Feed - https://www.buzzfeed.com/world.xml)

> Fatal error: Uncaught exception 'InvalidArgumentException' with message 'Embed::create only accepts instances of Embed\Request or strings' in C:\xampp\htdocs\Trends\site\_cron\oembed\Embed.php:130 Stack trace: #0 C:\xampp\htdocs\Trends\site\_cron\oembed\Embed.php(22): Embed\Embed::getRequest(Object(SimpleXMLElement), NULL) #1 C:\xampp\htdocs\Trends\site\_cron\database.php(16): Embed\Embed::create(Object(SimpleXMLElement)) #2 C:\xampp\htdocs\Trends\site\_cron\food.php(9): require_once('C:\xampp\htdocs...') #3 {main} thrown in C:\xampp\htdocs\Trends\site\_cron\oembed\Embed.php on line 130

What can i do? 

Best from Berlin,
Dennis

**Comment by oscarotero** [comment]
You have to pass a string with the url to `Embed::create()`. This error tells you are passing a instance of SimpleXMLElement.

**Comment by landman** [comment]
Ohhh. I understand! I get the Links from RSS Feed. I test it now with (string)<URL> and it works! :D Its sooo easy. Thank you!
