### ISSUE TITLE
Create from raw/html

### ISSUE THREAD

**Issue by JanPetterMG** [oscarotero/Embed#171]
Is there a way to use Embed without having to (re)download the URL content?

The raw content is already downloaded for internal usage, and I'm looking for a way to bypass `Embed::create()`. Either by passing an existing GuzzleHttp v6 response object (`\Psr\Http\Message\ResponseInterface`), or by passing the content and it's headers as parameters somewhere.

**Comment by oscarotero** [comment]
Please, see this issue #18

**Comment by JanPetterMG** [comment]
Thanks!
