### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by marshallunduemi** [oscarotero/Embed#174]
Fatal error: Class 'TestCaseBase' not found in C:\Program Files\xampp\htdocs\tutorials\Embed-master\test\fbtest.php on line 3

How can fix this thanks...

**Comment by oscarotero** [comment]
you have to configure phpunit to use `tests/bootstrap.php` file or use the xml config file: https://github.com/oscarotero/Embed/blob/master/phpunit.xml#L1
