### ISSUE TITLE
Fatal error: Call to undefined function

### ISSUE THREAD

**Issue by marshallunduemi** [oscarotero/Embed#175]
Fatal error: Call to undefined function Embed\ImageInfo\finfo_open() in C:\Program Files\xampp\htdocs\tutorials\Embed-master\src\ImageInfo\Curl.php on line 46

**Comment by oscarotero** [comment]
You need [fileinfo](http://php.net/manual/en/book.fileinfo.php) extension enabled (it should be enabled by default).

**Comment by marshallunduemi** [comment]
Thanks for quick reply, really appreciated.
All work fine now but the time it's take to load page is much, is there
anyway to reduce page load?
