### ISSUE TITLE
Find de RSS in page?

### ISSUE THREAD

**Issue by onigetoc** [oscarotero/Embed#176]
It would be intersting to find all RSS on the page. I already write a php script to find all rss on a web page.
http://www.tutorialspoint.com/php_webview_online.php?PID=0Bw_CjBb95KQMTC1WOVVETkJqU2M
Click the TAB preview to view the result.

Is there a way to get only the header content?

**Comment by oscarotero** [comment]
There's the `source` property that returns the rss feed, for example:

https://oscarotero.com/embed2/demo/index.php?url=http%3A%2F%2Fsoftplug.com

Unfortunally, it returns only one value (the first found). Maybe should be changed to return an array of values.

**Comment by oscarotero** [comment]
The new 3.0 version has the property `feeds` returning an array with all feeds found.
