### ISSUE TITLE
instagram oembed

### ISSUE THREAD

**Issue by haakony** [oscarotero/Embed#177]
Hello 
I am having some problems getting a OEmbed on my production server, but it works just fine on my dev wamp server.
Can you think of any reason why that happens?

on the production server $info->code just gets me the video of this example(https://www.instagram.com/p/BNrk96CgVQT/) , but on the dev it gets the full embed code.
And i noticed the "bag" was empty on the production server.
it also works just fine on your demo.

"oembed" => OEmbed {#206 ▼
      #config: array:3 [▶]
      +bag: Bag {#213 ▼
        #parameters: array:15 [▼
          "provider_url" => "https://www.instagram.com"*

"oembed" => OEmbed {#206 ▼
      #config: array:3 [▶]
      +bag: Bag {#213 ▼
        #parameters: []
      }

**Comment by oscarotero** [comment]
There's no easy way to debug this. I'd like to refactor this library to provide an easy way to inspect the requests but I not have enought time currently.
You can do a `var_dump` [here](https://github.com/oscarotero/Embed/blob/master/src/Providers/OEmbed.php#L36) to check if the correct oembed endpoint url is detected.

**Comment by haakony** [comment]
Hi
Maybe i missunderstand but.
If its the $endPoint I am dumping then that returns NULL on both.

**Comment by oscarotero** [comment]
In theory, `$endPoint` should be the url used for the oembed request.
There's two ways to get this url:

* From the html code [here](https://github.com/oscarotero/Embed/blob/master/src/Providers/OEmbed.php#L29), with the function `getEndPointFromDom()`
* Or from the url host [here](https://github.com/oscarotero/Embed/blob/master/src/Providers/OEmbed.php#L30) that returns [this value](https://github.com/oscarotero/Embed/blob/master/src/Providers/OEmbed/Instagram.php#L12)

Can you test if any of these functions are executed and what value returns?

**Comment by haakony** [comment]
Hey

if i dd($endPoint); on OEmbed.php line 35 then i get the link(http://api.instagram.com/oembed) on both servers.
The $html seems to be the same on both servers.

**Comment by haakony** [comment]
found that i am getting a 302 error on https://youtu.be/EShUeudtaFg allso 
but its working on my dev machine 

InvalidUrlException in Embed.php line 51:
The url 'http://youtu.be/EShUeudtaFg' returns the http code 302

**Comment by oscarotero** [comment]
Ok, seems like it's not following redirections. Redirections are disabled under some php config because this: https://github.com/oscarotero/Embed/issues/151

Here's the code detecting if disable or not redirections:
https://github.com/oscarotero/Embed/blob/master/src/RequestResolvers/Curl.php#L163

**Comment by haakony** [comment]
Hey, Thank you.
I just removed the entire if sentence and it works 👍
