### ISSUE TITLE
Support for Windows-1250

### ISSUE THREAD

**Issue by fast4shoot** [oscarotero/Embed#180]
Hello,

I often need to get information on websites that use Windows-1250 as their encoding. This fails in Http/Response.php on `mb_convert_encoding` throwing a "Illegal character encoding specified" exception.

This is understandable, as `mb_convert_encoding` [doesn't support Windows-1250](http://php.net/manual/en/mbstring.supported-encodings.php). Unfortunately this limits the usefulness of Embed.

Perhaps it would be a better idea to use iconv instead of mb_convert_encoding, or even to use both.

**Comment by oscarotero** [comment]
Mmm, interesting. Can you give me any url with Windows-1250 encoding for testing?
Thanks

**Comment by fast4shoot** [comment]
Definitely. Here's one: http://www.idnes.cz/.

If you put it into [your online demo](https://oscarotero.com/embed3/demo/index.php?url=http%3A%2F%2Fwww.idnes.cz%2F), you can immediately see the warning coming from `mb_convert_encoding` and you'll notice that all the accented characters are replaced with question marks.

**Comment by oscarotero** [comment]
Hello. After try with `iconv` I have a deprecation warning, so finally I still using `mb_convert_enconding` but checking before if the charset is supported or not. If this works for you, I can tag a new version, or if you find a better way to fix this, feel free to create a pull request.

**Comment by Keeo** [comment]
Hello, what is the problem with `iconv`? As far as I know only some [variable configurations](http://php.net/manual/en/migration56.deprecated.php) are deprecated and not `iconv` itself. So `iconv($charset, "UTF-8", $content)` should probably work.

**Comment by oscarotero** [comment]
Yes, sorry. I was misusing it. Added again iconv. Now it should work fine.

**Comment by fast4shoot** [comment]
I did a few tests and everything seems to work fine, thank you.

**Comment by oscarotero** [comment]
cool
