### ISSUE TITLE
Installation without Composer

### ISSUE THREAD

**Issue by exoloner** [oscarotero/Embed#182]
Using Apache with PHP/5.6.8 cURL is enabled.

In my /index.php
I'm using something like this : 

```
require_once 'phplibs/Embed.php';
use Embed\Embed;

//Load any url:
$info = Embed::create('https://www.youtube.com/watch?v=PP1xn5wHtxE');

print_r($info);
exit;
```

Returning this error:

**Fatal error**: Class 'Embed\Http\Url' not found in 
Path to htdocs\phplibs\Embed.php on line 24

I cannot use/configure/install the composer thing on the server.

The require worked though seems some namespaces are being lost in the way up ?
Is there any chance you update the documentation "Installation" section to "without Composer" ?

**Comment by oscarotero** [comment]
Currently, the 2.x version has an autoloader.php file so you can use it without composer:
https://github.com/oscarotero/Embed/tree/v2.x#installation
For 3.x version, you can use the same file (https://github.com/oscarotero/Embed/blob/v2.x/src/autoloader.php) but it's not included (you should copy/paste from v2.x branch) or use any psr-4 loader (https://github.com/search?o=desc&q=psr-4&s=stars&type=Repositories&utf8=%E2%9C%93)

**Comment by exoloner** [comment]
note: Everybody starts with the 3.x GitHub current version Install readme and thus obviously missing the 2.x instructions talking about the autoloader.php

Fine for me, worked really great!
Thanks you so much!

**Comment by oscarotero** [comment]
I removed the autoloader.php file because I think this library should not be responsive of providing a psr-4 loader. But maybe this information should be in the readme.

**Comment by exoloner** [comment]
Thanks!!
Just for the sake of making people's life easies, and a "fresh new out of
the box & running" feel.

btw:
The whole libraries suffer from permissions fatal errors on some
hostings(professional ones), specially in the CuRlDispatcher constructor,
while it's trying to find some place to write a cookie. and fails 3 times,
cracking all the library to death.
Does PHP not provide a standard and "safe" way to store session
information, instead of trying to write you own cookies somewhere ?
Thoughts, just thoughts, i'm not too much in to your lib.


2017-01-23 20:12 GMT+01:00 Oscar Otero <notifications@github.com>:

**Comment by oscarotero** [comment]
The cookies file is an [option of curl](http://php.net/manual/en/function.curl-setopt.php), as you can [see here](https://github.com/oscarotero/Embed/blob/master/src/Http/CurlDispatcher.php#L47). Maybe this could be configurable to allow to change the file instead define it automatically.
