### ISSUE TITLE
Unable to generate preview for mixcloud. 

### ISSUE THREAD

**Issue by kamrankr** [oscarotero/Embed#183]
**Sample Url for mixcloud:**
https://www.mixcloud.com/twofriendsmusic/2f-friendly-sessions-ep-16-includes-prince-fox-guest-mix/

**Oembed provider response from mixcloud for above url:**
https://www.mixcloud.com/oembed/?format=json&light=1&url=https%3A%2F%2Fwww.mixcloud.com%2Ftwofriendsmusic%2F2f-friendly-sessions-ep-16-includes-prince-fox-guest-mix%2F 

 I have tested the url from my server as well as on demo link provider, both shows the same problem. "invalid url". Following is the example url tested on demo. 

https://oscarotero.com/embed3/demo/index.php?url=https%3A%2F%2Fwww.mixcloud.com%2Ftwofriendsmusic%2F2f-friendly-sessions-ep-16-includes-prince-fox-guest-mix%2F

**Comment by oscarotero** [comment]
The url returns a 403 code, but testing from local works fine. So the problem is that mixcloud is blocking requests executed from some servers. I think there's nothing that Embed can do to fix this.

**Comment by tschoffelen** [comment]
Yes, Mixcloud seems to block your server for some reason, works fine on my server.
