### ISSUE TITLE
Giphy embed has changed?

### ISSUE THREAD

**Issue by l0c0luke** [oscarotero/Embed#185]
We have been embedding giphys without problem but today it was reported to me that a URL didn't work. Which also does not work in the demo link you provide. Just wanted to report it here to see if maybe indeed it did change. 

http://giphy.com/gifs/electriccyclery-bike-frogs-3oz8xEXfFbaNMRfWsU

**Comment by oscarotero** [comment]
Currently it's working. https://oscarotero.com/embed3/demo/index.php?url=http%3A%2F%2Fgiphy.com%2Fgifs%2Felectriccyclery-bike-frogs-3oz8xEXfFbaNMRfWsU

Maybe it was a temporal error

**Comment by l0c0luke** [comment]
It would seem giphy continues to be an issue. The link you post above, returns a 403 error in the returned html page it gets.

it seems giphy does offer a meager oembed endpoint... from oembed.com...

```
GIPHY (https://giphy.com)

URL scheme: https://giphy.com/gifs/*
URL scheme: http://gph.is/*
URL scheme: https://media.giphy.com/media/*/giphy.gif
API endpoint: https://giphy.com/services/oembed
Example: https://giphy.com/services/oembed?url=https%3A%2F%2Fgiphy.com%2Fgifs%2Fcant-hardly-wait-kW8mnYSNkUYKc
Supports discovery via <link> tags
```

somebody from wordpress complained to giphyy github and their response was to use that endppoint above, and then you can get the `slug` more easily, and then you can manually recreate their iframe embed code that they give you on the regulsr image page.

**Comment by oscarotero** [comment]
Seems like giphy detect Embed as a robot and show this page:

<img width="1223" alt="imaxe" src="https://user-images.githubusercontent.com/377873/57410628-9bffda00-71eb-11e9-8ee4-211391ea45b5.png">
