### ISSUE TITLE
Some server can not be fetch

### ISSUE THREAD

**Issue by onigetoc** [oscarotero/Embed#186]
Some server have 403 error.
https://oscarotero.com/embed3/demo/index.php?url=https%3A%2F%2Fpremium.wpmudev.org%2Fblog%2Fembedding-wordpress-oembed%2F

I try to do my own php script meta info crawler based on this script.
https://github.com/onassar/PHP-MetaParser

To grab page content It use https://github.com/onassar/PHP-Curler 

And i never see PHP-Curler fail until now.
My demo: http://feedsocial.com/lab/scrapping/PHP-MetaParser-master/demo.php?url=https%3A%2F%2Fpremium.wpmudev.org%2Fblog%2Fembedding-wordpress-oembed%2F

**Comment by oscarotero** [comment]
Seems the problem is in the user-agent, that by default is "Embed PHP Library". After change it for a more realistic one (like the used in your script), it works fine.
