### ISSUE TITLE
I can't use composer. Where's is the autoload.php file?

### ISSUE THREAD

**Issue by onigetoc** [oscarotero/Embed#187]
I can't use composer. Where's is the autoload.php file?

**Comment by oscarotero** [comment]
https://github.com/oscarotero/Embed/issues/182

**Comment by onigetoc** [comment]
Fatal error: Class 'Embed\Http\CurlDispatcher' not found in ................../Embed/demo/index.php on line 230

http://codesniff.com/Embed/demo/index.php?url=http%3A%2F%2Fwww.breitbart.com%2Fbig-government%2F2017%2F01%2F25%2Fassociated-press-throws-tempter-tantrum-over-snub-by-trump-press-secretary-spicer%2F

**Comment by onigetoc** [comment]
Ok, i put the old autoload in the src file like de V2 and it's working. 
Using composer just for that??
