### ISSUE TITLE
Embed Gist is broken

### ISSUE THREAD

**Issue by onigetoc** [oscarotero/Embed#188]
https://oscarotero.com/embed3/demo/index.php?url=https://gist.github.com/MarQuisKnox/888df92d8a91557e2332

Still working
https://oscarotero.com/embed2/demo/index.php?url=https://gist.github.com/MarQuisKnox/888df92d8a91557e2332

**Comment by onigetoc** [comment]
And Twitter too.
https://oscarotero.com/embed3/demo/index.php?url=https://twitter.com/realDonaldTrump/status/824227824903090176%3fref_src=twsrc%255Etfw

Still working
https://oscarotero.com/embed2/demo/index.php?url=https://twitter.com/realDonaldTrump/status/824227824903090176%3fref_src=twsrc%255Etfw

**Comment by oscarotero** [comment]
Fixed in the new release.

**Comment by onigetoc** [comment]
Do not work
http://codesniff.com/Embed/demo/index.php?url=http%3A%2F%2Fwearechange.org%2Fchinese-nukes-prepared-response-inauguration-donald-trump%2F

**Comment by oscarotero** [comment]
It works fine here: https://oscarotero.com/embed3/demo/index.php?url=http%3A%2F%2Fwearechange.org%2Fchinese-nukes-prepared-response-inauguration-donald-trump%2F
What version of php are you using?

**Comment by onigetoc** [comment]
Work on your but not on mine, i replaced all src files.

**Comment by onigetoc** [comment]
By the way, the zip file do not contain the demo folder anymore

**Comment by oscarotero** [comment]
Ok, you may be using php5.4 (or lower), that does not support arbitrary expressions like `empty($content = $this->content)`.
Embed v3 supports php 5.5 or upper, so you have to use embed v2 for older php versions.

The demo folder is not included in the exported zip file for security reasons.

**Comment by onigetoc** [comment]
It worked before the last update except for Twitter and Gist, Most server are not php 5.5

**Comment by onigetoc** [comment]
Breaking everything for one line of code.
I fix it with
```
$content = $this->content;
if (empty($content)) { 
   return $this->htmlContent = false;
}
```
