### ISSUE TITLE
UFT-8 encoding issue in french?

### ISSUE THREAD

**Issue by onigetoc** [oscarotero/Embed#190]
Hello me again :)

Encoding issue in french in title and Description 
https://oscarotero.com/embed3/demo/index.php?url=https://allergies.ooreka.fr/astuce/voir/587661/allergie-a-la-betterave

**Comment by oscarotero** [comment]
fixed. Thank you

**Comment by onigetoc** [comment]
Can you point me the file where the modification is please?
