### ISSUE TITLE
Too much bugs for V3 not ready

### ISSUE THREAD

**Issue by onigetoc** [oscarotero/Embed#191]
Multiple URLs do not work

http://www.allotoi.com/sports/colonnes-de-lumiere-dans-la-nuit-canadienne
http://reveilletoi.com/spiritualite/les-crises-de-lego
http://codesniff.com/plugins/rss-feeds-news-blocks-wordpress-plugins-for-rss
http://softplug.com

V3 Do not work
https://oscarotero.com/embed3/demo/index.php?url=http://www.allotoi.com/sports/colonnes-de-lumiere-dans-la-nuit-canadienne
V2 still working
https://oscarotero.com/embed2/demo/index.php?url=http://www.allotoi.com/sports/colonnes-de-lumiere-dans-la-nuit-canadienne

V3 Do not work
https://oscarotero.com/embed3/demo/index.php?url=http://softplug.com/fr/
V2 still working
https://oscarotero.com/embed2/demo/index.php?url=http://softplug.com/fr/

**Comment by oscarotero** [comment]
It seems that there's serveral sites returning different content depending of the user-agent request header. The default user-agent used was "Embed PHP Library", but [i changed it](https://github.com/oscarotero/Embed/commit/2908fa4615eac4981e6821d3aa03e8bb16956e54) to fix #186, and this change makes fail other sites, so I've [changed it again](https://github.com/oscarotero/Embed/commit/a05c1d0924ee0632b962357c320c6816189bf806) to fix the other cases and this makes fail these other sites.

Finally [I've found a user-agent](https://github.com/oscarotero/Embed/commit/00c23b4a7eb510c83859a8dfc79c2df919937693) that works fine in all cases (or so I think).

If you find more failing sites, please try to change the user agent.

**Comment by onigetoc** [comment]
For my own website parser, i also find that this User agent work every time.

`Mozilla/5.0 (Windows NT 6.1; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0`
