### ISSUE TITLE
Image.. Not as good as Version 2 ?

### ISSUE THREAD

**Issue by onigetoc** [oscarotero/Embed#192]
Image.. Not as good as Version 2 ?
I prefered much the V2 images choices

https://oscarotero.com/embed3/demo/index.php?url=http://ici.radio-canada.ca/nouvelle/1014200/attentat-quebec-trudeau-fox-news-kate-purchase-tweet-erreur-information-twitter-media

https://oscarotero.com/embed2/demo/index.php?url=http://ici.radio-canada.ca/nouvelle/1014200/attentat-quebec-trudeau-fox-news-kate-purchase-tweet-erreur-information-twitter-media

And the image of V2 show the Opengraph image og:image
http://opengraphcheck.com/result.php?url=http%3A%2F%2Fici.radio-canada.ca%2Fnouvelle%2F1014200%2Fattentat-quebec-trudeau-fox-news-kate-purchase-tweet-erreur-information-twitter-media
`https://images.radio-canada.ca/w_635,h_357/v1/ici-info/16x9/trudeau-premier-ministre.jpg` 
The same as Facebook will choose

**Comment by oscarotero** [comment]
This is because the v3 demo is configured with the option `choose_bigger_image` as `true` (in v2 is `false`). I've changed to false (it's the default value anyway).

**Comment by onigetoc** [comment]
Where and how can i set this to false?

**Comment by oscarotero** [comment]
You have all options documented in the readme https://github.com/oscarotero/Embed#example-with-all-options
