### ISSUE TITLE
Image do not show in V3

### ISSUE THREAD

**Issue by onigetoc** [oscarotero/Embed#194]
https://oscarotero.com/embed3/demo/index.php?url=http://www.forbes.com/sites/kalevleetaru/2016/10/31/has-social-media-killed-free-speech/#6c7a4ed71f2d

https://oscarotero.com/embed2/demo/index.php?url=http://www.forbes.com/sites/kalevleetaru/2016/10/31/has-social-media-killed-free-speech/#6c7a4ed71f2d

**Comment by oscarotero** [comment]
That's because the user agent (again).
If it's changed to the same than v2 (`PHP Embed library`) works fine. I don't know how to solve this. There's not an user agent that works fine in all cases. The only solution I see is use various user agents depending of the url. But this can be hard to maintain.

**Comment by oscarotero** [comment]
Ok, to handle with this situation, I've created the new `Embed\Http\UserAgent` class that allows to configure different user agents for different urls. So, you only have to do the following:

```php
//Configure to use a user agent in some urls:
$ua = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 Safari/537.36';
$urls = [
    '*.mysite.com*',
    '*.mysite-2.com*',
];
Embed\Http\UserAgent::add($ua, $urls);

//Use it
$info = Embed\Embed::create('http://mysite.com/foo');
```

Let me know if this work fine before create a new tag with this.
Thanks.

**Comment by onigetoc** [comment]
Yeah, i think it too complicated or i mean, too much URLs to begin to filter each one.

**Comment by oscarotero** [comment]
Ok, finally I find a more automatic way to handle this: If the response is 403, retry again with a different user agent. It seems to work fine now.
