### ISSUE TITLE
Wikipedia is broken

### ISSUE THREAD

**Issue by onigetoc** [oscarotero/Embed#195]
https://oscarotero.com/embed2/demo/index.php?url=https://fr.wikipedia.org/wiki/Cin%25C3%25A9ma_dynamique

https://oscarotero.com/embed3/demo/index.php?url=https://fr.wikipedia.org/wiki/Cin%25C3%25A9ma_dynamique

**Comment by oscarotero** [comment]
Fixed.

**Comment by onigetoc** [comment]
Can you tell me witch file is updated?
this? https://github.com/oscarotero/Embed/commit/e0043bb98e008825bb94e8df3be197ebe0e4e86d
Do it will break other thing fixed by the user agent?

**Comment by oscarotero** [comment]
The referenced commit is https://github.com/oscarotero/Embed/commit/714d2cdbdbaaa0667465dc13d5296c947c592b84 The problem was about the encoded chars in the url.
