### ISSUE TITLE
feature: autoplay on video type parameter

### ISSUE THREAD

**Issue by thanatos11** [oscarotero/Embed#196]
Does this library have autoplay parameter option? and if yes, what is the refference, if not, is it in any plan soon?

**Comment by oscarotero** [comment]
No. Autoplay is a feature of youtube videos and this library just get the data returned by the oembed endpoint, without modification.

**Comment by thanatos11** [comment]
OK, thanks. FYI, youtube and vimeo have same functionality with same parameter autoplay=1, i manage to process the returned iframe and add autplay to it. Thanks for your time anyway, it was just a suggestion.

**Comment by thanatos11** [comment]
solution: 

`$code = $info->code;

        $url_parts = parse_url($url);

        // for videos add autoplay for youtube and vimeo
        if($info->type == 'video' && ($url_parts['host'] == 'youtube.com' || $url_parts['host'] == 'www.youtube.com' || $url_parts['host'] == 'vimeo.com' || $url_parts['host'] == 'www.vimeo.com')){
        // for videos add autoplay check if the embed gets the code

            // create an easy html parser to verify the iframe and add autoplay for video types
            $dom = new DOMDocument;

            // set error level so that the html parser doesn't raise exceptions on warnings
            $internalErrors = libxml_use_internal_errors(true);

            $dom->loadHTML($code);

            // Restore error level
            libxml_use_internal_errors($internalErrors);

            // get the iframe
            $frame = $dom->getElementsByTagName('iframe')->item(0);

            //get the src from iframe
            $src = $frame->getAttribute('src');

            // check if url has any other parameters to properly add the parameter
            if (strpos($src,'?') !== false) {
                $src .= "&autoplay=1";
            } else {
                $src .= "?autoplay=1";
            }

            // set the new src with autoplay
            $frame->setAttribute('src', $src);

            // replace old iframe html with new one
            $code = htmlspecialchars_decode($dom->saveHTML($frame));
        }`
