### ISSUE TITLE
Invalid url 'http://null/' (Status code 0)

### ISSUE THREAD

**Issue by raymondelferink** [oscarotero/Embed#198]
Valid URL http://www.vpro.nl throws an Internal server error:
Invalid url 'http://null/' (Status code 0)

See: https://oscarotero.com/embed3/demo/index.php?url=http%3A%2F%2Fwww.vpro.nl

Can anyone see why? Is there anything we can do about that?

**Comment by oscarotero** [comment]
This is due an incorrect value of `og:url` meta tag in this page, that contains "http://null"
I'm not sure what is the best way to fix this.

**Comment by raymondelferink** [comment]
Hi Oscar, thanks for your swift reply! This mornign it seems the site in question has been updated and the issue has been lifted.
Cheers, Raymond
