### ISSUE TITLE
Status code !=200 throws InvalidUrlException

### ISSUE THREAD

**Issue by JanPetterMG** [oscarotero/Embed#202]
If HTTP code is anything else than 200, it throws `InvalidUrlException`. Why is that?
How about separating that into another exception instead, eg. `RequestException`?

Is there some way to disable throwing for status codes? config array variable?
btw. GuzzleHttp has an option `(bool) http_errors` in their config array, for such purposes...

**Comment by oscarotero** [comment]
The InvalidUrlException is throwed if the url does not match with any Adapter, so no data can be retrieved.
It's throwed here: https://github.com/oscarotero/Embed/blob/master/src/Embed.php#L78 after check whether the url is a file, has a domain adapter or matches with the default webpage adapter.
There's some adapters like youtube: https://github.com/oscarotero/Embed/blob/master/src/Adapters/Youtube.php#L18 that accepts also the code `429`.

Maybe the name is a bit confusing, but this exception is throwed just in this case. Why you should want to disable it?.

**Comment by JanPetterMG** [comment]
I'm mainly interested in filtering out invalid URLs, so that I can catch those exceptions and do some special treatment (eg. delete them from database, mark them as blacklisted, or similar). eg. when requesting an perfectly valid URL, but gets redirected to an invalid one...

In case of wrong Status Code, an separate exception should be generated. Preferably with an option to disable it, eg. if you're caching every single request, independent of amount data generated.
_I'm working on an custom bot, witch may easily request 20K+ unique URLs a day, so excluding everything that fails from the cache, causing them to potentially be requested multiple times, is just not the way to go..._

- `204 No content` basically 200 but without content. (I still want to cache it as 200)
- `304 Not modified` equals `200` if using the `ETag`, `If-Modified-Since` or `If-None-Match` headers (then I'll fetch from the cache instead)
- `403 Forbidden` (I'll try again using tor/proxy, and an random real-world browser User-Agent)

The simplest solution for me, is to hard-code everything `HTTP 200` in your library, but I'll expect there will be some negative consequences too. The only real alternative is therefore to write an custom dispatcher with it's own internal checks and a custom set of exceptions.

Consider this an Feature-request. How about an [Guzzle inspired structure](http://docs.guzzlephp.org/en/latest/quickstart.html#exceptions)?
- EmbedException
  - InvalidUrlException
  - TransferException
    - RequestException
      - ConnectException
      - BadResponseException
        - ClientException
        - ServerException
      - TooManyRedirectsException

It doesn't have to be this extensive, but keeping `<=399`, `4XX`, `5XX` and `invalid URL`s separate would be an huge improvement.

**Comment by oscarotero** [comment]
Why not simply try/catch the exception? For example:

```php
try {
    $info = Embed::create($url);
} catch (Embed\Exceptions\InvalidUrlException $exception) {
    $response = $exception->getResponse();
    $statusCode = $response->getStatusCode();
    //handle errors here
}
```

**Comment by JanPetterMG** [comment]
I'd overlook `$exception->getResponse()`.
Then there is a way around.
