### ISSUE TITLE
Can't embed videos from CNN or BBC

### ISSUE THREAD

**Issue by invasi0n** [oscarotero/Embed#204]
Hello,
Videos from CNN, BBC or NY Times can't be embed. `code` property is empty. 
Thanks

**Comment by oscarotero** [comment]
Can you provide some urls?

**Comment by invasi0n** [comment]
Hello,
For example:
https://oscarotero.com/embed2/demo/index.php?url=http%3A%2F%2Fwww.bbc.com%2Fnews%2Feducation-39388422

https://oscarotero.com/embed2/demo/index.php?url=http%3A%2F%2Fedition.cnn.com%2Fvideos%2Fpolitics%2F2017%2F03%2F17%2Fmcdonalds-tweet-trump-moos-erin-pkg.cnn

The response does not include the `code` property

**Comment by oscarotero** [comment]
Ok. I've created an adapter to CNN:
https://oscarotero.com/embed3/demo/index.php?url=http%3A%2F%2Fedition.cnn.com%2Fvideos%2Fpolitics%2F2017%2F03%2F17%2Fmcdonalds-tweet-trump-moos-erin-pkg.cnn
(note that we are in embed3, not embed2).

I didn't find a way to embed bbc videos.

**Comment by invasi0n** [comment]
Thank you very much! Somehow I missed your post...
