### ISSUE TITLE
Open Graph only available thru the Html provider

### ISSUE THREAD

**Issue by JanPetterMG** [oscarotero/Embed#206]
Most Open Graph data is only available thru the `Html` provider. That's a strange approach, isn't it?
I'm using `$provider->getBag()->getAll()`.

Applies to most property types, see http://ogp.me/#types

How about allowing those to be fetched from the `OpenGraph` class, and eventually ignore the prefixes in the `Html` class?

------------------

In the meantime, is there a native way to get properties with an specific prefix only, or is `strpos` the intended solution for such purposes? I'm asking because `->getAll()` sometimes returns really large arrays, counting up to 200 properties, where 90% of those is unwanted.

**Comment by oscarotero** [comment]
Opengraph provider get all values starting by `og:` or `og:article:`, but removing that prefix, so both following lines returns the same:

```php
$title = $info->getProviders['html']->bag->get('og:title');
$title = $info->getProviders['opengraph']->bag->get('title');
```
What open graph data is not available in opengraph provider?

---

No, there's no way to filter data by prefix.

**Comment by JanPetterMG** [comment]
I've been logging every single property and meta tag since I discovered the missing data, but cannot seem 
to find any traces of `og:article:*` in my logs. It's about 90K webpages, from the last 24 hours in there...
What I see all the time is `article:*`, from the `html` provider, without the `og:` prefix.

A simple test:
```html
<meta property="og:type" content="article">
<meta property="article:published_time" content="2017-04-10T19:50:02+00:00">
<meta property="article:modified_time" content="2017-04-10T20:10:02+00:00">
<meta property="article:expiration_time" content="2018-04-10T19:50:02+00:00">
<meta property="article:author" content="Anonymous">
<meta property="article:section" content="Frontpage">
<meta property="article:tag" content="myTag">
```

Resulting in:
````
Array
(
    [type] => article
)
````
and
````
Array
(
    [og:type] => article
    [article:published_time] => 2017-04-10T19:50:02+00:00
    [article:modified_time] => 2017-04-10T20:10:02+00:00
    [article:expiration_time] => 2018-04-10T19:50:02+00:00
    [article:author] => Anonymous
    [article:section] => Frontpage
    [article:tag] => myTag
)
````

**These prefixes is unavailable in the Open Graph provider:**
- `music:` - http://ogp.me/ns/music#
- `video:` - http://ogp.me/ns/video#
- `article:` - http://ogp.me/ns/article#
- `book:` - http://ogp.me/ns/book#
- `profile:` - http://ogp.me/ns/profile#

Fetching them from the `html` provider works like a charm, but I don't understand why there is an native Open Graph provider, when 5 of 6 namespaces are unavailable, and additionally `og:type` is modified to comply with generic non-`og` guidelines.

The provider looks more like an converter/translator class for internal usage by emed only, than a native provider to fetch perfectly valid data from...

**Comment by oscarotero** [comment]
mmm. You're right. I thought all opengraph values were prefixed with `og:` but it seems incorrect. The opengraph provider should collect these prefixes too.
