### ISSUE TITLE
Suggestion: Switch to composer/ca-bundle

### ISSUE THREAD

**Issue by JanPetterMG** [oscarotero/Embed#207]
How about switching to `composer/ca-bundle`?
Then we don't need to include an certficate that sometimes may get outdated/updated, and there is no need to release a new version, just for updated certficates either. btw.
https://github.com/composer/ca-bundle

```php
$system = CaBundle::getSystemCaRootBundlePath();
$bundled = CaBundle::getBundledCaBundlePath();
```

**Comment by oscarotero** [comment]
It's great, I didn't know it.
Thanks for the info 👍
