### ISSUE TITLE
Malformed URL: http://:0

### ISSUE THREAD

**Issue by JanPetterMG** [oscarotero/Embed#208]
Not sure what's the problem is, or how to fix it, but as I see it, this is something that should be handled internally. If an empty canonical url is discovered (or whatever it's origin is), don't follow it, especially if it throws exceptions.

`Fatal error: Uncaught InvalidArgumentException: Malformed URL: http://:0 in /var/www/oscarotero.com/www/embed3/src/Http/Url.php:643 Stack trace: #0 /var/www/oscarotero.com/www/embed3/src/Http/Url.php(507): Embed\Http\Url::parse('http://:0') #1 /var/www/oscarotero.com/www/embed3/src/Http/Url.php(33): Embed\Http\Url->parseUrl('http://:0') #2 /var/www/oscarotero.com/www/embed3/src/Http/Url.php(23): Embed\Http\Url->__construct('http://:0') #3 /var/www/oscarotero.com/www/embed3/src/Http/Url.php(115): Embed\Http\Url::create('http://:0') #4 /var/www/oscarotero.com/www/embed3/src/Providers/Html.php(336): Embed\Http\Url->createAbsolute('//:0') #5 /var/www/oscarotero.com/www/embed3/src/Providers/Html.php(29): Embed\Providers\Html->extractImages(Object(DOMDocument)) #6 /var/www/oscarotero.com/www/embed3/src/Adapters/Webpage.php(23): Embed\Providers\Html->__construct(Object(Embed\Adapters\Webpage)) #7 /var/www/oscarotero.com/www/embed3/src/Adapters/Adapter.php(72): Embed\Adapters\Webpage->init() #8 /var/www/oscarotero.com/www/embed3/ in /var/www/oscarotero.com/www/embed3/src/Http/Url.php on line 643`

Example:
https://oscarotero.com/embed3/demo/index.php?url=http%3A%2F%2Fwww.expressen.se%2Fkvallsposten%2Fsport%2Fstjarnan-uppges-klar-for-ny-klubb--mitt-under-slutspelet%2F

If you need more URLs, just ask, I have thousands of them. They're all giving me the exact same error...

**Comment by oscarotero** [comment]
Ok, this is because some images have malformed urls and throws exceptions on create a new Uri instance with them. I've fixed using a try/catch.
Thanks for reporting this.
