### ISSUE TITLE
Provider for Linkpulse (lp)

### ISSUE THREAD

**Issue by JanPetterMG** [oscarotero/Embed#209]
I've found a meta tag property prefix that isn't supported natively yet; `lp` by Linkpulse.
It's basically an duplicate of the OpenGraph protocol, but with `lp:` and `lp.` prefixes only.

Official list of fields at the bottom of the page: http://docs.linkpulse.com/docs/opengraph/

It's worth adding that a large number of webpages also uses two more fields; `lp:premium` (boolean - paywall/subs only) and `lp:section` (as an alternative to `lp.article:section`).

Example:
```html
 <meta property="lp:title" content="Add more power to Linkpulse with metadata" />
 <meta property="lp:type" content="article" />
 <meta property="lp:url" content="http://www.linkpulse.com/docs/opengraph/" />
 <meta property="lp:image" content="http://www.linkpulse.com/gfx/linkpulse-180-white.png" />
 <meta property="lp:description" content="We believe in power of metadata as part of the analysis of the realtime trafic data." />
 <meta property="lp.article:author" content="Nils Dahl"/>
 <meta property="lp.article:published_time" content="2012-08-10T09:29:00"/>
 <meta property="lp.article:modified_time" content="2012-08-12T14:48:00"/>
 <meta property="lp.article:section" content="documentation"/>
 <meta property="lp:channel" content="web"/>
```

EDIT: The property tags are widely used, and are often used as a supplement, or replacement for the Open Graph protocol.

**Comment by oscarotero** [comment]
I've added this provider. Can you give me an url using this meta tag for testing?
Thanks

**Comment by JanPetterMG** [comment]
Thanks, it works!

Some random URLs, not so many `lp` properties used here, but it's something...
http://www.tv2.no/a/9151440
https://www.svd.se/starten-i-americas-cup-uppskjuten
http://www.aftonbladet.se/ledare/a/Jm8m6/rubriker-vi-verkligen-skulle-vilja-se
http://www.vg.no/rampelys/film/norsk-film-griseslaktes-i-amerikansk-storavis/a/24006708/
http://www.nettavisen.no/sport/graf-overtalte-agassi-til-a-trene-djokovic/3423343787.html
http://www.dagbladet.no/kjendis/folelsene-var-helt-jaevlige-jeg-ville-skrike-og-hyle/67629653
