### ISSUE TITLE
GetVideoUrl is missing

### ISSUE THREAD

**Issue by shtse8** [oscarotero/Embed#210]
I need to get the video url, but this method is missing.
Now I only can `getCode` and match the url inside.

**Comment by oscarotero** [comment]
Yes, this value is not provided so this is the way to get it.

**Comment by shtse8** [comment]
because the code returned now is fixed size.
it is not friendly for mobile and i have to change it to responsive html as iframely.com did, so i need to get back the video url and make the html myself. please support getVideoUrl method. thanks.

**Comment by oscarotero** [comment]
There's a better way to make videos and iframes responsive. See #3 and #65

**Comment by shtse8** [comment]
@oscarotero yes, this is the way i am doing. but i need to get the video url. but parsing the code returned is quick hack.
