### ISSUE TITLE
Custom Adapters

### ISSUE THREAD

**Issue by brianlmoon** [oscarotero/Embed#211]
In 2.x the package allowed for custom adapters in the configuration. This was required for parsing static HTML files on disk that had no headers. Was this removed on purpose or was it an oversight?

**Comment by oscarotero** [comment]
This feature was removed to simplify the options. But this could be done creating a response directly from the html file. Example (I've not tested the code):

```php
use Embed\Http\Response;
use Embed\Http\Url;
use Embed\Http\CurlDispatcher;

$url = Url::create('http://example.com');
$content = file_get_contents('example.com/index.html');
$response = new Response($url, $url, 200, 'text/html', $content, []);

$info = new CustomAdapter($response, [], new CurlDispatcher());
```
