### ISSUE TITLE
Allow special chars in extension

### ISSUE THREAD

**Issue by nicolas-t** [oscarotero/Embed#212]
An error is thrown when using this url : 
`https://pbs.twimg.com/media/CvCZ90BXYAE5q80.png:large`

because of `:large` being encoded as `%3Alarge`  

demo here :  
https://oscarotero.com/embed3/demo/index.php?url=https%3A%2F%2Fpbs.twimg.com%2Fmedia%2FCvCZ90BXYAE5q80.png%253Alarge

Do you think I have to strip the :foo on my side or do you think it's Embed related ? 

Thanks

**Comment by oscarotero** [comment]
Maybe it's Embed related, because the url is automatically encoded. I've fixed it not encoding this character, due it's used widely in other sites.

**Comment by nicolas-t** [comment]
Thanks, 

When will you release it ?

**Comment by oscarotero** [comment]
Sorry, I'm a bit busy right now, but I'm release it today, within a few hours.

**Comment by oscarotero** [comment]
v3.0.8 released.
