### ISSUE TITLE
Can't get correct response (InvalidUrlException)

### ISSUE THREAD

**Issue by wineua** [oscarotero/Embed#214]
Could you please take a look at this URL: https://oscarotero.com/embed3/demo/index.php?url=http%3A%2F%2Fimg.bibo.kz%2F%3F7142389.jpg

Seems like http_build_query function adds excess "="  equal sign to the end of url 
at Http/Url.php on line 491

**Comment by oscarotero** [comment]
Fixed. Thanks for reporting.
