### ISSUE TITLE
Call to undefined function Embed\Http\finfo_open()

### ISSUE THREAD

**Issue by banan4** [oscarotero/Embed#216]
Hello,

I'm running php 5.6.30 and getting this error:

[type] => 1
    [message] => Call to undefined function Embed\Http\finfo_open()
    [file] => /home/bzl/public_html/resources/Embed/src/Http/CurlDispatcher.php
    [line] => 162

php.ini has no mention of fileinfo.so, but phpinfo(); shows 

--enable-fileinfo=shared

any idea what might be causing this please? Pardon me if this is not the correct place to be posting this.

On a side note, might [this](http://php.net/manual/en/function.finfo-open.php#112617) be a more efficient algorithm? Admittedly, bmp/icon are left out, but...

**Comment by oscarotero** [comment]
I don't know, but seems that you don't have fileinfo enabled (https://help.dreamhost.com/hc/en-us/articles/214205858-How-do-I-enable-fileinfo-)
And about the algorithm, I'm not sure whether is more eficient an userland php code than a lib extension written in C but icon/bmp support is a must. In fact the first version of Embed used a similar approach than your suggestion (based in fastimage: https://github.com/tommoor/fastimage) but it caused serveral problems.

**Comment by banan4** [comment]
You are correct, it was in fact not installed correctly. Thank you very much for your assistance.

**Comment by tienvx** [comment]
I have php 7.1 and get the same error. Installing php7-fileinfo extension fixed the problem.
