### ISSUE TITLE
Notice: Undefined variable: href in Providers/Html.php on line 363

### ISSUE THREAD

**Issue by JanPetterMG** [oscarotero/Embed#218]
`
Fatal error: Uncaught TypeError: Argument 1 passed to Embed\Providers\Html::imageIsValid() must be an instance of Embed\Http\Url, null given, called in /var/www/oscarotero.com/www/embed3/src/Providers/Html.php on line 363 and defined in /var/www/oscarotero.com/www/embed3/src/Providers/Html.php:392 Stack trace: #0 /var/www/oscarotero.com/www/embed3/src/Providers/Html.php(363): Embed\Providers\Html::imageIsValid(NULL, Object(Embed\Http\Url), false) #1 /var/www/oscarotero.com/www/embed3/src/Providers/Html.php(29): Embed\Providers\Html->extractImages(Object(DOMDocument)) #2 /var/www/oscarotero.com/www/embed3/src/Adapters/Webpage.php(23): Embed\Providers\Html->__construct(Object(Embed\Adapters\Webpage)) #3 /var/www/oscarotero.com/www/embed3/src/Adapters/Adapter.php(72): Embed\Adapters\Webpage->init() #4 /var/www/oscarotero.com/www/embed3/src/Embed.php(75): Embed\Adapters\Adapter->__construct(Object(Embed\Http\Response), Array, Object(Embed\Http\CurlDispatcher)) #5 /var/www/oscarotero.com/www/embed3/src/Embed.php(31): Embed\Emb in /var/www/oscarotero.com/www/embed3/src/Providers/Html.php on line 392
`

Demo: https://oscarotero.com/embed3/demo/index.php?url=https%253A%252F%252Fwww.theguardian.com%252Fglobal-development-professionals-network%252F2017%252Fmay%252F26%252Frural-water-access-paraguay-success-lessons

**Comment by JanPetterMG** [comment]
It's impossible to catch this exception on php 5.6. The only way is thru an error handler...
http://php.net/manual/en/language.exceptions.php#118280

**Comment by oscarotero** [comment]
Ok, it's due a missing `continue` here. Fixed:
https://oscarotero.com/embed3/demo/index.php?url=https%3A%2F%2Fwww.theguardian.com%2Fglobal-development-professionals-network%2F2017%2Fmay%2F26%2Frural-water-access-paraguay-success-lessons

**Comment by JanPetterMG** [comment]
Thanks! that was fast :+1:
