### ISSUE TITLE
Stop following canonical urls on certain conditions

### ISSUE THREAD

**Issue by JanPetterMG** [oscarotero/Embed#219]
Is there some clever way to stop following canonical URLs on certain conditions?

I see lots of different webpages pointing Embed to the front page, when I've actually requested some other page (that also exists). This happens all the time, and most of the time, it puts Facebook as referrer in the url. This isn't Embed's fault, as it's often some canonical-like meta-tag somewhere pointing to that specific URL.

**Example:** [http://glomdalen.no/**skarnes**](http://glomdalen.no/skarnes)
**Redirects to:** [**https://www**.glomdalen.no/**skarnes**](https://www.glomdalen.no/skarnes)
**While `og:url` points to:** [**http://www.glomdalen.no**?ns_campaign=frontpage&amp;ns_mchannel=recommend_button&amp;ns_source=facebook&amp;ns_linkname=facebook&amp;ns_fee=0](http://www.glomdalen.no?ns_campaign=frontpage&amp;ns_mchannel=recommend_button&amp;ns_source=facebook&amp;ns_linkname=facebook&amp;ns_fee=0)
Witch becomes the final URL according to Embed (a different page).
Visiting that in a browser, causes redirection to HTTPS (once again)

How about not following so-called `canonical` urls if it contains `campaign` or `source` parameters? We'll already received a HTTP 200 right, so why bother adding that referrer, witch _may or may not_ point us to a potentially different and unwanted page...

Parameter blacklist suggestion:
- `ns_campaign`
- `ns_source`
- `utm_campaign`
- `utm_medium`
- `utm_source`

_Offtopic: Dealing with the webpages, requesting them to fix it isn't the right way to go either, it's too many of them, and often, this is how they track facebook clicks..._

EDIT: typo + bold text

**Comment by oscarotero** [comment]
Yes, we might have a `canonical_blacklist` option, in the same way that we have a `images_blacklist`.

Do you mind to work in a pull request (I'm a bit bussy now). It could be something like this: https://github.com/oscarotero/Embed/blob/master/src/Adapters/Adapter.php#L415 but in  [getUrl()](https://github.com/oscarotero/Embed/blob/master/src/Adapters/Adapter.php#L302)

**Comment by JanPetterMG** [comment]
Thanks, I'll look into that, and submitting an PR when possible.

**Comment by JanPetterMG** [comment]
There's no default `$config` :disappointed:
So if anyone wants to avoid this issue, they have to create their own custom blacklist? with common strings?

I was about to create a constant array, but that's PHP 5.6+ only (Embed targeting 5.5+), and since `$embed->create()` is static, it isn't possible to use properties either...

The only thing I can think of now, is creating the default config as one of the default parameters in `$embed->create($url, $config)`, but then we cannot append anything, only replace it with a new custom array...
Any suggestions?

**Comment by oscarotero** [comment]
We can create a static property to store the default config, that will be used if `$config` is `null`. For example:

```php
$info = Embed::create($url, []); //empty config
$info = Embed::create($url, null); //use the default config

$config = Embed::$default_config; //Get the default config
$config['url_blacklist'][] = '*.example.com/*'; //Add new urls to blacklist

$info = Embed::create($url, $config); //Use the new configuration
```

**Comment by JanPetterMG** [comment]
Ahh, obviously, I didn't think of that, Thanks!
I'm almost never working on anything static, hehe
