### ISSUE TITLE
Images not fetched in response

### ISSUE THREAD

**Issue by Purus** [oscarotero/Embed#222]
I am using the below code to get the video details and it works fine.

```
    $info = Embed\Embed::create("https://www.youtube.com/watch?v=DpUoWjIxxZs"); 
    $result = array();

    $result['title'] = $info->title;
    $result['desciption'] = $info->description;
    $result['type'] = $info->type;
    $result['tags'] = $info->tags;
    $result['provider'] = $info->providerName;
```

But the below line to fetch the images, does not work.

`    $result['images'] = $info->images;`

OpenGraph provider has this data and not oembed. How can I get the openGraph bag details? The code below does not help.

```
$providers = $info->getProviders();
$oembed = $providers['oembed'];
echo $oembed->bag->get('photos');
```

**Comment by oscarotero** [comment]
What do you mean with "does not work"? I've tested this urls and works fine: https://oscarotero.com/embed3/demo/index.php?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DDpUoWjIxxZs returning the images too.

Anyway, you have all providers in the array returned by `$info->getProviders()`. For example `$providers['opengraph']`.

**Comment by Purus** [comment]
When I access image , i get server 500 error. I am not sure as this is
strange.

**Comment by Purus** [comment]
Seems to work in different network.
