### ISSUE TITLE
New provider: "article-info" meta tag

### ISSUE THREAD

**Issue by JanPetterMG** [oscarotero/Embed#225]
Feature request!

Currently this meta tag does not show up in the `html` provider bag, it's simply ignored. To fetch it, you'll have to use Xpath.

As you can see, it has a lot of useful data in it:
```html
<meta name="article-info"
      data-id="bt335907b"
      data-numeric-id="335907"
       data-short-id="QV7oA"
      data-type="standard"
      data-published="1497948056000"
      data-modified="1497954373000"
      data-section-id="nyheter:lokalt"
      data-section-unique-name="nyheter:lokalt"
      data-section-name="nyheter &gt; lokalt"
      data-engage-group=""
      data-tags="Lindås|Statens vegvesen|Meland|Haukeland universitetssykehus|Danmark|Etterforskning|Litlebergen|Nissan"
      data-paywall-state="closed"
      data-paywall-type="subscription"
>
```

It's on my to-do list, but don't expect it anytime soon. If anyone wants to help, I really appreciate it!

**Comment by JanPetterMG** [comment]
@oscarotero I'm wondering if you have any thoughts about how to return timestamps.

As you can see, timestamp is in UNIX epoch microsecond format. This is as good as it gets, but not for direct presentation purposes?
If `Adapter->getFirstFromProviders()` gets called, you'll never know what's returned...

- As is, Unix epoch microsecond integer
- Unix epoch float|integer?
- Conversion to a standardized time format, witch?
- User-specified format? (if it's a string already, just throw it at the end-user)
- Add a property for specifying what it is.

If the provider ever gets submitted, depends on your decision. Cheers!

**Comment by oscarotero** [comment]
Currently, there's no conversion, the data is returned as-is. Most data formats is ISO8601 (at least opengraph), but the user always can create a `Datetime` instance with that and convert to the desired format. Timestamp does not work like that (not sure but `new Datetime(1497948056000)` is not valid), so in this case I'd convert to ISO8601.
