### ISSUE TITLE
Facebook event can't get data

### ISSUE THREAD

**Issue by tiger154** [oscarotero/Embed#227]
Hi there I tried to get some public event data. 
but it return just title not image. 'https://www.facebook.com/events/1822069678114212/'

When I try to crawl that link. I can't  get proper event data... such as main image. I can get only title.. Do I need some special permission? even thought this is a public event?? 

I also checked on your demo page : https://oscarotero.com/embed3/demo/index.php?url=https%3A%2F%2Fwww.facebook.com%2Fevents%2F1822069678114212%2F

but I can't get images, descriptions.. 

Here is my code
```
$config = [
                'adapter' => [
                    'config' => [
                        'minImageWidth' => 50,
                        'minImageHeight' => 50,
                    ]
                ],
                'providers' => [
                    'html' => [
                        'maxImages' => 3
                    ],
                    'facebook' => [
                        'key' => "XXXXXXXXX"
                    ]
                ],
                'resolver' => [
                    'config' => [
                        CURLOPT_CONNECTTIMEOUT => 5,
                        CURLOPT_TIMEOUT => 5,
                        CURLOPT_USERAGENT => 'My Crawler',
                        CURLOPT_MAXREDIRS => 3
                    ]
                ]
            ];
 $result = Embed::create($url, $config);

```

**Comment by raymondelferink** [comment]
Try adding this to your options struct:

'html' => [
       'max_images' => 10,
       'external_images' => true
]

**Comment by oscarotero** [comment]
AFAIK, Facebook has not a way to embed events directly, just posts, photos, etc.
For example, it works with a event post: https://oscarotero.com/embed3/demo/index.php?url=https%3A%2F%2Fwww.facebook.com%2Fevents%2F1822069678114212%2Fpermalink%2F1843444875976692%2F%3Faction_history%3Dnull

**Comment by tiger154** [comment]
Thank you @oscarotero  then I was thinking other way around like using 'https://graph.facebook.com' . 
If I make a request with curl actually I can get proper data. 

Do you have any idea to adapt this in this cool framework? :)  
I mean I could get with this ugly code but I'd like to use within this cool framework!! 
```
       $facebook_event_id = '1822069678114212';
        $facebook_key = 'XXXXXXXXX';
        $fields = 'description,timezone,start_time,end_time,name,owner,privacy,id,cover';
        $ch = curl_init();
        curl_setopt($ch, CURLOPT_URL, 'https://graph.facebook.com/'.$facebook_id.'?access_token='.$facebook_key.'&fields='.$fields);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
        $r = curl_exec($ch);

```

**Comment by oscarotero** [comment]
If you can archieve this, please share the code (creating a gist, for example) and I'll try to adapt to embed.
thanks.

**Comment by tiger154** [comment]
Hi @oscarotero I made a sample code so please let me know if it's enough  :) 

  - https://gist.github.com/tiger154/171fb3aa2cb02ff99ec1a58548d81990 

* I used 'Embed\Http' to parse url 
* From line 38 that's just a sample result so you can just comment or delete. 
* sample result through this gist file

```
object(stdClass)[44]
  public 'description' => string 'BACKDOOR TEADANCE becomes BAƆKDOOR®
Same partyconcept | Same location | Only better 

Music by DJ's: MARTIN RIVERA (Funhouse) - SOFIA VALENTINE (Flikker) - STENNIS (NYX) 
Entertainment by Mermaids EnvyPeru (Miss Fish 2017) & Ivy-Elyse Monroe (Miss SuperBall 2017) and their Hot Hot GoGo Boys!
Your host: Moustache lady SNORELLA WC.

Join us for our next BAƆKDOOR® on Saturday July 22 at AKHNATON, Amsterdam when we will team up with the legendary Amsterdam club night FLIKKER. This is going to be amazing! Th'... (length=1587)
  public 'timezone' => string 'Europe/Amsterdam' (length=16)
  public 'start_time' => string '2017-07-22T23:00:00+0200' (length=24)
  public 'end_time' => string '2017-07-23T05:00:00+0200' (length=24)
  public 'name' => string 'BACKDOOR meets FLIKKER at AKHNATON Amsterdam' (length=44)
  public 'owner' => 
    object(stdClass)[45]
      public 'name' => string 'Backdoor Amsterdam' (length=18)
      public 'category' => string 'Dance & Night Club' (length=18)
      public 'category_list' => 
        array (size=1)
          0 => 
            object(stdClass)[46]
              ...
      public 'id' => string '739754256107669' (length=15)
  public 'privacy' => string 'OPEN' (length=4)
  public 'id' => string '1822069678114212' (length=16)
  public 'cover' => 
    object(stdClass)[47]
      public 'cover_id' => string '10210345374085330' (length=17)
      public 'offset_x' => int 0
      public 'offset_y' => int 50
      public 'source' => string 'https://scontent.xx.fbcdn.net/v/t1.0-9/18835618_10210345374085330_4023483479399596616_n.jpg?oh=e791af0aa863cf6fc8f0507320381720&oe=59C78E33' (length=139)
      public 'id' => string '10210345374085330' (length=17)

```

**Comment by oscarotero** [comment]
Ok, I had [something similar](https://github.com/oscarotero/Embed/blob/6566587b319d27d102665f5e0d01fb7c811d6f1c/src/Providers/Api/Facebook.php) before facebook released the oembed api, then it was deleted, so I've recovered again and adapted for events only.

**Comment by tiger154** [comment]
Cool!!! Thank you so much code looks perfect!!! I will pull all :)

**Comment by tiger154** [comment]
Hey @oscarotero ,

Thanks for your job!!! I have some questions.

1) When are you gonna release with this update? 
   - If you can do I can just update my composer! so If you have plan please let me know when it would be! 

2) If it's not I need to extend myself but I don't want to touch inside 'vendor/~~' as that is not good approach. So is there any way to extend  outside of 'vendor' directory properly? 

Thank you !!!

**Comment by oscarotero** [comment]
I need to fix the travis errors before create a new release. If you need it now, you can install the `dev-master` instead a stable version.

**Comment by tiger154** [comment]
Ah alright! Thank you so much! :)
