### ISSUE TITLE
Linkedin thows an error

### ISSUE THREAD

**Issue by raymondelferink** [oscarotero/Embed#229]
Is there any way to make Embed work for LinkedIn? If you put in a link to a linkedin profile Embed throws an fatal error. 

See: https://oscarotero.com/embed3/demo/index.php?url=https%3A%2F%2Fwww.linkedin.com%2Fin%2Fraymondelferink%2F

In the bottom of the page it says: 
Fatal error: Uncaught Embed\Exceptions\InvalidUrlException: Invalid url 'https://www.linkedin.com/in/raymondelferink/' (Status code 999) in /var/www/oscarotero.com/www/embed3/src/Embed.php:79 Stack trace: #0 /var/www/oscarotero.com/www/embed3/src/Embed.php(31): Embed\Embed::process(Object(Embed\Http\Url), Array, Object(Embed\Http\CurlDispatcher)) #1 /var/www/oscarotero.com/www/embed3/demo/index.php(226): Embed\Embed::create(Object(Embed\Http\Url), Array, Object(Embed\Http\CurlDispatcher)) #2 {main} thrown in /var/www/oscarotero.com/www/embed3/src/Embed.php on line 79

and the resulting $info is empty.

First I thought it was due to Linkedin not allowing anonymous access, but then I saw that Embedly's Extract endpoint does return content for the same profile:
http://embed.ly/docs/explore/extract?url=https%3A%2F%2Fwww.linkedin.com%2Fin%2Fraymondelferink%2F

Any ideas?

Cheers, Raymond

**Comment by oscarotero** [comment]
I think it depends of the server from the request is sent. For example, in localhost works fine.

**Comment by lchhieu** [comment]
same error
