### ISSUE TITLE
Option to stop following canonicals to / on specific conditions

### ISSUE THREAD

**Issue by JanPetterMG** [oscarotero/Embed#232]
Once again I've stumbled upon some tricky webpages... This time, it's just a few ones, but some of them are too large/important to be ignored...

For example:
http://itavisen.no/tag/netflix/
Redirects to the front-page, because of:
`<meta property="og:url" content="http://itavisen.no"/>`

- New configuration option named `ignore_root_canonicals` (bool). _Feel free to suggest a better name._
- Ignores redirects to the front page, specifically `/`.
  - `HTTP 200` only. _An `HTTP 404` with redirect to the front-page is still better than the nothing._
  - Within the current host only. _`http://12.34.56.78/` to `https://example.com/` __shall not__ be denied._
  - Except when we're on the front-page already. _`/?foo=bar` to `/` __should not__ be denied._

_Not sure where to put this, as I haven't found the place canonical urls are turned into redirects yet..._
Anyway, what do you think?

**Comment by oscarotero** [comment]
The conditions to following the canonical url can be improved here: https://github.com/oscarotero/Embed/blob/master/src/Embed.php#L73
But I don't want to complicate this with options. If some sites returns wrong results, it's better to create adapters than create more settings with a hard to explain behaviour. In my opinion:

* Try to improve the canonical url following with generical conditions that can be applied in all cases
* For specific cases, create adapters to fix the values.

Maybe a good option could be allow to register custom adapters under a namespace. For example:

```php
$info = Embed::create($url, [
    'custom_adapters_namespace' => 'MyApp\\EmbedProviders\\'
]);
```

So, to fix `http://itavisen.no`, you can create an adapter in `MyApp\\EmbedProviders\\Itavisen`.

**Comment by JanPetterMG** [comment]
ok, I'll create a couple of page-specific adapters for now.
I'll also do some more research, because if it's more than a just a handful number of webpages, this needs to be fixed, one way or another...

**Comment by JanPetterMG** [comment]
Well, it's more pages than I've expected, so an fix is definitively needed...
