### ISSUE TITLE
Use Semantic Versioning

### ISSUE THREAD

**Issue by stephanvierkant** [oscarotero/Embed#233]
I just saw that version 3.0.9 contains fixes, improvements and new features. Thanks!

Based on the version number I thought it was just a patch release, but this clearly isn't. Why not use [Semantic Versioning](http://semver.org/) for this library?

I think the latest versions should have called 3.1 instead.

**Comment by oscarotero** [comment]
Yes, you're right. I try to follow the semver specification in my projects, but this release was not tagged correctly. Now it's fixed. Thanks
