### ISSUE TITLE
Multiple adapter namespaces

### ISSUE THREAD

**Issue by JanPetterMG** [oscarotero/Embed#237]
Make it possible to have multiple adapter NS.

It's too bad if you'll have to choose between one library or another, or even your own custom adapters.
As always, it's all about the order.

**Comment by JanPetterMG** [comment]
Alternative approach, probably better in the end: **Registry** config array

Then we'll able to prioritize adapters over each other, namespace independent, and if you don't need an adapter, don't use it. No need to request unnecessary data. This resolves every part of #220

Reply to https://github.com/oscarotero/Embed/issues/232#issuecomment-313955380 - That's unrealistic, as we might end up with 100+ classes just to disable an canonical meta tag. _(I'm counting 23 domains as we speak)_. The current system is definitively broken, and a FIX IS NEEDED!

Therefore I'm suggesting:
```php
$config['registry'] = [
    'adapters' => [
        'Canonical' => '\\Custom\\Namespace\\Canonical',
        'Github' => '\\Embed\\Adapters\\Github',
        'Wikipedia' => '\\Embed\\Adapters\\Wikipedia',
        'YouTube' => '\\Embed\\Adapters\\YouTube',
    ],
    'providers' => [
        'oembed' => 'Embed\\Providers\\OEmbed',
        'opengraph' => 'Embed\\Providers\\OpenGraph',
    ],
    'hosts' => [
        'canonical-issue.example.com' => 'Canonical',
        'canonical-issue.domain.net' => 'Canonical',
    ],
];
```
------------------------------------------------------------------
Another issue with the current approach, is that it falls back to Embeds own adapters in case no custom adapter is found, because of that, every unwanted adapter has to be replaced by an empty one, just to be able to throw out an provider. Why make it so hard?
Those capable of setting up custom adapters, are also capable of re-adding Embeds own adapters!

Reply to https://github.com/oscarotero/Embed/issues/235#issuecomment-314518327 - In case of missing providers _(fatal error)_, don't do anything about it, let the user remove the adapters using it, or adding back in the missing providers.

**Comment by oscarotero** [comment]
Currently, there's a condition in opengraph provider to avoid canonical urls pointing to the home page. You can see it here https://github.com/oscarotero/Embed/blob/master/src/Providers/OpenGraph.php#L159 
I guess moving this to the adapter, to apply the condition to all providers should fix your issue. (I mean move to here: https://github.com/oscarotero/Embed/blob/master/src/Adapters/Adapter.php#L304)

I don't get the `registry` config. The providers are instantiated by the adapters and each adapter has its own providers. I don't know why you want to move all this logic to a long configuration array. Some adapters could use opengraph as its first provider, others might have better results with twitter cards. Configuring the providers globally, for all adapters makes no sense to me.

**Comment by oscarotero** [comment]
Heres's the issue I tried to fix (similar to yours) https://github.com/oscarotero/Embed/issues/160 But it was fixed only in opengraph, should be applied to all providers.

**Comment by JanPetterMG** [comment]
Then the canonical issue is no longer a problem. But there is still a few issues left:

1. How do you plan to disable adapters and providers you don't want/need anyway? #220

2. Some adapters may prefer data from one provider over another, but in case no page-specific adapter is used, how to control what provider the data is returned from? #220 Implement `getFirstFromProviders` in a library on top of Embed? Throw out the whole `Adapter` class witch the whole library depends on??

3. I'm going to create replacement classes for a few providers, nothing will change except some return values. How do I get the adapters to use the replacement class instead of the underlying class that just was extended/replaced?

How about an registry-like class instead, where Embed asks for classes needed? The code is already there, you just need to put it in an separate class, and build an interface for it, requiring functions like `domain`, `provider` and `adapter`.
Yes you don't really need `provider` at all, but you'll also eliminates a lot of flexibility then. That's all.

> If this doesn't get resolved somehow soon, I'll fork this project, fix a few return values, build 3 more providers as well as methods/properties for easy access to even more data. Then I don't even need support for external adapters at all. Just saying.

**Comment by oscarotero** [comment]
1. Why do you want to disable adapters? The purpose of the adapters is fix the wrong results that the default adapter (Webpage) returns. In an ideal world, just one adapter was needed. Do you want the library returns bad results for any purpose? Anyway, if you don't like how `Embed::create($url)` works, consider create a custom factory class: `CustomEmbed::create($url)`.

2. (and 3) Just create your own Webpage class:
```php
namespace MyOwnAdapters;

use Embed\Adapter\Adapter;

class Webpage extends Adapter
{
    protected function init()
    {
        $this->providers = [
            //move linkpulse to first, because it's my preferred provider
            'linkpulse' => new Providers\Linkpulse($this),

            // disable Oembed
            // 'oembed' => new Providers\OEmbed($this),
            'opengraph' => new Providers\OpenGraph($this),
            'twittercards' => new Providers\TwitterCards($this),
            'dcterms' => new Providers\Dcterms($this),
            'sailthru' => new Providers\Sailthru($this),

            //use a custom provider
            'html' => new CustomHtml($this),
        ];
    }
}

$info = Embed::create($url, [
    'custom_adapters_namespace' => 'MyOwnAdapters\\'
]);
```

> If this doesn't get resolved somehow soon, I'll fork this project, fix a few return values, build 3 more providers as well as methods/properties for easy access to even more data. Then I don't even need support for external adapters at all. Just saying.

You're free to fork and create a new version of this project. The license allows that. This is a project maintained in my free time that it's very limited.

**Comment by JanPetterMG** [comment]
2 and 3: Even if i'll do that, every existing adapter that isn't replaced extends `Embed\Adapters\Webpage`, witch then uses the unwanted `Webpage` class.
Additionally, adapters like ex. `File` doesn't care, it's using the existing `Oembed` class, even if it isn't supposed to do so...

1. There is multiple reasons for it. I have a bot crawling the web, Most of the time I want everything possible, but sometimes the main goal is just discovery, (icons, feeds, custom xpath queries).
Additionally, I don't ever use Facebook, Flickr, Github, Google, +++.

I don't really want to fork this project, as it means more job to maintain, but it also means less fixes, adapters, and providers upstream.
