### ISSUE TITLE
min image width/height ignored + external image bug

### ISSUE THREAD

**Issue by JanPetterMG** [oscarotero/Embed#239]
```php
            $embed = Embed\Embed::create($url, [
                'min_image_width' => 500,
                'min_image_height' => 500,
            ]);
            var_export($embed->images);
```

Why do I get all available images, regardless of size?

_Sorry for asking, but Am I doing something wrong (again), or is this (another) bug?_

**Comment by JanPetterMG** [comment]
I'd also get images for external domains, even when `external_images` was set to `false`.
Eg. requesting `example.de` returned a few images from `example.fr`.
_I really hope the logic is well designed..._

**Comment by oscarotero** [comment]
`min_image_width` and `min_image_height` is used to choose the main image (`$info->image`), but does not affect to the list of all images (`$info->images`).

And about the `external_images`, it's an option of the html provider used to scan the `<img>` elements in the html (it's `false` to do not get unrelated images like banners or social networks logos). It must be configured in the html subarray:

```php
$options = [
    'min_image_width' => 500,
    'min_image_height' => 500,
    'html' => [
        'external_images' => true
    ]
];
```

**Comment by JanPetterMG** [comment]
Okay, I'd just think it's a bit strange if there is parameters for min height/width, and that those are ignored when requesting multiple images...

In this case I wanted multiple sizes, but minimum `500px` w/h, so that I can cache them and choose what image to present to the user depending on the `media` (screen) size. I've got 3 images matching the criteria, and another 40 with sizes mostly under `70px`.
It's easy to check the size in a foreach loop, but so is it if you'll only want the first big image, as well as the biggest.
The point is that I don't see a valid reason to have those config options, if they're only used in a single function. You could simply do this instead: `$embed->getImage(500, 500);`, witch also is more flexible...

------------------------------------------------
```php
$options = [
    'html' => [
        'external_images' => false,
    ]
];
```
This config is default, as well as the config I've used when I've got images from a different domain, from the HTML provider!
I don't have the original testing url where about 5 of 20 images was from different domains, but you can try this instead:

```php
var_export(
    \Embed\Embed::create('https://www.dolce-gusto.no/kaffekapsler/catuai-do-brasil', [
        'html' => [
            'external_images' => false,
        ]
    ])
        ->getProviders()['html']->getImagesUrls()
);
```
Currently at least one of them is from `dolce-gusto.dk`, while the page is located at `dolce-gusto.no`.
Could you please explain this?

**Comment by oscarotero** [comment]
`external_images` does not affect to first level domains (.com, .no, .dk, etc). So dolce-gusto.no can use images from dolce-gusto.dk, because (in theory) it's the same site but in different languages.

**Comment by JanPetterMG** [comment]
You should really consider adding support for `min_image_width` and `min_image_height` in `\Embed\Adapters\Adapter->getImages()`

**Comment by oscarotero** [comment]
Thanks for the suggestion but Embed never had a functional api, just properties to return the final value. Adding functions with arguments to get the values increments the complexity of the library.
You can use `array_filter` for this purpose.

**Comment by JanPetterMG** [comment]
I'm aware of that :) but those properties doesn't fill out them self, do they? Sorry if I referred to the wrong magic function.
Have a nice day.

**Comment by oscarotero** [comment]
The purpose of magic function is lazy load the values because most people just want a couple of values (like embed code and title). Some operations like get all images sizes are expensive, and can be executed multiple times, so it's better to get and cache the value.

For example, `$info->image` uses internally `$info->images`. This code:

```php
$mainImage = $info->getImage();
$allImages = $info->getImages();
```
executes `$info->getImages()` twice. But in the followin example

```php
$mainImage = $info->image;
$allImages = $info->images;
```

it's execute once, because the result is cached in the first execution. Of course, you're free to use the methods directly, but this is not the purpose what they are created for. In fact, they should be declared as protected, to avoid its usage from external.
