### ISSUE TITLE
Some Google maps links doesn't work

### ISSUE THREAD

**Issue by denisaug** [oscarotero/Embed#240]
Hi,

I've  found that some google maps links not working.

This one works ok:
https://www.google.es/maps/place/Tordoia,+A+Coru%C3%B1a/@43.0870993,-8.6410403,12z/data=!3m1!4b1!4m2!3m1!1s0xd2ef4006f1ef489:0x404f58273ca55a0

But this one not (removed place section):
https://www.google.es/maps/@43.0870993,-8.6410403,12z/data=!3m1!4b1!4m2!3m1!1s0xd2ef4006f1ef489:0x404f58273ca55a0

Google maps produces correct iframe for the last one from web ui.

Not sure if this is Embed problem or Google.

Thanks!

**Comment by oscarotero** [comment]
Embed get a 404 error with the second url. From web ui works fine but it redirects to the first link. I don't think Embed can do something here.

**Comment by denisaug** [comment]
Seems I've found something.

Accourding to Google Maps Embed API there are 5 embed modes: place, directions, search, view and streetview.

Embed GoogleMaps provider implements only 3 of them: place, directions, search.

View mode colud be implemented like this:

```
        switch ($this->mode) {
            case 'view':
                return Utils::iframe($url
                    ->withPath('maps/embed/v1/view')
                    ->withQueryParameters([
                        'center' => '70.8853928,-40.8414069', // should be parsed from url (@70.8853928,-40.8414069,4z)
                        'zoom' => '4', // should be parsed from url (@70.8853928,-40.8414069,4z)
                        'key' => $key,
                    ]));
```

And for streetview
 ```
   case 'streetview':
                return Utils::iframe($url
                    ->withPath('maps/embed/v1/streetview')
                    ->withQueryParameters([
                        'location' => '46.414382,10.013988', // should be parsed from url
                        'heading' => '210', // should be parsed from url
                        'pitch' => '10', // should be parsed from url
                        'fov' => '35', // should be parsed from url
                        'key' => $key,
                    ]));
```

**Comment by oscarotero** [comment]
I'm a bit bussy but if you want to work in a pull request, I'd be happy to review and merge it.

**Comment by denisaug** [comment]
Ok, I'll take a look.

**Comment by denisaug** [comment]
Hi, Oscar!
I've created a pull reuest #241 , please review.

**Comment by oscarotero** [comment]
Merged
