### ISSUE TITLE
Consider removing Fileinfo extension requirement

### ISSUE THREAD

**Issue by tschoffelen** [oscarotero/Embed#242]
Since one of the last versions (>3.0.8, not sure when it landed exactly), the library [uses the function `finfo_open`](https://github.com/oscarotero/Embed/blob/124da43f0ab184ccc7b400ec929d40021062711f/src/Http/CurlDispatcher.php#L162), which isn't a default PHP function.

It doesn't seem at first sight like this function is required for what the library does, so is it possible to remove this requirement? Or when this is really deemed neccessary, at the least update the README to include this new requirement.

Cheers!

**Comment by oscarotero** [comment]
hello. fileinfo extension is enabled by default since php v5.3 http://php.net/manual/en/fileinfo.installation.php
Are you having troubles with this? It can be included into composer.json as a requirement.

**Comment by tschoffelen** [comment]
Okay, strangely enough not on my hosts (running PHP 7.0), because I noticed that when I ran a `composer update` and suddenly the error rate shot up. But might be just me then.

**Comment by jasteele12** [comment]
Actually, having clients working with many of the cheaper shared hosting providers (Dreamhost, Bluehost, etc) this is NOT enabled by default on many of even the 5.5+ builds :(

**Comment by oscarotero** [comment]
Ok. Fileinfo is not really necesary. It just has been used for some minimal performance improvement. Now it's removed, so in the next release wont be required.
