### ISSUE TITLE
Authors do not work on different version

### ISSUE THREAD

**Issue by onigetoc** [oscarotero/Embed#244]
Hi, i can't updrade to version 5 because of my php version.

I noted that the author was found on version 1 and not version 2 and 3

Version 1: (authorName appear)
http://codesniff.com/Embed/demo/?url=http%3A%2F%2Fwww.santeweb.ch%2Fsanteweb%2FSujets_Prioritaires%2FAlimentation_allergie_intolerance%2FMaladies%2FQu_est_ce_que_l_histamine_Qu_est_ce_que_l_intolerance_l_histamine.php

Version 2: (authorName do not appear)
http://codesniff.com/Embed2/demo/?url=http%3A%2F%2Fwww.santeweb.ch%2Fsanteweb%2FSujets_Prioritaires%2FAlimentation_allergie_intolerance%2FMaladies%2FQu_est_ce_que_l_histamine_Qu_est_ce_que_l_intolerance_l_histamine.php

Version 3: (authorName appear)
https://oscarotero.com/embed3/demo/index.php?url=http://www.santeweb.ch/santeweb/Sujets_Prioritaires/Alimentation_allergie_intolerance/Maladies/Qu_est_ce_que_l_histamine_Qu_est_ce_que_l_intolerance_l_histamine.php

But sometime is the opposite, it work one version 2 but not version 1 and 3

I would like it to be more stable on version 2, what should i do?

**Comment by oscarotero** [comment]
Embed2 works fine in my server:
https://oscarotero.com/embed2/demo/index.php?url=http://www.santeweb.ch/santeweb/Sujets_Prioritaires/Alimentation_allergie_intolerance/Maladies/Qu_est_ce_que_l_histamine_Qu_est_ce_que_l_intolerance_l_histamine.php

I don't know why it does not work in yours.

**Comment by onigetoc** [comment]
I did update from your lattest Embed2 but i get a error on View all collected data because i have your old Embed2 script i think, Since i do not have composer i don't really witch file i need to update.
http://codesniff.com/Embed-2.x/demo/?url=http%3A%2F%2Fwww.thegatewaypundit.com%2F2017%2F08%2Ffemale-college-students-removed-howard-university-wearing-trump-hates%2F

**Comment by oscarotero** [comment]
Why don't you use the embed2 demo script?
https://github.com/oscarotero/Embed/blob/v2.x/demo/index.php

**Comment by onigetoc** [comment]
This is what i did, but without composer there's lot of file missing i think. even if i used the old embed2 scripts.
