### ISSUE TITLE
Do not find description even if is in og meta in version 2 & 3

### ISSUE THREAD

**Issue by onigetoc** [oscarotero/Embed#245]
Do not find description even if is in og meta

http://lesakerfrancophone.fr/le-danger-detre-pris-au-serieux

`<meta property="og:description" content="Par Dmitry Orlov – Le 8 août 2017 – Source Club Orlov Supposons que vous ayez Napoléon Bonaparte et Jésus-Christ chez vous pour le thé. Napoléon parle de conquête du monde alors q" />`

**Comment by oscarotero** [comment]
I cannot see this meta in the html code.

**Comment by onigetoc** [comment]
Sorry but its clearly there, and it happen often on many website and it happen often

**Comment by oscarotero** [comment]
Ok, in firefox these meta tags does not appear, but in chrome yes. I don't know why. Seems a server-side thing. Maybe changing the user agent?

**Comment by onigetoc** [comment]
My limited server can not use compose and i can't reinstall the version 2 or any version

**Comment by oscarotero** [comment]
I mean the server of the page (http://lesakerfrancophone.fr). Seems that return different responses for firefox and chrome. Maybe changing the user agent of Embed can fix this issue (but open the door to others :)
