### ISSUE TITLE
Call to undefined method Embed\Adapters\Youtube::getRequest()

### ISSUE THREAD

**Issue by MovingGifts** [oscarotero/Embed#246]
Thank you for this package! I have an issue which didn't exist in an older version of this package and used to work perfectly, not sure how to fix it with the new package:

```php
$info = Embed::create('https://www.youtube.com/watch?v=PP1xn5wHtxE');
$id = $info->getRequest()->getQueryParameter('v'); 
```

Any idea how to fix it?

**Comment by oscarotero** [comment]
Hello. The api changed a bit in the v3. You can use this:

```php
$info = Embed::create('https://www.youtube.com/watch?v=PP1xn5wHtxE');
$id = $info->getResponse()->getUrl()->getQueryParameter('v');
```
