### ISSUE TITLE
Allow serialization of Embed objects

### ISSUE THREAD

**Issue by edhelas** [oscarotero/Embed#247]
I'm currently building a cache system that wrap the Embed resolver.
The idea is to prevent the resolution of the same URL several times.

I'd like to serialize the object returned by `\Embed\Embed::create($url)` and I'm wondering if there is ways to do that properly (by maybe cleaning up some properties…)?

**Comment by oscarotero** [comment]
The object returned contains a bunch of information, not only the title, description, images, etc, but also all info fetched by all providers (oembed, opengraph, html code, etc), the info of all requests and responses (headers, status code, time, size, etc). I think the best you can do is simply save an array with the desired information you want to cache. Something like:
```php
$info = Embed::create($url);
$cachedInfo = [
    'title' => $info->title,
    'code' => $info->code,
    //etc...
];
$cache->setItem($url, $cachedInfo);
```

**Comment by edhelas** [comment]
Indeed that's what I've done :) Thanks again for the feedback!
