### ISSUE TITLE
Only Code video or embed code without iframe

### ISSUE THREAD

**Issue by marcelogarbin** [oscarotero/Embed#250]
Hi,

Sorry to open this topic, but I need some help. Is there any way to get only the video code from the URL or Embed?

Example: `https://www.youtube.com/watch?v=en2D_5TzXCA`

Embed/Code video: `en2D_5TzXCA`

Thank's

**Comment by oscarotero** [comment]
This was discussed in other issues like #136 
The version 3.x includes some changes in the api so the way to get the code is different:

```php
$info = Embed::create($url);

if ($info->providerName === 'Youtube') {
    $url = $info->getResponse()->getUrl();
    $code = $url->getQueryParameter('v');
}
```

**Comment by jasteele12** [comment]
@marcelogarbin Non-Embed (PHP only) version just FYI:

`<?php  // get video code
$url = 'https://www.youtube.com/watch?v=en2D_5TzXCA&lady=gaga...';
parse_str(parse_url($url, PHP_URL_QUERY), $qParams);  // same func used for $_GET, etc.
$code = $qParams['v'];
?>
<iframe allowtransparency="true" scrolling="no" width="400" height="300" frameborder="0" allowfullscreen src="//www.youtube.com/embed/<?php echo $code; ?>"></iframe>
`

**Comment by marcelogarbin** [comment]
@jasteele12 @oscarotero I was thinking of doing only PHP, but I was thinking that I would have to do to the other providers, like vimeo, facebook, intagram... So I asked if there was already something in the package, I did not find it in the documentation.

Thanks for sharing.

**Comment by marcelogarbin** [comment]
Would there be any way to capture only the entire embed URL without the iframe tags?

Ex.: 
```
$info = Embed::create('https://www.youtube.com/watch?v=en2D_5TzXCA');
$info->code; //The code without iframe, only url
```

From `https://www.youtube.com/watch?v=en2D_5TzXCA` to `https://www.youtube.com/embed/en2D_5TzXCA`

**Comment by marcelogarbin** [comment]
@oscarotero For example, where (documentation) did you bring the "`$url->getQueryParameter('v')`" method?

I would like to get the vimeo now, where do I find the documentation for these methods?

I checked this: https://github.com/oscarotero/Embed#accessing-to-advanced-data
But I have not found the methods I can use to fetch information.

**Comment by marcelogarbin** [comment]
I have resolved the following for YouTube and Vimeo, ex.:
```
public function video($url, $onlyCode = FALSE){
    $video = Embed::create($url);

    if($onlyCode === TRUE){
        switch($video->providerName){
            case 'YouTube':
                return $video->getResponse()->getUrl()->getQueryParameter('v');
                break;
            case 'Vimeo':
                return $video->getResponse()->getUrl()->getDirectoryPosition(0);
                break;
        }
    }

    return $video;
}
```

Thank's

**Comment by garbinmarcelo** [comment]
Hi, @oscarotero how are you?

I updated the package from version 3 to 4, but this code `$video->getResponse()->getUrl()->getQueryParameter('v');` is not working. 

How can I make it work? is there another way?

Thanks

**Comment by oscarotero** [comment]
Responded here: https://github.com/oscarotero/Embed/issues/136#issuecomment-723445466
