### ISSUE TITLE
Facebook embeds use the server language

### ISSUE THREAD

**Issue by bdeclerc** [oscarotero/Embed#251]
I'm using embed through the Drupal https://www.drupal.org/project/url_embed project, but I suspect the problem (and the solution?) might be in Embed

When I try to embed a facebook post on my (Dutch) website, the Facebook UI elements return in German, as far as I can tell because the embedded code:
```
<!--//--><![CDATA[// ><!--
(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/de_DE/sdk.js#xfbml=1&version=v2.11';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));
//--><!]]>
```
uses a de_DE connection - I suspect Facebook is auto-assigning the language because my hosting service is in Germany - testing op https://oscarotero.com/embed3/demo/ returns the data with an en_GB  language (which matches the location I find online for oscarotero.com, which is "United Kingdom")

If a curl requests provides an "Accept-Language" http-header to Facebook, they will follow the suggested language, so technically it's possible to tell FB to ignore the IP-location data when requesting the post, but I'm not finding a way of telling PHP Curl to do that when called, so I'm not sure if there's anything I could do myself to fix this (for example by setting an extra header for curl through php.ini drupal's settings.php or something similar)

**Comment by oscarotero** [comment]
Hi.
To do that, you have to create an instance of the dispatcher with your custom configuration. [There's an example in the README](https://github.com/oscarotero/Embed#the-dispatcher)

I guess something like the following should work:

```php
use Embed\Embed;
use Embed\Http\CurlDispatcher;

$dispatcher = new CurlDispatcher([
    CURLOPT_HTTPHEADER => ['Accept-Language' => 'en_GB']
]);

$info = Embed::create($url, null, $dispatcher);
```

I don't know if the drupal's url_embed plugin allows to configure that.
