### ISSUE TITLE
Encoded characters in image URLs have wrong decoding

### ISSUE THREAD

**Issue by alivelimeli** [oscarotero/Embed#255]
Hello,

I'm trying to use your library in a website which there is an image like this url:

`http://www.company.com/Uploads/product_image%20copy.png`

But when i try to reach images i saw that image URL is like:

`http://www.company.com/Uploads/product_image+copy.png`

So it changed `%20` to `+` character. Its wrong.

**Comment by MrHexagon** [comment]
I had same issue. Fixed by replacing urlencode with rawurlencode https://github.com/MrHexagon/Embed/commit/fc5a18596e61fa389907f8039de583a948294d46

**Comment by Vinorcola** [comment]
I had the same issue today. I'll create a new pull request that also fix Google Plus problem.
