### ISSUE TITLE
Getting largest image from YouTube videos

### ISSUE THREAD

**Issue by chrisgherbert** [oscarotero/Embed#256]
YouTube videos are usually (always?) returning a small, letterboxed 4:3 thumbnail from $video->image.  Since the images all include a pixel count, it seems like it would be easy to provide a way to just return the largest one - $video->largestImage, maybe?

**Comment by oscarotero** [comment]
You can use the option `choose_bigger_image` to get the bigger image instead the first (and usually most relevant) image. Here's more info: https://github.com/oscarotero/Embed#example-with-all-options
