### ISSUE TITLE
Do not find image

### ISSUE THREAD

**Issue by onigetoc** [oscarotero/Embed#258]
Hi, i'm curious about the fact that Embed do not find the main image from this website.
http://www.lelibrepenseur.org/veronique-hammerer-deputee-lrem-mon-mari-ne-peut-pas-sacheter-de-porsche-cayenne-cest-terrible/

https://oscarotero.com/embed3/demo/index.php?url=http://www.lelibrepenseur.org/veronique-hammerer-deputee-lrem-mon-mari-ne-peut-pas-sacheter-de-porsche-cayenne-cest-terrible/

but Facebook do find it.
https://www.facebook.com/sharer.php?u=http://www.lelibrepenseur.org/veronique-hammerer-deputee-lrem-mon-mari-ne-peut-pas-sacheter-de-porsche-cayenne-cest-terrible/

May be it's because the image host url is different?
http://i0.wp.com/www.lelibrepenseur.org/wp-content/uploads/2017/12/mon_mari_ne_peut_sacheter_une_porsche_cayenne2.jpg?resize=610%2C344

**Comment by oscarotero** [comment]
Yes but you can change the configuration:

```php
$info = Embed::create($url, [
    'html' => [
        'external_images' => true
    ]
]);
```

**Comment by onigetoc** [comment]
How i do this in V2 and where?

thank's

**Comment by oscarotero** [comment]
```php
$config = [
    'providers' => [
        'html' => [
            'externalImages' => true
        ]
    ]
];
```

**Comment by onigetoc** [comment]
Do not work, where i put this?
inside my try?
