### ISSUE TITLE
Reddit code is empty

### ISSUE THREAD

**Issue by l0c0luke** [oscarotero/Embed#261]
Using a reddit URL doesnt return any code. But it does seem they provide a means to get oembed code with the url used as aparameter?

To get the embed code for the url https://www.reddit.com/r/investing/comments/7pfpeq/buffett_on_cyrptocurrencies_i_can_say_almost_with/ I can get the data from 

https://www.reddit.com/oembed?url=https://www.reddit.com/r/investing/comments/7pfpeq/buffett_on_cyrptocurrencies_i_can_say_almost_with/

**Comment by oscarotero** [comment]
Hi. Thanks for reporting.
I just added support for reddit oembed.

**Comment by l0c0luke** [comment]
very cool. thanks.

test failing right now.

**Comment by l0c0luke** [comment]
Greetings... just following up on this to see if I am not using right version maybe? I am not sure where your demo is at... but the below link returns a blank `code` field...

https://oscarotero.com/embed3/demo/index.php?url=https%3A%2F%2Fwww.reddit.com%2Fr%2Ftezos%2Fcomments%2Fa5uiz3%2Fquick_bit_by_kathleen_breitman_on_not_watching%2F
