### ISSUE TITLE
Is this a debugging code? it breaks my JSON output!

### ISSUE THREAD

**Issue by EazyServer** [oscarotero/Embed#264]
https://github.com/oscarotero/Embed/blob/2644cb5557d32fc1f5e40710e10d95034f3699e6/src/Providers/Api/Facebook.php#L22

**Comment by oscarotero** [comment]
Opps! Yes. I'm fixing it.

**Comment by oscarotero** [comment]
Fixed and relased a new version: https://github.com/oscarotero/Embed/releases/tag/v3.3.1

**Comment by EazyServer** [comment]
thank you.
