### ISSUE TITLE
Twitter requires publish subdomain for oembed links

### ISSUE THREAD

**Issue by Berdir** [oscarotero/Embed#273]
According to https://dev.twitter.com/web/embedded-timelines/oembed, twitter expects you to use the publish subdomain.

Without it, either redirects to mobile or just returns the profile page of the oembed user.

Adding a \Embed\Providers\OEmbed\Twitter class with the expected getEndPoint() and getPatterns() methods seems to fix it. We're still using 2.x, so I will create a PR for that, would be great if we could get a new release for that too, not just 3.x as updating won't be so easy (we use it through a drupal module, so don't have a direct dependency)

**Comment by oscarotero** [comment]
New versions 2 & 3 released

**Comment by Berdir** [comment]
That was fast, thanks!
