### ISSUE TITLE
Embed triggers a Not Acceptable error when pulling a file from IIS.

### ISSUE THREAD

**Issue by maranda** [oscarotero/Embed#275]
Copying issue from Movim, https://github.com/movim/movim/issues/656

**Comment by maranda** [comment]
https://lightwitch.org/Media/Default/Pictures/server_station.jpg

**Comment by edhelas** [comment]
Master looks fine to me, I'll update the library version as soon as a new release is made :)

**Comment by oscarotero** [comment]
Great. New version 3.3.3 released including this fix.
