### ISSUE TITLE
Tumblr redirecting to privacy page

### ISSUE THREAD

**Issue by nicolas-t** [oscarotero/Embed#278]
Hello 

If I do : 
https://oscarotero.com/embed3/demo/index.php?url=http%3A%2F%2Fhueandsaturation.tumblr.com%2Fpost%2F132401456097%2Fcristiana-couceiro
I get very basic results.

But, the source code of the page has : 
`<link rel="alternate" type="application/json+oembed" href="https://www.tumblr.com/oembed/1.0?url=http://hueandsaturation.tumblr.com/post/132401456097/cristiana-couceiro" title="&copy; cristiana couceiro"/>`

Which contains more infos : 

```json
{
	"cache_age": 3600,
	"url": "http://hueandsaturation.tumblr.com/post/132401456097/cristiana-couceiro",
	"provider_url": "http://www.tumblr.com",
	"provider_name": "Tumblr",
	"author_name": "Cristiana Couceiro",
	"version": "1.0",
	"author_url": "http://hueandsaturation.tumblr.com/",
	"type": "rich",
	"html": "<div class=\"tumblr-post\" data-href=\"https://embed.tumblr.com/embed/post/NiOdC4b-kWm1TC-ou9G6gQ/132401456097\" data-did=\"aa9d61208f49cdab5d98937ebeb5441ea1f862e4\"  ><a href=\"http://hueandsaturation.tumblr.com/post/132401456097/cristiana-couceiro\">http://hueandsaturation.tumblr.com/post/132401456097/cristiana-couceiro</a></div><script async src=\"https://assets.tumblr.com/post.js\"></script>",
	"height": null,
	"width": 540
}
```

---

Ok, I just cloned you repo and did some tests, in fact the problem comes from tumblr, if you browse in incognito mode you'll be redirected (302) here : 
https://www.tumblr.com/privacy/consent?redirect=http%3A%2F%2Fhueandsaturation.tumblr.com%2Fpost%2F132401456097%2Fcristiana-couceiro

and that's page Embed tries to parse.

Do you have any idea of a workaround ? a tumblr Adapter ?

Thanks

**Comment by oscarotero** [comment]
Yes, tumblr creates a cookie after submit the privacy consent form, but it does not work without javascript.
I guess he only solution is create a tumblr adapter and create and use the oembed provider.
Do you like to work in a PR?

**Comment by nicolas-t** [comment]
I can try yes.

The adapter will take : 
http://hueandsaturation.tumblr.com/post/132401456097/cristiana-couceiro
transform it into : 
https://www.tumblr.com/oembed/1.0?url=http://hueandsaturation.tumblr.com/post/132401456097/cristiana-couceiro
and use OEmbed provider to extract and return the data ? 

Are there on this repo some php files I could use as examples ? 

Thanks

**Comment by oscarotero** [comment]
v3.3.4 released
