### ISSUE TITLE
Image sizes are simply width * height

### ISSUE THREAD

**Issue by edhelas** [oscarotero/Embed#280]
This is more a question than a bug but I'm wondering why the 'size' parameter of the pictures retrieved are actually their width*height (see https://github.com/oscarotero/Embed/blob/632c80db62bcb7e601b81f01d882d698bb472ba3/src/Adapters/Adapter.php#L622).

Instead I'd expect to have the actual size (in bits) of the images retrieved as I can easily compute width*height myself from the information retrieved from Embed.

Am I missing something :) ?

**Comment by oscarotero** [comment]
Yes, maybe the name is confusing.
`size` is used to get the bigger image, so it can be used as the main image using the `choose_bigger_image` option.
Getting the number of bytes is more dificult because the image is not fully downloaded (just the minimum bytes possible to get the width and height). You could use the `Content-Lenght` header, but is not always possible.

**Comment by edhelas** [comment]
That would be really interesting to get, actually a HEAD request is giving that information quite often. But I understand more now, thanks for the answer.

**Comment by edhelas** [comment]
Would it be possible to try to add this kind of information to the metadata attached to the pictures? :)

**Comment by oscarotero** [comment]
You can get all http information from the responses:

```php
$info = Embed::create($url);

$images = $info->images;
$responses = $info->getDispatcher()->getAllResponses();

foreach ($responses as $response) {
    $url = (string) $response->getUrl();
    $image = search_image_by_url($url, $images);

    if ($image) {
        echo $response->getHeader('Content-Length');
    }

}

```

**Comment by edhelas** [comment]
Thanks a lot for the tip. I've added something similar to my code https://github.com/movim/movim/commit/14eb577e6669a8c79fac4c62da2a2720a2840273 :) Closing the ticket.
