### ISSUE TITLE
Japanese Link

### ISSUE THREAD

**Issue by boxingnguyen** [oscarotero/Embed#281]
I have issue with this link
https://ja.m.wikipedia.org/wiki/LAMP_(%E3%82%BD%E3%83%95%E3%83%88%E3%82%A6%E3%82%A7%E3%82%A2%E3%83%90%E3%83%B3%E3%83%89%E3%83%AB)
or acctually it is
https://ja.m.wikipedia.org/wiki/LAMP_(ソフトウェアバンドル)
I can't get OGP because invalid url error ( status code 404). But it's a correct link and get OGP well with facebook. 
Thank you so much!

**Comment by oscarotero** [comment]
Hi.
This link works fine to me. You can test it here:
https://oscarotero.com/embed3/demo/index.php?url=https%3A%2F%2Fja.m.wikipedia.org%2Fwiki%2FLAMP_%28%25E3%2582%25BD%25E3%2583%2595%25E3%2583%2588%25E3%2582%25A6%25E3%2582%25A7%25E3%2582%25A2%25E3%2583%2590%25E3%2583%25B3%25E3%2583%2589%25E3%2583%25AB%29

**Comment by boxingnguyen** [comment]
Thank you so much! It's fine. I found a problem. It's my fault when I would like to display Japanese char.
