### ISSUE TITLE
Wrong encoding description!

### ISSUE THREAD

**Issue by boxingnguyen** [oscarotero/Embed#284]
Here is the link: http://marketing.itmedia.co.jp/mm/articles/1708/14/news039.html
Right description: 「マーケティング4.0」とは何か。本稿では、首都大学東京大学院准教授の水越康介氏とネスレ日本の津田匡保氏の講演から、その概念と実践について探る。【更新】
Wrong description: 
`u}[PeBO4.0vÆÍ½©B{eÅÍAñsåwåw@y³öÌzNîÆlXú{ÌÃc§ÛÌu©çA»ÌTOÆÀHÉ`

I used mb_convert_encoding function to change encoding to SJIS but it does not work! 
Please help me, thank you so much!

**Comment by oscarotero** [comment]
Can you try to add a new "if" here
https://github.com/oscarotero/Embed/blob/master/src/Http/Response.php#L75
with the new encoding?
Thanks

**Comment by boxingnguyen** [comment]
I got it. I add these lines in line 72 **before** checking ISO-8859-1. I was so confused when I put them in L75. It's always return ISO-8859-1, not SJIS. 
`                elseif (mb_detect_encoding($content, 'SJIS', true) === 'SJIS') {
                    $content = mb_convert_encoding($content, 'HTML-ENTITIES', 'SJIS');
                    $content = preg_replace('/<head[^>]*>/', '<head><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=shift_jis">', $content);
                }`
 
Thank you so much!

**Comment by oscarotero** [comment]
Do you like to do a pull request with this change?

**Comment by boxingnguyen** [comment]
Sorry for the delayed reply. Yes, I would like to do it. I pulled request.
