### ISSUE TITLE
facebook links throwing error

### ISSUE THREAD

**Issue by ravipula** [oscarotero/Embed#285]
hi, I really like using this package. I have been using this for a while. I recently encountered an issue with facebook links. Earlier it was working fine but this has been occurring recently.
The issue is with facebook links which are throwing an error saying "iconv(): Wrong charset, conversion from `&quot;UTF-8&quot;' to `UTF-8//TRANSLIT//IGNORE' is not allowed" like this. I've debugged to some extent to know the trace of error. The error is from the Utils.php file in the src folder. The function call toUtf8 has a iconv method where the UTF-8 charset is converted to the UTF-8//TRANSLIT//IGNORE. So, while using the facebook links the charset that is extracted from the page is setting the $charset here as ""UTF-8"" i.e it is having a quotes inside a quotes. so this isn't a valid charset and iconv() is throwing an error on this. Any suggestions are welcome. 

please help, Thanks a lot!

**Comment by oscarotero** [comment]
Can I get a link to reproduce this error?
Facebook links seems to work correctly to me: https://oscarotero.com/embed3/demo/index.php?url=https%3A%2F%2Fwww.facebook.com%2Fhistoriadelarteblog%2Fposts%2F1026066147549607

**Comment by ravipula** [comment]
i'm trying this on local. Yeah it was working fine on your demo page. But as i explained earlier i'm not sure what is causing this conflict, as rest of all the url's are working fine. This is happening just for facebook.
<img width="631" alt="screen shot 2018-07-26 at 9 59 13 am" src="https://user-images.githubusercontent.com/23690673/43273800-9f21f708-90ba-11e8-992a-2f260fbdb11c.png">
As you can see in the image for the $charset value it was extracting from the content.

**Comment by oscarotero** [comment]
this seems a problem with your local php configuration. Can you show me the value of `$result` here? https://github.com/oscarotero/Embed/blob/18ea6ad7e609499eee0466c81da2d9a7fa6e00f2/src/Http/CurlResult.php#L42

**Comment by oscarotero** [comment]
I've commited a change to fix this issue. Can you confirm whether it works fine now?

**Comment by ravipula** [comment]
Sorry for the delayed reply i'm using composer to install the package. i have updated it but i don't see your change to the respective file. Thanks @oscarotero

**Comment by oscarotero** [comment]
The changes are not tagged. You must use the `dev-master` version.

**Comment by ravipula** [comment]
@oscarotero I did and now it's working. Thanks a lot for your time man appreciate your help.
