### ISSUE TITLE
<url> malformed

### ISSUE THREAD

**Issue by byndstd** [oscarotero/Embed#287]
Hi
I'm using your embed plugins but if I insert an url for example : example.com
I get this error 
`Embed\Exceptions\InvalidUrlException
<url> malformed

    1. in I:\zzerver\uwmp-php7\u7000\www\yii2b\vendor\embed\embed\src\Embed.php at line 144

	$adapter = self::getClass('Webpage', $config);

	if ($adapter::check($response)) {
		return new $adapter($response, $config, $dispatcher);
	}

	if ($response->getError() === null) {
		$exception = new Exceptions\InvalidUrlException(sprintf("Invalid url '%s' (Status code %s)", (string) $url, $response->getStatusCode()));
	} else {
		$exception = new Exceptions\InvalidUrlException($response->getError());
	}

	$exception->setResponse($response);

	throw $exception;
}`
I try to change the class : abstract class Embed , that if the url is invalid just return the url, instead of embed code but i didn't succeed, can you please help me .

**Comment by oscarotero** [comment]
Why not simply use a try/catch?
```php
$url = 'http://example.com';

try {
    $info = Embed::create($url);
    return $info->code;
} catch (Exception $e) {
    return $url;
}
```

**Comment by byndstd** [comment]
thank you so much for your replay
