### ISSUE TITLE
Get final DOM after javascript such as ReactJs sites

### ISSUE THREAD

**Issue by tiger154** [oscarotero/Embed#288]
Hi there,

Question is is there any option we can grab after javascript generate final DOM ?

I tried to scrap this site 
  - https://www.intomore.com/culture/this-queer-convention-wants-more-lesbian-and-bi-visibility-in-the-media 

And it returns nothing. after I check raw data I realized it return bunch of javascript source most of them
looks like they are using ReactJs or similar framework. 

So please let me know if there is any way option for now? 

Thank you sir!

**Comment by oscarotero** [comment]
No, there's no option for that. This library only get the code returned by the server but does not execute it.
