### ISSUE TITLE
Can't get images

### ISSUE THREAD

**Issue by tiger154** [oscarotero/Embed#289]
Hi I was trying to scrap this page. When I tried it with on demo site(https://oscarotero.com/embed3/demo/index.php) 

There is no images. but When I see scraped content part I can see there is all html. 
Can you give any hint what could be the problem? 

test-link => http://links.newsletters.allure.com/servlet/MailView?ms=MTQwOTExMDES1&r=MjUzMzE0OTE5MDcyS0&j=MTQ2MTcxNTkzMQS2&mt=1&rt=0

**Comment by oscarotero** [comment]
This is because by default, only images under the same domain will be selected. This is to avoid getting banners or other non relevant images. You can configure the html provider using the option `external_images` to true, or providin an array of allowed domains.

**Comment by tiger154** [comment]
@oscarotero  Ah thank you I got it . :)
