### ISSUE TITLE
Get `twitter:card` data

### ISSUE THREAD

**Issue by KeurbyCandy** [oscarotero/Embed#290]
Hi there,

Is there a possibility to get the twitter:card data from any provider?

It seems the `$info->type; //The page type (link, video, image, rich)` is not what I want :(.

I tried with the HTML provider but I can't access the `twitter:card` too. Or maybe I miss use?

Here is an example where I need to get the `twitter:card` value:
https://oscarotero.com/embed3/demo/index.php?url=https%3A%2F%2Fbits.blogs.nytimes.com%2F2011%2F12%2F08%2Fa-twitter-for-my-sister%2F
In the webpage => `<meta name="twitter:card" value="summary">`
But I get:
```php
$info = Embed::create($url); // $info->getType() === 'rich'
``` 

If I try this way:
```php
$providers = $info->getProviders();
$twitterProvider = $providers['twittercards']; // $twitterProvider->getType() === null
```

I need to get the value because `summary` and `summary_large_image` are not displaying the same way. Hope you can help me on this :).

Thanks for the great lib btw, you did a really good job ! :)

**Comment by KeurbyCandy** [comment]
Ok I think I got it but it's Twitter's fault IMO.

The link I sent to you is is composed by this meta `<meta name="twitter:card" value="summary">`. But in Twitter's documentation, they wrote `<meta name="twitter:card" content="summary_large_image">`. But they parse the `value` and the `content`.

Btw in your https://github.com/oscarotero/Embed/blob/46e19804e330065c899657c047288f792e2bca02/src/Providers/TwitterCards.php#L26, you only parse `content`.

IMO it's the site's fault to not deal properly with twitter meta.

But we may do need to parse the `value` if twitter does it :(.

What do you think about it?

**Comment by oscarotero** [comment]
I close this, because it was discussed in #291
