### ISSUE TITLE
getCode() is missing a case for imageHtml

### ISSUE THREAD

**Issue by phptek** [oscarotero/Embed#293]
In embed/embed/src/Adaptors//File.php the `getCode()` method doesn't work properly for remote images.

As far as I can tell, there should be a clause for "imageHTML".

Adding the following clause to `getCode()` fixes the problem (Using v3.3.5 with PHP7.1)

```
    case 'imageHtml':
        return Utils::imageHtml($this->url,'', $this->imageWidth, $this->imageHeight);
```

This method's `switch` block is also missing a default. It should decide what is a suitable default to pass onto API consmers. Default to a dummy `1px x 1px` image in an `<img>` element perhaps? Or throw an exception?

**Comment by oscarotero** [comment]
`getCode()` is not required to return a code, if the url has no code, it simply returns null, so no default block is needed.
But I'm ok with having a 'imageHtml' case to return an `img` html element. So if you create a pull request, I'll be happy to merge it.
Thanks!

**Comment by phptek** [comment]
Will do. Many thanks.

**Comment by phptek** [comment]
@oscarotero Done. See #294 :-)
