### ISSUE TITLE
OpenGraph provider appears to not read tags from page content.

### ISSUE THREAD

**Issue by wshawn** [oscarotero/Embed#295]
Google collects an Organization, CollegeOrUniversity, ProfilePage, Website, and Person: https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fwww.shawnwilkerson.com

Embed only appears to grab header meta. Is this the expected functionality?

**Comment by oscarotero** [comment]
Only schemas with JSON-LD format are currently supported. Microdata and RDFa formats are not supported because requires a huge work (or using dependencies). And the main aim of this library is getting simple data to embed an url, not extract all possible values.

**Comment by wshawn** [comment]
ok. I was not aware of that. JSON-LD is just extremely succinct, but may not be in the spirit of the original intention of OpenGraph, which is to tag elements and content.
