### ISSUE TITLE
Invalid URL scheme: "aiapp"

### ISSUE THREAD

**Issue by rez1dent3** [oscarotero/Embed#302]
Hello.

The link opens and works, but you cannot get embed.

```php
$info = \Embed\Embed::create('https://appleinsider.ru/iphone/apple-mozhet-predstavit-iphone-xs-i-iphone-xs-max-v-krasnom-cvete.html');
```

Error:
Invalid URL scheme: "aiapp"

**Comment by oscarotero** [comment]
Ok, I fixed this error in dev-master. Thanks for notify this.

**Comment by rez1dent3** [comment]
@oscarotero Works, thanks. Waiting for tag )
