### ISSUE TITLE
Class embed\embed not found

### ISSUE THREAD

**Issue by gizburdt** [oscarotero/Embed#306]
Hi,

Just installed the package. When I `use Embed\Embed;` I get the following error:

```
Class 'Embed\Embed' not found
```

Using this code:
```
use Embed\Embed;

dd(Embed::create('https://youtube.com'));
```

I installed the latest version, using PHP 7.1

**Comment by oscarotero** [comment]
have you included the composer autoloader?

**Comment by gizburdt** [comment]
Yes. I'm using Laravel, so it's included automatically

**Comment by oscarotero** [comment]
I'm sure this is a problem with your configuration/framework not Embed itself.

**Comment by gizburdt** [comment]
Yeah could be. Strange thing is, it is loaded with composer, so should just work. Will have a further look at it, thanks!

**Comment by gizburdt** [comment]
Was building a package (composer) within a project (also composer). I ran the wrong composer install, so it wasn't loaded. Thanks for your replies :)

**Comment by zumbidoweb** [comment]
same here
