### ISSUE TITLE
Twitch provider

### ISSUE THREAD

**Issue by msurguy** [oscarotero/Embed#312]
Hi! Thank you so much for this package and maintenance! 

I was wondering if support for Twitch was on the horizon or if I should make a PR for the package to support it. 

AFAIK, here's the oembed endpoint for it: 

https://api.twitch.tv/v5/oembed?url=

And here's an example URL that you can inspect for the response:
https://api.twitch.tv/v5/oembed?url=https%3A%2F%2Fwww.twitch.tv%2Friotgames%2Fv%2F72749628 

Thanks!

**Comment by oscarotero** [comment]
Definitely. You can create a PR adding a new OEmbed provider here: https://github.com/oscarotero/Embed/tree/master/src/Providers/OEmbed

FYI, I have this issue #269 that like to do some day and it includes twitch.

**Comment by MrMoronIV** [comment]
I just downloaded the package from packagist but it seems the twitch url is not detected when I just provide a regular stream url. Is there something needed to make this work?

**Comment by msurguy** [comment]
@MrMoronIV can you please provide the URL you're trying?

**Comment by MrMoronIV** [comment]
https://twitch.tv/failarmy

**Comment by MrMoronIV** [comment]
In addition, I expect it to give a player in `$info->code`, or is that not the case?

**Comment by oscarotero** [comment]
Seems like `https://api.twitch.tv/v5/oembed?url=https%3A%2F%2Fwww.twitch.tv%2Ffailarmy&format=json` returns a 204 (no content) response.

**Comment by MrMoronIV** [comment]
Which means....? Twitch has an internal error? You can see it's just a regular stream :)

**Comment by oscarotero** [comment]
Seems like twitch oembed api does not work. Don't know if twitch stopped supporting oembed.

**Comment by MrMoronIV** [comment]
I've investigated a little and it seems like the right way to get twitch on your site is to just embed an iframe as explained here: https://dev.twitch.tv/docs/embed/video-and-clips/

```
<iframe
    src="https://player.twitch.tv/?<channel, video, or collection>"
    height="<height>"
    width="<width>"
    frameborder="<frameborder>"
    scrolling="<scrolling>"
    allowfullscreen="<allowfullscreen>">
</iframe>
```

Not sure if this goes against the idea of oembed, but the oembed api seems to be non existing as of writing. Is this something worth implementing in this project or is it out of scope?

**Comment by MrMoronIV** [comment]
Hmm, in addition, it DOES work for clips and videos, just not live-streams, I guess only live streams are supposed to be embedded using the iframe approach.
