### ISSUE TITLE
getting info NULL unlike in your test web

### ISSUE THREAD

**Issue by byndstd** [oscarotero/Embed#313]
hello If you can please help me; I'm getting $info Null for some links but in your test I get some results; Can you please help me to fix this problem the Link I tried is 
`https://www.quirksmode.org/html5/videos/big_buck_bunny.mp4 `
in your test web I get the code of the link but in my web I get result as var_dump($info) I get NULL

**Comment by oscarotero** [comment]
No idea. It can be due many reasons (php config, server, etc) In theory, this url should be resolved with this adapter: https://github.com/oscarotero/Embed/blob/master/src/Adapters/File.php so try to debug it.

**Comment by byndstd** [comment]
> No idea. It can be due many reasons (php config, server, etc) In theory, this url should be resolved with this adapter: https://github.com/oscarotero/Embed/blob/master/src/Adapters/File.php so try to debug it.

Ok Thank you. Honestly your plugin oscarotero/Embed seriously is the best php plugin ever 
You are the best . you are genius.

**Comment by oscarotero** [comment]
I'm not a genius :D:D, but thanks for your nice words :)
