### ISSUE TITLE
Live Video

### ISSUE THREAD

**Issue by marcelogarbin** [oscarotero/Embed#317]
Hello,

Is it possible to check if a video is live? example live on Youtube ...

If so, how could you do that?

Thank you

**Comment by oscarotero** [comment]
If youtube does not return this info, this library either.

**Comment by marcelogarbin** [comment]
Okay, I found the "islivebroadcast" attribute, but it gets "true" even after the live has been finalized. I spent some time trying to find something to try to check this, but without success.
My idea would be very simple, it would just take this status and put a div in the website layout that the video is "live".

I would like tips on how to do this, and thank you for this package. It is excellent.

**Comment by oscarotero** [comment]
If this value is returned by any provider (oembed, opengraph, html, etc), you can get it in this way: https://github.com/oscarotero/Embed#accessing-to-advanced-data
