### ISSUE TITLE
UTF-8 encoding issue in Korean?

### ISSUE THREAD

**Issue by budiantoip** [oscarotero/Embed#318]
Hello,

There's an encoding issue in Korean in `Description`, could you please check it out?

https://oscarotero.com/embed3/demo/index.php?url=https://blockpost.com/tech/41234/

Thank you

**Comment by oscarotero** [comment]
I've made some changes in the encoding detection and now it works fine in your case but this could break other cases. I have to do more test before release. You can use the `dev-master` version meanwhile.

**Comment by budiantoip** [comment]
Ok, you did an amazing job, thanks for your effort
