### ISSUE TITLE
Privacy

### ISSUE THREAD

**Issue by thierrymaasdam** [oscarotero/Embed#320]
Hi there,

I was wondering about the GDPR in regard to this plugin. If I embed, let's say, an Instagram post, will that have consequences for my users in regard to their privacy? 

Looking forward to hearing from you.

Thanks!

**Comment by oscarotero** [comment]
Hi.
If you can embed an instagram post, is because instagram allows to embed that post and provide the code to do it. This library only returns that code, that is public and accessible by anyone, but do not store any information. I guess GDPR affects to instagram.

**Comment by thierrymaasdam** [comment]
Hi Oscar,

Thank you for your reply. I get it: it's up to Instagram whether to install cookies or not, and this cannot be regulated through this package.

Anyways, thank you for your effort in maintaining this package — as well as creating it in the first place.

Yours,
Thierry
