### ISSUE TITLE
all request headers are always overwritten

### ISSUE THREAD

**Issue by shucream0117** [oscarotero/Embed#321]
Hello.

I'd like to set `Accept-Language` header.
So, I tried to set `CURLOPT_HTTPHEADER` shown as below, but it doesn't go well.

```php
$curlDispatcher = new CurlDispatcher([
            CURLOPT_HTTPHEADER => ['Accept-Language: ja,en;q=0.9'],
            CURLOPT_MAXREDIRS => 20,
            CURLOPT_CONNECTTIMEOUT => 10,
            CURLOPT_TIMEOUT => 10,
            CURLOPT_SSL_VERIFYPEER => false,
            CURLOPT_SSL_VERIFYHOST => false,
            CURLOPT_ENCODING => '',
            CURLOPT_AUTOREFERER => true,
            CURLOPT_USERAGENT => '',
            CURLOPT_IPRESOLVE => CURL_IPRESOLVE_V4,
        ]);
Embed::create($url, null, $curlDispatcher);
```

I guess https://github.com/oscarotero/Embed/blob/v3.3.9/src/Http/CurlDispatcher.php#L99 this code overwrites `CURLOPT_HTTPHEADER`.

In addition, I tried https://github.com/oscarotero/Embed/issues/135 this way. But it also didn't go well.

Is there a good way to set optional request headers?

**Comment by oscarotero** [comment]
Ok, I just changed the code to not override the `CURLOPT_HTTPHEADER` but append more headers. Can you try if works fine now?
Thanks!
