### ISSUE TITLE
Issue with UTF-8 processing

### ISSUE THREAD

**Issue by chekalsky** [oscarotero/Embed#324]
Since v3.4.0, library stopped working right in most cases with cyrillic in UTF-8 . ([example](https://oscarotero.com/embed3/demo/index.php?url=https%3A%2F%2Ftjournal.ru%2Fnews%2F106629-evrokomissiya-proverit-amazon-na-predmet-narusheniya-antimonopolnogo-zakonodatelstva))

That's because of [changes here](https://github.com/oscarotero/Embed/commit/56d5a6cff3625d6e46adcf64f2ac3021f90dab56).

In case there is UTF-8 detected you need to make `mb_convert_encoding($content, 'HTML-ENTITIES', 'UTF-8')` before `loadHTML` as it was before this commit to make it works with UTF-8 right.

**Comment by oscarotero** [comment]
Ok, I'll try to fix it.
It's really hard to find a way to parse html in all encodings 😅

**Comment by oscarotero** [comment]
I think it's fixed now. v3.4.1 released
