### ISSUE TITLE
Provide alternative for curl_multi_exec()

### ISSUE THREAD

**Issue by vaites** [oscarotero/Embed#325]
There are hosting providers that disables `curl_multi_exec()` function (like Dinahosting), so this library can't be used to fetch the images.

I suggest check the funcion avaliability and make sequential fetch instead of parallel...

**Comment by oscarotero** [comment]
In this case, I recommend to create a new dispatcher extending `CurlDispatcher` and overriding the `dispatchImages` method, so you can configure Embed to use the new dispatcher (https://github.com/oscarotero/Embed#the-dispatcher)

**Comment by vaites** [comment]
I solved my problem with a new dispatcher, but I also think it can be solved with the current `CurlDispatcher`. Do you think it affects so few users that it's not worth implementing it?

**Comment by oscarotero** [comment]
I've not had any issue with `curl_multi_exec()` until now, so I'm not sure if hosting disabling `curl_multi_exec()` but not `curl_exec()` is a common case.

My idea is to provide and maintain a single dispatcher that works in most cases and let users create their own implementations to meet their needs.

If that is a common issue, I can include it but if isn't, I'd create the dispatcher in the app or maybe another composer package providing this dispatcher.

**Comment by vaites** [comment]
Don't know how many hostings disable `curl_multi_exec()` (I know DigitalOcean and Dinahosting), so if there's no more request to add this feature, just forget it until the number of users looks reasonable.

**Comment by oscarotero** [comment]
I use digital ocean (the embed demo is hosted there) and never had this issue

**Comment by vaites** [comment]
Maybe just some kind of products, don't know if is the default config. Anyway, I'm the only asking for it so, let this issue closed ;)
