### ISSUE TITLE
Vimeo URLs not working on DigitalOcean servers

### ISSUE THREAD

**Issue by bendesilva** [oscarotero/Embed#326]
All Vimeo URLs going through Embed are returning "invalid URL" errors with a 403 code. This only appears to be happening for me on DigitalOcean servers, not in local development or on AWS servers. The same issue appears to be happening on your demo.

Seems an HTML captcha page is returned instead:

"You have been temporarily blocked
Pardon the inconvenience, but our servers have detected a high number of errors from your connection. To continue, please verify that you are a human"

I can CURL to Vimeo's oEmbed endpoint (https://developer.vimeo.com/api/oembed/videos) from the server in question.

Any idea where the issue may be? Does the Embed library not use Vimeo's oEmbed endpoint and just treat it like any other webpage?

**Comment by cupcakedream** [comment]
Also having this issue on Digital Ocean with Vimeo..

**Comment by zedam** [comment]
Same issue, but in VULTR (ubuntu)

**Comment by bendesilva** [comment]
Vimeo in a support ticket have advised:

> Due to widespread malicious traffic from some cloud providers, our engineers have banned blocks of those providers' IP addresses from accessing resources on vimeo.com. This has the unfortunate consequence of preventing legitimate traffic, such as users utilizing a VPN service, from accessing Vimeo. Usually a CAPTCHA prompt can be passed to grant a user temporary access; however, an issue on our end is preventing that access.

They have also mentioned that they're blocking requests from Google Cloud IP blocks, so it seems like it's widespread. They want me to provide details of my Vimeo account, use case, IP address and verification that it's static. As I use this package on a range of IP addresses for various clients it's not feasible to verify each and every one and on an ongoing basis.

I managed to work around the issues by applying a hotfix to the package on affected servers which uses the Vimeo oEmbed endpoint by adding both an "adapter" and "provider" for Vimeo. Videos embed as expected after that. Not really confident in making a PR for the changes, but it seemed a fairly simple fix, any chance we can get this updated?

**Comment by cole007** [comment]
Hi Ben 

Thanks for the update - are you able to share or PR the specific adapter/provider created/used for vimeo?

Cheers,

Cole

**Comment by bendesilva** [comment]
@cole007 See referenced pull request and my forked repo, this has fixed the issue for me on affected servers.
