### ISSUE TITLE
How to adjust video width / make it responsive.

### ISSUE THREAD

**Issue by Elenadominick** [oscarotero/Embed#331]
I embeded an vimeo URL into my Craft Section using the Plugin and it works out fine so far. 
Now I wanted to make it responsible using "entry.field.media.width" from the Plugin Documentation. 
Where and how do I have to call this term to make it work? 

Sorry, I'm a beginner and couldn't find any instructions on that. 
Thank you very much for your help.
Elena

**Comment by oscarotero** [comment]
Duplicate of https://github.com/oscarotero/Embed/issues/65
