### ISSUE TITLE
Support Twitch

### ISSUE THREAD

**Issue by onigetoc** [oscarotero/Embed#332]
Twitch video embed would be easy to add.
Url Channel: https://www.twitch.tv/twit
Url videos: https://www.twitch.tv/videos/106400740
channel regex:  `/(?:www\.|go\.)?twitch\.tv\/([a-z0-9_]+)($|\?)/`
video regex: `/(?:www\.|go\.)?twitch\.tv\/videos\/(\d+)($|\/?)/`

Channel embed: 
`<iframe src="https://player.twitch.tv/?autoplay=true&channel=CHANNEL_ID_HERE" frameborder="0" allowfullscreen="true" scrolling="no" height="378" width="620"></iframe>`

Video Embed:
`<iframe src="https://player.twitch.tv/?autoplay=true&video=vVIDEO_ID_HERE" frameborder="0" allowfullscreen="true" scrolling="no" height="378" width="620"></iframe>`

autoplay: true/false

**Comment by oscarotero** [comment]
Thanks. The new version 4.2.0 has support for Twitch embeds.
