### ISSUE TITLE
Wrongly tagged release "2.7.9"

### ISSUE THREAD

**Issue by reflexxion** [oscarotero/Embed#334]
As @derjumpy wrote in #333 there is a wrongly tagged release.

---

Could it be that you tagged the wrong commit?
1. Tag name is "2.7.9" and not "v2.7.9" as usual.
2. Commit dc1dc3c is tagged with "2.7.9" and not eb05178. dc1dc3c is the commit that is already tagged with 3.4.2.

_Originally posted by @derjumpy in https://github.com/oscarotero/Embed/pull/333#issuecomment-581922225_

**Comment by oscarotero** [comment]
Yes, sorry. I just released the 2.7.10.
In github web, seems like it's not possible to tag a commit if it does not exists in master. I did it in the command line.
