### ISSUE TITLE
Support for JSON-LD

### ISSUE THREAD

**Issue by JanPetterMG** [oscarotero/Embed#335]
I thought JSON-LD was supported years ago, but apparently it is not. Is this an bug?
https://json-ld.org/

Example
JSON-LD data at https://oscarotero.com/ is not available. See demo:
https://oscarotero.com/embed3/demo/index.php?url=https%3A%2F%2Foscarotero.com%2F

**Comment by oscarotero** [comment]
It's as `$info->linkedData` but seems like the demo does not show this value.

**Comment by JanPetterMG** [comment]
Thanks.
