### ISSUE TITLE
[Youtube]  blocked server ip when using Embed::create .

### ISSUE THREAD

**Issue by mahmoudps** [oscarotero/Embed#337]
Hi ,
my server ip  get blocked from Youtube when i use Embed::create($url);

> Fatal error: Uncaught Embed\Exceptions\InvalidUrlException: Invalid url 'https://www.youtube.com/watch?v=xxxxxxx' (Status code 429) 

but server ip can get youtube embed data from Youtube embed provider
[https://www.youtube.com/oembed?url=$url] .
can we grab the oembed data with your Embed provider directly without use curl the youtube link
before extraction it's data ?

**Comment by oscarotero** [comment]
The new version (v4.x) should work with this. If you decide to upgrade, could you test it?

**Comment by lenvanessen** [comment]
@oscarotero can a fix also be applied to the 3.* branch?

**Comment by reganlawton** [comment]
I'm on this change

**Comment by oscarotero** [comment]
In theory, the status code 429 is valid in youtube as I can see here: https://github.com/oscarotero/Embed/blob/v3.x/src/Adapters/Youtube.php#L18

**Comment by lenvanessen** [comment]
We're having it on Twitter actually

Op za 27 jun. 2020 23:29 schreef Oscar Otero <notifications@github.com>:

**Comment by oscarotero** [comment]
Could you work in a PR with a fix for twitter?
Just duplicate the Youtube adapter changing the name to Twitter, and let me know if it works

**Comment by oscarotero** [comment]
Fixed in v3.4.7
