### ISSUE TITLE
"Cannot instantiate abstract class"

### ISSUE THREAD

**Issue by drewdeakin** [oscarotero/Embed#338]
Hey!

I have installed the code via composer (using the 3.4 package as I am on PHP Version 7.3.15)

On a test page, I have the following code:

```php
  require_once ('config.php'); // includes autoload.php

  use Embed\Embed;
  $embed = new Embed();
```

But it is generating the following error:

Fatal error: Uncaught Error: Cannot instantiate abstract class Embed\Embed in /test.php:12 

Line 12 is ```$embed = new Embed();```

Are you able to help solve the error?

**Comment by oscarotero** [comment]
Hi, the `Embed` class is instantiable in 4.x version. Switch to v3.x branch to see the documentation for 3.x version: https://github.com/oscarotero/Embed/tree/v3.x

**Comment by drewdeakin** [comment]
Thanks!
