### ISSUE TITLE
No ResponseFactoryInterface detected

### ISSUE THREAD

**Issue by elshobokshy** [oscarotero/Embed#342]
When I installed the package and ran `new Embed()` in my Laravel controller I got the following error in the title. Any idea why?

In `embed\embed\src\Http\FactoryDiscovery.php:52`

**Comment by elshobokshy** [comment]
I had to use version 3.x ... But I AM using PHP 7.4.1 so I find that weird. Care to explain please?

**Comment by oscarotero** [comment]
You need to install any library implementing PSR-7.
Any of these are detected by default: https://github.com/middlewares/awesome-psr15-middlewares#psr-7-implementations

**Comment by elshobokshy** [comment]
So I need to install all of these packages in order for it to work? Why don't you add them to the packagist dependencies?

**Comment by oscarotero** [comment]
No, you have to install one of these. For example `nyholm/psr7`.
I didn't incude it because there are many options and users may be already using one.

**Comment by elshobokshy** [comment]
Oh I need to use at least ONE of them, got it. I'll be trying it later. Won't hurt to mention it in the readme ^^ Thanks mate!

**Comment by oscarotero** [comment]
It's already mentioned (in requirements) but maybe it's not clear enough.

**Comment by elshobokshy** [comment]
I installed `composer require guzzlehttp/guzzle`. Which gave me version 6.5 which is PSR7 compliant. But I still have the same error.

**Comment by elshobokshy** [comment]
I went ahead and installed 

    composer require slim/psr7

Thank you!

**Comment by tripbnb66** [comment]
consider to use "omposer require guzzlehttp/psr7" as this package is used by more users

**Comment by grandeljay** [comment]
> Why don't you add them to the packagist dependencies?

> I didn't incude it because there are many options and users may be already using one.

Isn't this the package managers (composer) job to figure out? For the sake of convenience I think it would be good if you just add one. If somebody is already using a different one, maybe they can switch it to match yours?

It just seems like an odd reason to not add a dependency as a dependency.
