### ISSUE TITLE
Extremely slow in a simple loop

### ISSUE THREAD

**Issue by elshobokshy** [oscarotero/Embed#344]
I've got in my database YouTube links?

I loop through every link in laravel blade file : 

```
@foreach($urls as $url)
    <?php $url = Embed::create($url->url); ?>
    {!! $url->code !!}
@endforeach
```

So I loop through each url, create an Embed, and then print out the code and title. EACH looping takes 1 second to finish, so if I loop through 30 items it takes 30 seconds to finish.

How can I prevent that? Is there a way to only generate the code for it to be faster? As that's the only thing I'll be needing.

Thanks!

**Comment by oscarotero** [comment]
You can use the version 4, that is much more faster and allows to create multiple embed code in parallel:

```php
$codes = $embed->getMulti(...$urls);
```

Note that v4 requires php 7.4.

**Comment by elshobokshy** [comment]
I'm wondering why `getMulti` can't take an array containing the url strings?

**Comment by oscarotero** [comment]
This is not needed. The library creates the values on demand: only in the first time you call `$url->code`, the library will get the url code.
The use of variadic `getMulti(...$urls)` instead an array is because it's more strongly typed (it ensures that all values are strings).

**Comment by AliHassan13** [comment]
@oscarotero can you please help me to speed up  using `getMulti(...$urls)`. 
here is my code 
```
 $infos = $embed->getMulti(...$urls);
        foreach ($infos as $key=> $info) {
            echo $key;
            echo $info->title;
        }
```

it's working fine get all the data i want but its take **44sec**  this is too much time.. 
how can i fix it?

**Comment by oscarotero** [comment]
`getMulti` runs all request in parallel, so it should be a lot faster. How many urls have the $urls variable?
Maybe, there are some that are specially slow. I recomend to do some testing, first with few urls (5 for example) and then incrementing the number.

**Comment by AliHassan13** [comment]
some time $urls are 24 and some time 10. 
sure i will test it first with less numbers of $urls.

**Comment by elshobokshy** [comment]
Happy to see I'm not the only one that STILL has this problem even when I started using `getMulti` ...

**Comment by garbinmarcelo** [comment]
Hi, 
I'm using v3. In that case to improve speed just by switching to v4? Or would you have any tips on how to do this? 

Thanks
