### ISSUE TITLE
Allow for alternative temporary directory path

### ISSUE THREAD

**Issue by justcaldwell** [oscarotero/Embed#345]
Fantastic library - thank you!

I'm wondering if there is a way to provide an alternative path for temporary files. Using sys_get_temp_dir() can be problematic for users in environments with restrictions that prevent them writing to system directories. Specifically, line 84 in CurlDispatcher.php:

`$cookies = str_replace('//', '/', sys_get_temp_dir().'/embed-cookies.txt');`

In our case, Drupal maintains it's own temporary directory that can be different from the one returned by sys_get_temp_dir().

**Comment by oscarotero** [comment]
Ok, good idea.
I've added the ability to pass options to the CurlClient class. For example:

```php
$client = new CurlClient();
$client->setSettings(['cookies_path' => $custom_cookies_path]);

$embed = new Embed(new Crawler($client));
```

Can you confirm this works fine before tag a new version?
Thanks.

**Comment by justcaldwell** [comment]
Thanks very much for your responsiveness. 
I just noticed that embed 4.0 requires PHP 7.4+. My Drupal dev environment only supports up to 7.3 at the moment -- as soon as I can bump it to 7.4, I'll give this a test. Apologies for the delay.
