### ISSUE TITLE
No ResponseFactoryInterface detected

### ISSUE THREAD

**Issue by EmporerElvis** [oscarotero/Embed#349]
Installed embed using
 composer require embed/embed
 
createda simple test.php 
-----------------------------
ini_set('display_errors', '1');
ini_set('display_startup_errors', '1');

include __DIR__.'/../vendor/autoload.php';

use Embed\Embed;

$embed = new Embed();

//Load any url:
$info = $embed->get('https://www.youtube.com/watch?v=PP1xn5wHtxE');

//Get content info

$info->title; //The page title
$info->description; //The page description
$info->url; //The canonical url
$info->keywords; //The page keywords

echo "hello world";
--------------------------------
received error:
Fatal error: Uncaught RuntimeException: No ResponseFactoryInterface detected in /var/www/html/vendor/embed/embed/src/Http/FactoryDiscovery.php:52 Stack trace: #0 /var/www/html/vendor/embed/embed/src/Http/CurlClient.php(21): Embed\Http\FactoryDiscovery::getResponseFactory() #1 /var/www/html/vendor/embed/embed/src/Http/Crawler.php(25): Embed\Http\CurlClient->__construct() #2 /var/www/html/vendor/embed/embed/src/Embed.php(17): Embed\Http\Crawler->__construct() #3 /var/www/html/t2/t2.php(10): Embed\Embed->__construct() #4 {main} thrown in /var/www/html/vendor/embed/embed/src/Http/FactoryDiscovery.php on line 52

i'm using PHP 7.4.3

Help would be greatly appreciated!  

Thanks for any help.
Sincerely,
Emperor Elvis

**Comment by oscarotero** [comment]
Duplicated #342
