### ISSUE TITLE
using the new embed getting error 500 ClientInterface

### ISSUE THREAD

**Issue by byndstd** [oscarotero/Embed#350]
`Exception 'Error' with message 'Interface 'Psr\Http\Client\ClientInterface' not found'`

I'm using PHP 7.4.5 , and I have curl library installed

I'm getting error on code using create and also the same if I use get
$code  = Embed::create($url, ['min_image_width' => 200, 'min_image_height' => 200]);

```
Exception 'Error' with message 'Interface 'Psr\Http\Client\ClientInterface' not found' 

in /opt/lampp/htdocs/project/vendor/embed/embed/src/Http/Crawler.php:13
```

**Comment by oscarotero** [comment]
Are you sure you have all dependencies installed?
This new version require `psr/http-client` (among others dependecies) and an implementation of a psr-18 compatible package (for example https://github.com/Nyholm/psr7)

**Comment by byndstd** [comment]
**Thank you very much for your answer**

I have installed everything on my server and now I'm getting new error for every link 
I did install everything the new error I'm getting is 

```
Exception 'RuntimeException' with message 'No ResponseFactoryInterface detected' 

in /opt/lampp/htdocs/project/vendor/embed/embed/src/Http/FactoryDiscovery.php:52
```

**Comment by oscarotero** [comment]
Yes, you need to install any library implementing this interface. If you don't know what to install, I recommend  https://github.com/Nyholm/psr7

**Comment by byndstd** [comment]
> Yes, you need to install any library implementing this interface. If you don't know what to install, I recommend https://github.com/Nyholm/psr7

Thank you so much I'm sorry I tried to install "**composer require nyholm/psr7**" but I didn't succeed
