### ISSUE TITLE
some functions are not recognized

### ISSUE THREAD

**Issue by byndstd** [oscarotero/Embed#352]
I try the to return some urls but I get 
`Call to undefined function Embed\isHttp()`
I did comment to : 
`if (!isHttp($uri)) {
                throw new InvalidArgumentException(sprintf('Uri string must use http or https scheme (%s)', $uri));
  }`

I get `Call to undefined function Embed\resolveUri()`
I did change `return resolveUri($this->uri, $uri);` to `return $this->uri`

I get 
`Call to undefined function Embed\clean()`

**Comment by oscarotero** [comment]
These functions are in this file: https://github.com/oscarotero/Embed/blob/master/src/functions.php and are loaded automatically by composer.

**Comment by byndstd** [comment]
yes I have that file but I don't know why the file is not recognized and the functions

**Comment by oscarotero** [comment]
I don't understand, it seems to work fine. What's the problem?

**Comment by byndstd** [comment]
$info->image doesn't return image path it's return object with no image link
object(Nyholm\Psr7\Uri)#187 (7) {
  ["scheme":"Nyholm\Psr7\Uri":private]=>
  string(5) "https"
  ["userInfo":"Nyholm\Psr7\Uri":private]=>
  string(0) ""
  ["host":"Nyholm\Psr7\Uri":private]=>
  string(11) "i.ytimg.com"
  ["port":"Nyholm\Psr7\Uri":private]=>
  NULL
  ["path":"Nyholm\Psr7\Uri":private]=>
  string(29) "/vi/-COiNtJBr8I/hqdefault.jpg"
  ["query":"Nyholm\Psr7\Uri":private]=>
  string(0) ""
  ["fragment":"Nyholm\Psr7\Uri":private]=>
  string(0) ""
}

**Comment by byndstd** [comment]
> I don't understand, it seems to work fine. What's the problem?

$info->image doesn't return image path I'm trying to find the images but I didn't make it work

**Comment by oscarotero** [comment]
The url values (image, url, authorUrl...) are returned in PSR-7 `UriInterface`, so you have methods like `$url->getPath()`, `$url->getHost()`, etc.

This interface includes the `__toString()` magic method, so If you want to convert this value to a string, just do `$imgString = (string) $info->image`.

**Comment by byndstd** [comment]
Yes
Thank you so much it's working 
Thank you again
