### ISSUE TITLE
YouTube title: DOMXPath::query(): Invalid XPath Context

### ISSUE THREAD

**Issue by stephanvierkant** [oscarotero/Embed#354]
I've upgraded to 4.1.1 and the example from the readme doesn't work:

```
use Embed\Embed;

$embed = new Embed();

//Load any url:
$info = $embed->get('https://www.youtube.com/watch?v=PP1xn5wHtxE');

//Get content info

$info->title; //The page title
```

I get this error:

> Warning: DOMXPath::query(): Invalid XPath Context

**Comment by stephanvierkant** [comment]
Sorry, my fault.

**Comment by chaseconey** [comment]
@stephanvierkant I seem to be running into the same issue - what did you end up doing to solve this one?

**Comment by catalinux** [comment]
I get same error for some youtube links. Is there any way we cad transform that error in exception?
