### ISSUE TITLE
Embed\Http\NetworkException (18) on Youtube video

### ISSUE THREAD

**Issue by stephanvierkant** [oscarotero/Embed#355]
On our production server, I get this error when retrieving a YouTube video:

> In CurlDispatcher.php line 143:
>                                                         
>   [Embed\Http\NetworkException (18)]                    
>   transfer closed with outstanding read data remaining  
>                                                         

However, it does work on my own laptop. Both are using curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.0.2n.

Any idea what causes this problem?

**Comment by oscarotero** [comment]
No idea.
It seems like the curl error returned is `CURLE_PARTIAL_FILE (18)` (You can see all errors here: https://curl.haxx.se/libcurl/c/libcurl-errors.html)

Maybe the reason is that, for some reason, the Content-Length header is different to the body size?

Try to ignore this error, perhaps it does not affect to fetching the data.

**Comment by stephanvierkant** [comment]
How can I ignore this error? `\Embed\Http\CurlDispatcher::exec` throws an exception.

**Comment by oscarotero** [comment]
One idea:
Edit this function: https://github.com/oscarotero/Embed/blob/master/src/Http/CurlDispatcher.php#L143

appending this, to ignore this kind of errors:

```php
if ($code === 18) {
    return;
}
```

If it works, I'll add an option to configure the dispatcher to ignore some errors.

**Comment by stephanvierkant** [comment]
Yes, that works! 

Haven't looked into it yet, but maybe the HttpClient has some options to ignore this?

**Comment by oscarotero** [comment]
Not yet, but I'll add it.

**Comment by oscarotero** [comment]
I just added this change. Could you please test it before release a new version?
Now, you can configure the CurlClient to ignore some or all errors:

```php
$client = new CurlClient();
$client->setSettings([
    'ignored_errors' => [18] // Ignore errors of code 18
]);

$client->setSettings([
    'ignored_errors' => true // Ignore all errors
]);
```

Let me know if it works fine. Thanks!

**Comment by oscarotero** [comment]
Version 4.2.0 released including this new option.
