### ISSUE TITLE
Some Embeds Fail with JsonLdException

### ISSUE THREAD

**Issue by bobdercole** [oscarotero/Embed#356]
Hi,

I noticed that some embeds, that were previously working, are now failing with an uncaught exception. 

For example https://vimeo.com/ results in this:

(ML\\JsonLD\\Exception\\JsonLdException(code: loading remote context failed): Loading http://schema.org failed at /application/vendor/ml/json-ld/Processor.php:1752)
(ML\\JsonLD\\Exception\\JsonLdException(code: loading document failed): Invalid media type (near \"text/html\") at /application/vendor/ml/json-ld/FileGetContentsLoader.php:105)

The demo shows the same issue:

![image](https://user-images.githubusercontent.com/3331705/82467478-b40d6900-9a8f-11ea-84f6-281626030e77.png)

**Comment by oscarotero** [comment]
Ok, I'll take a look. Thanks for let me know.

**Comment by oscarotero** [comment]
I just commited a fix for this. Could you please test it before tag a new version?
Thanks

**Comment by bobdercole** [comment]
That seems to work. Thank you!

**Comment by oscarotero** [comment]
Version 4.2.0 released including this fix.
