### ISSUE TITLE
Instagram embed returning login

### ISSUE THREAD

**Issue by amjad-eremnews** [oscarotero/Embed#359]
Instagram is returning login content on production server, while on local embeds is working fine.

**Comment by amjad-eremnews** [comment]
library version version is 3.x

**Comment by oscarotero** [comment]
Yes, this is a duplicate of https://github.com/oscarotero/Embed/issues/357. 
It's a change from instagram, and I'm thinking in the best way to solve it.

**Comment by oscarotero** [comment]
Released a workaround in 3.4.5

**Comment by amjad-eremnews** [comment]
Awesome, it is fixed. verified!
Many thanks
