### ISSUE TITLE
Embed 4.x :  Server Language

### ISSUE THREAD

**Issue by MatteoNet** [oscarotero/Embed#360]
Hi Oscarotero,
I noticed that Embed returns Facebook results in the language of the location where the server is hosted. I tried to enter in the settings : CURLOPT_HTTPHEADER' => ['Accept-Language: it-IT'] but they came back in French: "Multiplayer.it. 310 797 J’aime · 17 892 en parlent." 
Here is the code I used:

```
use Embed\Embed;
use Embeded\Http\Crawler;
use EmbedpcurlClient;

$client = new CurlClient();
$client->setSettings([)
    CURLOPT_HTTPHEADER => ['Accept-Language: it-IT'],
]);

$embed = new Embed(new Crawler($client));
$result = $embed->get('https://facebook.com/multiplayer.it');
```

**P.S.** : You did a great job in this amazing script. Thank you Oscarotero :+1:

**Comment by oscarotero** [comment]
To send custom headers to the request, you have to do this:

```php
$embed = new Embed();

$embed->getCrawler()->addDefaultHeaders(['Accept-Language: it-IT']);
```

**Comment by MatteoNet** [comment]
I try this:

```
$embed = new Embed();

$embed->getCrawler()->addDefaultHeaders(['Accept-Language: it-IT']);
$result = $embed->get('https://facebook.com/multiplayer.it');
var_dump($result->description);
```
but i got this error:

`Header name must be an RFC 7230 compatible string.`

**Comment by oscarotero** [comment]
Sorry, my fault. This should work:

```php
$embed->getCrawler()->addDefaultHeaders(['Accept-Language' => 'it-IT']);
```

**Comment by MatteoNet** [comment]
Yes, your fix work, but i have the same issue, embed return came back in French: 
"Multiplayer.it. 310 797 J’aime · 17 892 en parlent." 
:cry:

**Comment by oscarotero** [comment]
I had some similar issues with youtube (in local returns spanish text, in my server english). There's nothing I can do, because I suspect it's in facebook side. Maybe they detect your server is in France.

**Comment by garbinmarcelo** [comment]
> I had some similar issues with youtube (in local returns spanish text, in my server english). There's nothing I can do, because I suspect it's in facebook side. Maybe they detect your server is in France.

I know this is an old post, but has there been any progress on this? On my local machine it is in pt-BR, but on the server the description that comes from YouTube is in English and is not the same as the one in the video.
