### ISSUE TITLE
Arabic / Persian bug

### ISSUE THREAD

**Issue by pajuhaan** [oscarotero/Embed#366]
This function removes all pure Persian and Arabic characters:
function clean(string $value, bool $allowHTML = false): ?string
{
    $value = trim($value);

    **//Ignore empty texts or with no regular characters
    if ($value === '' || !preg_match('/\w/', $value)) {
        return null;
    }**

**Comment by oscarotero** [comment]
Thanks for notify this.
The purpose of this function is avoid values like `--` that I found in some cases but I can remove it, unless there's another way to detect regular characters of any alphabet. Any idea?

**Comment by oscarotero** [comment]
Fixed in 4.2.3
