### ISSUE TITLE
Discourse-style (onebox) embed of (website) URLs?

### ISSUE THREAD

**Issue by strarsis** [oscarotero/Embed#371]
When a website URL is pasted into a Discourse post, often a title, description text, and a thumbnail is shown (using [onebox](https://github.com/discourse/onebox)).
WordPress seems to supports this very well, with a featured image (and description).
However, when I use such an URL with Embed, there is currently no `code` to use to show the actual "info box".

**Comment by oscarotero** [comment]
I'm not sure what do you want. Can you give an example?

**Comment by strarsis** [comment]
@oscarotero: When you insert an URL into a Discourse powered forum post, the page behind the URL is shown in a box with title, text, icon, etc. Embed works nicely with popular OEmbed providers like YouTube, however, it doesn't work with e.g. a WordPress page, though those pages offer a title, text, icon, etc for embedding.

**Comment by oscarotero** [comment]
This library gets the title, description, icon etc of any webpage, so you can generate the same kind of box with all these stuff. The embed code is returned only if the site provides it (for example, implements an OEmbed api), but you can use the other data to generate your own fallback embed.

**Comment by strarsis** [comment]
@oscarotero: This is great! Could you add a default template/code to this library so one can easily get simple HTML for a onebox-like output of these website metadata? I would really love to use this library not only for embedding YouTube videos and other services, but also to have a "smart"/nice box for a website link.

**Comment by oscarotero** [comment]
Each project have its own requirements and styles, so there's no a default template. The scope of this library is only getting the data.

**Comment by strarsis** [comment]
@oscarotero: Well, I can make a simple template then and populate it using the extracted data. Thanks.
