### ISSUE TITLE
Pass a class to the iframe

### ISSUE THREAD

**Issue by tommysvr** [oscarotero/Embed#373]
Great library 👍🏻 👍🏻

Is it possible to pass a class to the iframe, like this?

```
<iframe class="embed-responsive-item" src="..."></iframe>
```

**Comment by oscarotero** [comment]
No, it's not possible, but you can insert the embed code in a div with the class:

```php
<div class="embed-code"><?= $info->code ?></div>
```

An then modify the iframe with css

```css
.embed-code iframe {
    /* ... */
}
```
