### ISSUE TITLE
Youtube Embed Code NULL

### ISSUE THREAD

**Issue by arif-medialinker** [oscarotero/Embed#383]
Hi, 
Few Days ago my Embed code not fetching Youtube Code, it alwasy return NULL. I tested Vimo links, and CNN boht Links return Code as iFrame, but Youtube link not returning iFrame code.

My Code is this
$url = 'https://www.youtube.com/watch?v=FPBO4xIil38';
$info = Embed::create($url);
            $link_data['title'] = $info->title;
            $link_data['code'] = $info->code;    --> has NULL Value
            $link_data['url'] = $info->url;
            if($this->url_exists($info->image)){
                $link_data['image'] = $info->image;
            }
            return response()->json(['link_data' => $link_data]);

PHP Version is 7.3
Embed Version is ^3.4
Laravel Version is 6.6.1

**Comment by mcaskill** [comment]
Hi. Are you still having this issue?

This is the call the Embed library makes internally:

> https://www.youtube.com/oembed?url=http%3A//youtube.com/watch%3Fv%3DFPBO4xIil38&format=json

And the response contains the `html` key and value you are looking for.

I'm also having this issue with Embed v3.4.8 but in my scenario, the oEmbed API responds with a 401 Unauthorized. The video is unlisted, so it probably has embedding disabled.

**Comment by arif-medialinker** [comment]
Thanks for reply, and I am not having this issue anymore, it was the having issue with strtolower on URL,  and Youtube link is Case sensitive, I removed strtolower from youtube URL, and its works fine after that.
