### ISSUE TITLE
Twitch would be easy to do

### ISSUE THREAD

**Issue by onigetoc** [oscarotero/Embed#384]
URL with ID https://www.twitch.tv/videos/740399376
```
<div id="twitch-embed"></div>
<!-- Load the Twitch embed script -->
<script src="https://player.twitch.tv/js/embed/v1.js"></script>
<!-- Create a Twitch.Player object. This will render within the placeholder div -->
<script type="text/javascript">
  new Twitch.Player("twitch-embed", {
    video: "740399376"
  });
```
</script>

**Comment by oscarotero** [comment]
Thanks, but I think it's better to use an iframe instead load and execute inline javascript, to avoid CORS errors or loading several videos in the same page.

**Comment by oscarotero** [comment]
Ok, I see that the iframe solution does not work anymore (https://oscarotero.com/embed/demo/index.php?url=https%3A%2F%2Fwww.twitch.tv%2Fvideos%2F740399376)

Do you want to work on a Pull request?

**Comment by onigetoc** [comment]
I can't since i work on your V2 version because i do not have Composer on my shared server to install V3

**Comment by oscarotero** [comment]
Ok, I understand. No problem, thanks!
