### ISSUE TITLE
IDE supports @property

### ISSUE THREAD

**Issue by rentalhost** [oscarotero/Embed#387]
Hello!

Some properties could be accessed via magic `__get()`, but actually are a private property. It was done probabily to be readonly properties, but it affects IDE to recognize as a valid property.

![image](https://user-images.githubusercontent.com/421851/93941454-df85b600-fd04-11ea-8904-e3cd35d25eba.png)

So I suggests to create `@property-read` declaration to identify it as public acessibility but readonly.

Example:

![image](https://user-images.githubusercontent.com/421851/93941561-1c51ad00-fd05-11ea-902b-6e230c3dc071.png)

So:

![image](https://user-images.githubusercontent.com/421851/93941592-2c698c80-fd05-11ea-9dec-b9ad4fe974b0.png)

It is open to PR? If so, I would like to make it tomorrow.

**Comment by oscarotero** [comment]
Fair enough. Thanks!
