### ISSUE TITLE
PHP8 incompatibility

### ISSUE THREAD

**Issue by strarsis** [oscarotero/Embed#393]
@oscarotero: `Embed` doesn't seem to be compatible with PHP8:
````
Parse error: syntax error, unexpected token "match", expecting "(" in [...]/vendor/embed/embed/src/functions.php on line 119
````

https://github.com/oscarotero/Embed/blob/45aaeae8636b8a9d4056c8b5f7bb9aebc1b81557/src/functions.php#L119

Edit: `match` is a reserved keyword in PHP8.x for [match expressions](https://php.watch/versions/8.0/match-expression), hence the parse error. When the `match` function is renamed to something else, e.g. `match2`, the file parses without errors.

PR ready: https://github.com/oscarotero/Embed/pull/394

Note: Travis CI appears to support PHP 8 now, it may be a nice idea to add PHP 8 to `.travis.yml` so embed is automatically tested on it.

**Comment by oscarotero** [comment]
Hi, thanks for the PR, it's merged.
Seems like TravisCI fails installing php8 https://travis-ci.org/github/oscarotero/Embed/jobs/737369064

**Comment by strarsis** [comment]
@oscarotero: Apparently Travis CI treats PHP 8 currently as 'nightly' build, e.g. https://github.com/doctrine/instantiator/pull/67/files#diff-6ac3f79fc25d95cd1e3d51da53a4b21b939437392578a35ae8cd6d5366ca5485R10.

**Comment by oscarotero** [comment]
Ah, ok. PHP8 is not released yet (stable version).

**Comment by oscarotero** [comment]
Released this change in https://github.com/oscarotero/Embed/releases/tag/v4.3.0
