### ISSUE TITLE
v3.x not installable on PHP 8

### ISSUE THREAD

**Issue by I-Valchev** [oscarotero/Embed#407]
Hi, I see you so nicely added PHP 8 support for ^3.4 in #395, but I can't seem to install it:

```
    - embed/embed[v3.4.0, ..., v3.x-dev] require php ^5.6|^7.0 -> your php version (8.0.0) does not satisfy that requirement.
    - Root composer.json requires embed/embed ^3.4 -> satisfiable by embed/embed[v3.4.0, ..., v3.x-dev].
```

Is that something that can be fixed? Thanks.

**Comment by oscarotero** [comment]
I've released a new version that fixes this issue. Thanks for let me know
