### ISSUE TITLE
Embed codes for video URLs

### ISSUE THREAD

**Issue by digilist** [oscarotero/Embed#412]
Thank you for this great library. I have been using it for a long time now and I am very happy with it.

With version 3 it was possible to get embed codes for videos with a direct link (e.g. http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4), but this does not work anymore with version 4.

```
<video controls><source src="http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4"></video>
```

With version 4 I get a curl timeout exception. I do not think it is related to the endpoint, I tested it with various sources. I rather think it is related to the downloading of the response body which is probably not necessary here. I think in version 3 it stopped if a binary response was detected.

After some debugging I noticed in the changelog that support for files was removed. What was the reason to drop this? Would it be possible to add this again? And if it was to complex or something, would it be possible to throw an Exception when this is tried? Took me a bit to figure this out 🙂

**Comment by oscarotero** [comment]
The main reason to remove the support for binary files is that the version 4.x uses PSR (7, 17 and 18) standards to handle the https requests and it's a bit complex to implement this feature (but I'm open to Pull request if anyone want to work on it).
The most easy way to handle this is by checking the url extension before use Embed. For example:

```php
$ext = pathinfo($url, PATHINFO_EXTENSION);

switch ($ext) {
    case "mp4":
    case "mpeg":
    case "mov":
    case "webm":
    case "ogv":
        return "<video controls src='$url'></video>;
    case "mp3":
    case "ogg":
        return "<audio controls src='$url'></audio>;
    default:
        return $embed->get($url);
}
```

**Comment by digilist** [comment]
I see, that makes sense. Thank you for your quick answer. I will try to find some time to further look into this. Checking the extension is a good start.

**Comment by digilist** [comment]
I opened a PR for this. Not sure if this is too easy or is missing something though
