### ISSUE TITLE
Some Facebook urls redirect to the login page

### ISSUE THREAD

**Issue by lozeone** [oscarotero/Embed#415]
I'm seeing Some facebook urls that are redirecting to the login page and then returning a "invalid parameter" error from FB, Because you cant embed the login page.

Ones in this old format tend to work
https://www.facebook.com/permalink.php?story_fbid={post-id}

While the same one using the current format does not.
https://www.facebook.com/*/posts/{post-id}

To fix this I added a pattern for "www.facebook.com/login/*" to the Redirects.php class and get the intended url from the "next" parameter. This resolves the issue for me.

**Comment by lozeone** [comment]
This is for v3.x

**Comment by oscarotero** [comment]
Ok, merged and released. Thanks

**Comment by lozeone** [comment]
Great. thank you!
