### ISSUE TITLE
Twitter Timelines

### ISSUE THREAD

**Issue by joeworkman** [oscarotero/Embed#425]
I used to be able to get embeds for twitter user timelines. This no longer seems possible. Does anyone else able to do this with either v3 or v4?

URLs to individual tweets do still work.

**Comment by oscarotero** [comment]
I remember that twitter removes the abilityt to embed timelines automatically some time ago. The only way to embed them is manually, using the steps here: https://help.twitter.com/en/using-twitter/embed-twitter-feed
