### ISSUE TITLE
Facebook embed stopped working ^3.4

### ISSUE THREAD

**Issue by amjad-emfzlcc** [oscarotero/Embed#426]
Facebook embed is not working on library version ^3.4.

**Comment by oscarotero** [comment]
You need an API key.

**Comment by amjad-emfzlcc** [comment]
@oscarotero thanks for your response. API key means access token?

**Comment by oscarotero** [comment]
Yes. Facebook/Ingragram changed this. See https://github.com/oscarotero/Embed/issues/392
