### ISSUE TITLE
can be used with laravel?

### ISSUE THREAD

**Issue by bertux77** [oscarotero/Embed#431]
This is probably a very stupid question but I want to make sure before I start researching. 
Can it be used with laravel? Thanks

**Comment by oscarotero** [comment]
I'm not a Laravel guy but I guess you can use any PHP package in Laravel.
The only difference is that this package uses PSR-7, PSR-17 and PSR-18 standards for everything related with HTTP (Laravel doesn't follow these standards), but I don't think it is conflictive.

**Comment by MrHexagon** [comment]
Yes, I use it with laravel
