### ISSUE TITLE
Facebook video embeds don't work when using API token

### ISSUE THREAD

**Issue by DieterHolvoet** [oscarotero/Embed#432]
A call is made to `https://graph.facebook.com/v8.0/oembed_url` when fetching OEmbed information for a Facebook video [[source](https://github.com/oscarotero/Embed/blob/master/src/Adapters/Facebook/OEmbed.php)]. This endpoint does not exist, the correct endpoint is `/oembed_video` [[source](https://developers.facebook.com/docs/graph-api/reference/oembed-video/)].

**Comment by oscarotero** [comment]
Good catch. Thank you!
