### ISSUE TITLE
YouTube redirects to cookie wall embed v3.x - part 2

### ISSUE THREAD

**Issue by qrazi** [oscarotero/Embed#441]
I am aware there were 4 issues or so opened recently with this issue. I also saw the commit that was supposed to fix it. I still have the issue, with a video that is allowed to be embedded: https://oscarotero.com/embed3/demo/index.php?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DseeEkWpFXnk

I'm still investigating more as to why this is happening, but opening issue already.

Test result:
![image](https://user-images.githubusercontent.com/7550540/115420464-7236f680-a1fb-11eb-9f97-0386cd6bfc72.png)

Embed option in sharing:
![image](https://user-images.githubusercontent.com/7550540/115420552-85e25d00-a1fb-11eb-867b-e7af89e45fb4.png)

**Comment by oscarotero** [comment]
The v3 demo in my server (https://oscarotero.com/embed3/demo/index.php) wasn't the last version (I have to update it manually). I just updated it and seems to work fine:
https://oscarotero.com/embed3/demo/index.php?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DseeEkWpFXnk

**Comment by qrazi** [comment]
Ah, yes, I see. 

OK, background, I'm using Craft CMS with https://github.com/spicywebau/craft-embedded-assets plugin. Versions:
craftcms/cms: 3.6.11.2
spicyweb/craft-embedded-assets: 2.5.3
embed/embed: v3.4.15

https://github.com/oscarotero/Embed/blob/v3.4.15/src/Embed.php#L102 return a YouTube Adapter with the consent url:
![image](https://user-images.githubusercontent.com/7550540/115433092-6f420300-a207-11eb-94ec-51959762cbac.png)

As far as I can tell, this is because https://github.com/oscarotero/Embed/blob/v3.4.15/src/Embed.php#L90 checks the initial response, and https://github.com/oscarotero/Embed/blob/v3.4.15/src/Embed.php#L91 is also still set to the consent url.

I'm going to try and see if I can put this in a test to showcase (or find out what I'm doing wrong.. :sweat_smile: )

**Comment by mathiasselleslach** [comment]
I am having the same issue here as well.
So there seems to be a usecase left in V3 that still returns the consent url.

**Comment by qrazi** [comment]
Yes, so in my case the package that uses Embed, uses `$adapter->url`. Down the line this and other info is used to create a player by our website. Because `$adapter->url` (and `$adapter->response()`) is still set to the initial consent URL, it fails now for us.

I'm just not a 100% sure that `$adapter->url` should reflect the original URL?

On a side note, I'm getting quite a few errors when running the tests, will try and PR that too for the 3.x branch

**Comment by qrazi** [comment]
So I noticed that when I used curl on the CLI, or `file_get_contents()`, the response HTML does not contain any consent banner, but seems to be the actual video page.

I traced it back now to the CurlDispatcher setting a cookie jar. When I comment out https://github.com/oscarotero/Embed/blob/v3.x/src/Http/CurlDispatcher.php#L50 till https://github.com/oscarotero/Embed/blob/v3.x/src/Http/CurlDispatcher.php#L63 the response seems to be the video page, not the consent page. 

Hypothesis; when YouTube detects cookies can be set, and IP is coming from EU, consent screen is presented. I'm also assuming cookies are used for a reason and I can't just remove that?

Weird is also that I think I see in the 4.x branch cookies are used as well, but the 4.x demo does show the correct URL in the demo: https://oscarotero.com/embed/demo/index.php?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DseeEkWpFXnk 
![image](https://user-images.githubusercontent.com/7550540/115513023-e8327080-a282-11eb-9ecf-8ee5b960199e.png)

**Comment by qrazi** [comment]
@oscarotero quick ping, not at all meant in a demanding way; what would be a rough timeline for looking at PR #442 , and are you still accepting PRs on the v3.x branch? Is there something I can do to make it easier to check the PR?

**Comment by oscarotero** [comment]
@qrazi I'm not actively maintaining the v3.x branch but accepts PR from people using it. I've merged it and released 3.4.16.
Sorry for being late.

**Comment by qrazi** [comment]
Many thanks! And no need to apologize! :)
