### ISSUE TITLE
Cannot instantiate abstract class Embed\Embed 

### ISSUE THREAD

**Issue by realodix** [oscarotero/Embed#443]
https://github.com/realodix/urlhub/pull/754 [@8595849](https://github.com/realodix/urlhub/pull/754/commits/85958498fbda83082f1f1e18ab95d369c5f6b344)

<details>
  <summary>Screenshot</summary>
  
  ![Screenshot 2021-04-25 at 03-30-25 🧨 Cannot instantiate abstract class Embed Embed](https://user-images.githubusercontent.com/1314456/115972090-a2252780-a576-11eb-9b3b-afa3e31fccd4.png)
</details>

**Comment by oscarotero** [comment]
`Embed\Embed` is not an abstrac class in v4, so I guess you're running v3.
