### ISSUE TITLE
 YouTube redirects to cookie wall embed v3.x - part 3

### ISSUE THREAD

**Issue by qrazi** [oscarotero/Embed#447]
Hi @oscarotero, thanks again for merging my previous PR. I made a mistake however, as noted by https://github.com/spicywebau/craft-embedded-assets/issues/170#issuecomment-834398787. So I just added another PR to the v3 branch. I understand you're not actively maintaining it, but I would be grateful if you could humor me again... :sweat_smile: 

The mistake is, as seen in #446 , not forcing Url to a string type. `$url` is not set by default on a Adapter. When calling `->url`, it will use magic getters to run `getUrl()`. `getUrl()` defines that a string should be returned. Therefor consumers of the package should also assume the type is a string, and I created this PR, instead of a PR on the consuming project (and do the casting there).

I missed this in my initial PR because the testsuite does force the type casting and therefor doesn't fail on this property. I didn't notice it with manual testing either, since I was looking at a cached result (so in the context of Craft CMS).

#446 should be correct considering all this I think.

**Comment by oscarotero** [comment]
Ok, merged and released 3.4.17
