### ISSUE TITLE
How to get $info->image for an image link?

### ISSUE THREAD

**Issue by tnaseem** [oscarotero/Embed#452]
I've just come back to this package after a few years(!). I was using v2.7.

I've just updated to the latest and got most things working. However, although the image links get the HTML, $info->image is empty.

I was using this as a direct link to the image for my thumbnails. Is there any way I can do this with the new version?

Example image I was grabbing:
https://i.guim.co.uk/img/media/6cf196bbf37677d3e9624e6365ce282b6b451a73/0_236_5184_3110/master/5184.jpg?width=1920&quality=85&auto=format&fit=max&s=8a1a9a919bc99863c8677ac51e794bc9

**Comment by tnaseem** [comment]
As a side note, I did have a config array I used to send to the original Embed::create() call:
```
$info = Embed::create($url, $config);
```

**Comment by oscarotero** [comment]
The new version no longer collect all images in the page, just return the image defined by the webpage in some `<meta>` tags etc. You have more info here: https://github.com/oscarotero/Embed/issues/343

And about the `$info->image` for direct links to images, good point. I just release a new version fixing this.
Thanks!
