### ISSUE TITLE
New Twitch embed code

### ISSUE THREAD

**Issue by onigetoc** [oscarotero/Embed#455]
Now Twitch need the website host url in the iframe code.

`<iframe src="https://player.twitch.tv/?channel=chess&parent=www.MYWEBSITEURL.com" frameborder="0" allowfullscreen="true" scrolling="no" height="378" width="620"></iframe>`

I did a php to get the url like:
```
$siteurl = "http://" . $_SERVER['SERVER_NAME'] . $_SERVER['REQUEST_URI']; 

domain($siteurl);

function domain($url){
    $url = str_replace("www.","",$url);
    $remove = array("http://","https://");
    return str_replace($remove,"",$url);
}
```

**Comment by oscarotero** [comment]
There's the configuration option `twitch:parent` for that (See [Settings documentation](https://github.com/oscarotero/Embed#settings))
