### ISSUE TITLE
Custom Detector in custom Adapter

### ISSUE THREAD

**Issue by nicolas-t** [oscarotero/Embed#457]
Hello,

I'm writing a custom Adapter for twitter links, it uses the twitter API.
I'm able to set `$embed->title` to be the content of the tweet, everything is fine on this side.

But I'd also like to extract all the images of the tweet in `$embed->images`

I've done it by reproducing the code in the Wikipedia Adapter.

Here is a simplified version of what I'm using:

**Extractor :** 
```php
<?php
namespace App\Embed\Adapters\Twitter;

use Embed\Extractor as Base;
use Embed\Http\Crawler;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\UriInterface;

class Extractor extends Base
{
    private Api $api;

    public function __construct(UriInterface $uri, RequestInterface $request, ResponseInterface $response, Crawler $crawler)
    {
        parent::__construct($uri, $request, $response, $crawler);

        $this->title = new Detectors\Title($this);
        $this->images = new Detectors\Images($this);
    }

    public function getApi(): Api
    {
        return $this->api;
    }
}
```

**Title Detector :** 
```php
<?php
namespace App\Embed\Adapters\Twitter\Detectors;

use Embed\Detectors\Title as Detector;

class Title extends Detector
{
    public function detect(): ?string
    {
        return 'baz';
    }
}

```
**Images Detector :** 
```php
<?php
namespace App\Embed\Adapters\Twitter\Detectors;

use Embed\Detectors\Detector;

class Images extends Detector
{
    public function detect(): ?array
    {
        return ['foo', 'bar'];
    }
}
```

**Main function :** 
```php
$instance = new Embed();

$factory = $instance->getExtractorFactory();
$factory->addAdapter('twitter.com', \App\Embed\Adapters\Twitter\Extractor::class);
$info = $instance->get('https://twitter.com/burtoo/status/1439692411806969857');

var_dump($info->title); // works well, returns 'baz'
var_dump($info->images); // doesn't work, returns an instance of App\Embed\Adapters\Twitter\Detectors\Images
```

----

When doing `$info->images` I'm expecting to get the array `['foo', 'bar']` but I'm in fact getting an instance of : 
`App\Embed\Adapters\Twitter\Detectors\Images`
![image](https://user-images.githubusercontent.com/1765930/135298500-f6448cac-84a6-499b-80a9-8e1c2e6cefee.png)
_(truncated for readability)_

It seems that my `detect` function is never called.

Thanks for your help.

**Comment by oscarotero** [comment]
Hi.
`$info->images` is not available in the latest version of Embed, only `$info->image` is.

You can register new detectors, using [`ExtractorFactory::addDetector()` method](https://github.com/oscarotero/Embed/blob/master/src/ExtractorFactory.php#L69). Adding this line, it should work:

```php
$factory->addDetector('images', \App\Embed\Adapters\Twitter\Detectors\Images::class);
```

If you only want to have this detector for twitter, register it in the Twitter Adapter, instead of the ExtractorFactory. For example:

```php
class Extractor extends Base
{
    private Api $api;

    public function __construct(UriInterface $uri, RequestInterface $request, ResponseInterface $response, Crawler $crawler)
    {
        parent::__construct($uri, $request, $response, $crawler);

        $this->title = new Detectors\Title($this);
        $this->addDetector('images', Detectors\Images::class);
    }

    public function getApi(): Api
    {
        return $this->api;
    }
}
```

**Comment by nicolas-t** [comment]
Thanks for the quick answer !

If I modify the main function like this : 

```php
$instance = new Embed();

$factory = $instance->getExtractorFactory();
$factory->addDetector('images', \App\Embed\Adapters\Twitter\Detectors\Images::class);
$factory->addAdapter('twitter.com', \App\Embed\Adapters\Twitter\Extractor::class);
$info = $instance->get('https://twitter.com/burtoo/status/1439692411806969857');

var_dump($info->title); // works well, returns 'baz'
var_dump($info->images); // doesn't work, returns an instance of App\Embed\Adapters\Twitter\Detectors\Images
```

I get the same behaviour `$info->images` returns an instance of `App\Embed\Adapters\Twitter\Detectors\Images`


If I modify the extractor like you suggested with : 
`$this->addDetector('images', Detectors\Images::class);`  or
`$this->addDetector('images', \App\Embed\Detectors\Images::class);` 

I get this error : 
```
TypeError: Argument 2 passed to Embed\Extractor::addDetector() must be an instance of Embed\Detectors\Detector, string given, called in app/Embed/Adapters/Twitter/Extractor.php on line 24
```

Indeed if I dump the value of `$detector` here : 
https://github.com/oscarotero/Embed/blob/673cc5b4cef76d8108bccd0886d520e503f5557d/src/Extractor.php#L138

I get : `"App\Embed\Detectors\Images"`  (as a string)


I feel like I'm doing something stupid somewhere, but can't find where yet.

**Comment by oscarotero** [comment]
Ok, this is correct:

```php
$factory = $instance->getExtractorFactory();
$factory->addDetector('images', \App\Embed\Adapters\Twitter\Detectors\Images::class);
```

Because, when a new extractor is generated (your `$info` variable), the factory register this new detector (as [you can see here](https://github.com/oscarotero/Embed/blob/master/src/ExtractorFactory.php#L57)).

The way a Extractor returns the value from a detector is using the magic method `__get()` [here](https://github.com/oscarotero/Embed/blob/master/src/Extractor.php#L127), so make sure that the variable `$info->images` is not public, so this method won't be executed.

**Comment by nicolas-t** [comment]
Thanks!

Now it works with the private property `images` and `$factory->addDetector('images', \App\Embed\Adapters\Twitter\Detectors\Images::class);`.

The trick is, in my projet I also have a generic `images` detector for standard links just like with embed3 :
- Generic image detector : ` \App\Embed\Detectors\Images::class`
- Twitter image detector: ` \App\Embed\Adapters\Twitter\Detectors\Images::class`

I want to use the generic one on every links, and the twitter one only on twitter links.

What would be the right way of doing it ? 

I've tried : 
`$factory->addDetector('images', \App\Embed\Detectors\Images::class);`
 along with extending the generic detector: 
```php
<?php
// Twitter Images Detector

namespace App\Embed\Adapters\Twitter\Detectors;

use \App\Embed\Detectors\Images as Detector;

class Images extends Detector
{
    public function detect(): ?array
    {
        // ...
```

But It ignores the twitter detector and only returns the result of the generic extractor.

**Comment by nicolas-t** [comment]
Hello,

I've ended up using a condition like this: 

```php
$url = 'https://twitter.com/burtoo/status/1439692411806969857/';
$domain = parse_url($url, PHP_URL_HOST);

$instance = new Embed();
$factory = $instance->getExtractorFactory();

if ($domain === 'twitter.com') {
    $factory->addAdapter('twitter.com', \App\Embed\Adapters\Twitter\Extractor::class);
} else {
    $factory->addDetector('images', \App\Embed\Detectors\Images::class);
}

$info = $instance->get($url);
```
But it won't work with a short url redirecting to twitter for example.


Could you share an example of how to use a generic custom Detector (images) and how to _override_ it in a custom Adapter ?

Thanks

**Comment by oscarotero** [comment]
Mmm, seems like it's not possible right now to define a generic custom detector and override it in some adapters. Your code is right but yeah, it doesn't support redirects.

This feature could be implemented but I'm very busy right now, so I don't have time in this week to fix it. If you want to work on a pull request to this, I'd happy to review and merge it.

Some quick notes:

The Extractor is created here: https://github.com/oscarotero/Embed/blob/master/src/ExtractorFactory.php#L53 As you can see, it first creates the Extractor instance an then add the customDetectors.

A solution could be that a Adapter could expose its own custom detectors. For example in your twitter Adapter, it could have the `getDetectors()` method:

```php
// Twitter/Extractor.php

class Extractor extends Base
{
    public getDetectors(): array
    {
        return [
            'images' => new Images($this),
        ]
    }
}
```

Now, in the Extractor factory, (here: https://github.com/oscarotero/Embed/blob/master/src/ExtractorFactory.php#L41) just need to add the following code at the end of the `createExtractor` function:

```php
public function createExtractor(UriInterface $uri, RequestInterface $request, ResponseInterface $response, Crawler $crawler): Extractor
{
    $host = $uri->getHost();
    $class = $this->default;

    foreach ($this->adapters as $adapterHost => $adapter) {
        if (substr($host, -strlen($adapterHost)) === $adapterHost) {
            $class = $adapter;
            break;
        }
    }

    /** @var Extractor $extractor */
    $extractor = new $class($uri, $request, $response, $crawler);
    $extractor->setSettings($this->settings);

    foreach ($this->customDetectors as $name => $detector) {
        $extractor->addDetector($name, new $detector($extractor));
    }

    // THE NEW CODE TO ADD
    foreach ($extractor->getDetectors() as $name => $detector) {
        $extractor->addDetector($name, $detector);
    }

    return $extractor;
}
```

Now the detectors provided by the adapter should override the global detectors. What do you think?

---

If you don't want to work in this pull request, no problem. As a temporary workaround, you can create a custom `ExtractorFactory` extending the default and do something like this:

```php
class CustomExtractorFactory extends ExtractorFactory
{
    public function createExtractor(
        UriInterface $uri,
        RequestInterface $request,
        ResponseInterface $response,
        Crawler $crawler
    ): Extractor {
        $extractor = parent::createExtractor($uri, $request, $response, $crawler);
        $host = $uri->getHost();

        if ($host === 'twitter.com') {
            $extractor->addDetector("images", new \App\Embed\Adapters\Twitter\Extractor($extractor));
        }
    }
}
```

**Comment by oscarotero** [comment]
The new version (v4.3.5) includes a new way to register custom detectors, compatible with your needs. See the current adapters as a example: https://github.com/oscarotero/Embed/blob/master/src/Adapters/Archive/Extractor.php#L17

Closing this.
