### ISSUE TITLE
Headers not sent properly

### ISSUE THREAD

**Issue by dftd** [oscarotero/Embed#466]
Headers aren't properly added to curl when making a request.

A header array passed to `curl_setopt` is associative, like this: `["Cache-Control"] => "max-age=0" `.

But it should be a regular indexed array that looks like this: `[0] => "Cache-Control: max-age=0"`.

Not sure did I use the proper terms but I think you can understand me.

**Comment by oscarotero** [comment]
Understood. Thanks for the PR!
