### ISSUE TITLE
Use of cache

### ISSUE THREAD

**Issue by grandeljay** [oscarotero/Embed#471]
Hi,

I am using this for my [wishlist platform](https://github.com/grandeljay/wishthis) and noticed it takes very long to load, especially with a handful of products.

Is there a way to use cache?

Thanks
Jay

**Comment by oscarotero** [comment]
The purpose of this library is just get the info of the pages but not cache. Yrn ou need another library for that and only use Embed if the url isn't already cached. Example:

```php
if ($myCache->has($url)) {
    return $myCache->get($url);
} else {
    $embed = new Embed();
    $info = $embed->get($url);
    $myCache->set($url, $info);
    return $info;
}

```

**Comment by grandeljay** [comment]
Thanks, I'll make my own caching then.

I would consider it a great feature for this library though too. If you have a list, I would love to see this there.

Best
Jay

**Comment by grandeljay** [comment]
So I tried saving the Extractor response in a file via [serialize](https://www.php.net/manual/en/function.serialize.php) and noticed a bunch of `NUL` characters in the file

![image](https://user-images.githubusercontent.com/45571053/151319544-1f9c5c70-bd10-4dd0-b5ac-d4590a408d0a.png)

I'm guessing this is part of the reason I'm getting this error when trying to read the file again:
```log
Fatal error: Uncaught Error: Invalid XPath Context in /path/to/project/vendor/embed/embed/src/Document.php on line 88
```

Is there a better way to do this? Is perhaps the response not "clean"?

**Comment by grandeljay** [comment]
I read that to avoid the null bytes I should base64 encode/decode but I also get an error trying that.

**Comment by grandeljay** [comment]
Sorry for spam, I made a very obvious mistake and now it works with serialize.
