### ISSUE TITLE
Unable to cache

### ISSUE THREAD

**Issue by grandeljay** [oscarotero/Embed#472]
Apologies, I thought this would be better suited in a separate issue.

Using cache for this does not seem to work due to this private object
```
 ["xpath":"Embed\Document":private]=>
    object(DOMXPath)#102 (2) {
      ["document"]=>
      string(22) "(object value omitted)"
      ["registerNodeNamespaces"]=>
      bool(true)
    }
```

I'm guessing the error occurs because I am saving something omitted/private in my cache and later you can't read it anymore internally.

Does it maybe need to be public for the cache to work?

```
Fatal error: Uncaught Error: Invalid XPath Context in /path/to/project/vendor/embed/embed/src/Document.php on line 88
```

**Comment by oscarotero** [comment]
The best way to save the cache is create a different array with the values, but not cache the returned extractor, that contains more complex things like a DOMElement, DOMXPath, Request, Responses, all the detectors, etc.

Take a look to how to get the data to be cached in the tests: https://github.com/oscarotero/Embed/blob/master/tests/PagesTestCase.php#L96

**Comment by grandeljay** [comment]
Thank you so much!
