### ISSUE TITLE
Accept only videos

### ISSUE THREAD

**Issue by wyllyjon** [oscarotero/Embed#475]
Hello ! 

Is it possible to know what type of content correspond to a given url ?
I would like to accept only url of videos.

Thank for your help !

Jonathan

**Comment by oscarotero** [comment]
It's not possible to know that in a reliable way.
The embed code returned by many sites are iframes or javascript code so you don't know what's inside.
Maybe you can create a list of accepted providers (youtube, vimeo etc) and check if the url is from one of these providers.

**Comment by wyllyjon** [comment]
Ok, yes, it is a good idea :-)

Thanks for the help !

Le mer. 16 févr. 2022 à 16:40, Oscar Otero ***@***.***> a
écrit :
