### ISSUE TITLE
Canonical URL seems to be wrong

### ISSUE THREAD

**Issue by grandeljay** [oscarotero/Embed#478]
Please excuse me if I am using this wrong but the canonical URL seems to be wrong here:

https://oscarotero.com/embed/demo/index.php?url=https%3A%2F%2Fwww.etsy.com%2Fde%2Flisting%2F653731908%2Fvalentinstag-geschenk-fur-ihn-holzuhr%3Fclick_key%3D49&settings=

It's showing the URL I used instead of the canonical URL from the source or even an empty value, which I would prefer. Is it maybe a feature and defaulting to my URL instead of an empty value?

![image](https://user-images.githubusercontent.com/45571053/155550050-c3c8fd13-15dd-4ce5-a9c7-9e783616f630.png)
![image](https://user-images.githubusercontent.com/45571053/155549419-8932d3c6-b0b2-4173-b23a-547faf8497e2.png)
![image](https://user-images.githubusercontent.com/45571053/155549991-0b1bbbb3-0724-4833-be39-476a91c9d576.png)

**Comment by oscarotero** [comment]
Hi. Canonical URL is not always a reliable value. I had too many issues from sites that returns the same canonical url for all pages, or goes to a different page. This is why it's not used.

**Comment by grandeljay** [comment]
>I had too many issues from sites that returns the same canonical url for all pages, or goes to a different page.

Wouldn't that be the site owners problem? If they mark a URL as canonical shouldn't that be used? Even if it seems wrong to us?

**Comment by oscarotero** [comment]
Yes, if all developers made everything right and standard, it would be more easy but sadly it's not happening :)
Even [Google can ignore the `canonical` value](https://developers.google.com/search/docs/advanced/crawling/consolidate-duplicate-urls) on index a website for various reasons.

To include the canonical url or any other desired value, you can extend the [Url detector](https://github.com/oscarotero/Embed/blob/master/src/Detectors/Url.php).

**Comment by grandeljay** [comment]
Oh, neat. Thanks!

**Comment by grandeljay** [comment]
Is there an easy way to just return `null` or something empty if the canonical URL is not set? I'm not understanding how this works :/

```php
public function detect(): UriInterface
    {
        $oembed = $this->extractor->getOEmbed();

        return $oembed->url('url') ?? new Url('');
    }
```

**Comment by oscarotero** [comment]
The url cannot be `null`. What you can do is check the canonical url:

```php
public function detect(): UriInterface
{
    $oembed = $this->extractor->getOEmbed();

    return $oembed->url('url')
        ?: $oembed->url('web_page')
        ?: $this->getCanonical()
        ?: $this->extractor->getUri();
}

protected function getCanonical(): ?UriInterface
{
    $document = $this->extractor->getDocument();
    foreach ($document->select('.//link[@canonical]')->nodes() as $node) {
        $href = $node->getAttribute('href');

        if ($href) {
            return $this->extractor->resolveUri($href);
        }
    }
}
```
(Not tested)

**Comment by grandeljay** [comment]
This is perfect, thank you so much!

Just in case anybody else is interested, here is my slightly revised version (with a `return null` statement) I am using:
```php
public function detect(): UriInterface
{
    $oembed = $this->extractor->getOEmbed();

    return $oembed->url('url')
        ?: $oembed->url('web_page')
        ?: $this->getCanonical()
        ?: $this->extractor->getUri();
}

protected function getCanonical(): ?UriInterface
{
    $document = $this->extractor->getDocument();

    foreach ($document->select('.//link[@canonical]')->nodes() as $node) {
        $href = $node->getAttribute('href');

        if ($href) {
            return $this->extractor->resolveUri($href);
        }
    }

    return null;
}
```

The [full file](https://github.com/grandeljay/wishthis/blob/e3bbd3d0ae76a9f7fedfed4d777376cd9e950a00/src/classes/emebd-uri-interface.php#L15-L38) is here

**Comment by oscarotero** [comment]
You can create a different detector instead of extending the current one. This allows to have a custom property, like `$info->canonical`.

See this: https://github.com/oscarotero/Embed#detectors
