### ISSUE TITLE
Youtube playlists

### ISSUE THREAD

**Issue by oscarotero** [oscarotero/Embed#48]
Example: https://www.youtube.com/playlist?list=PL4qTakKkQATKOyZPJG_cAMnRtF7fAIdST

**Comment by tmli3b3rm4n** [comment]
I'm fixing to be implementing this into our system. I'll see about adding this feature and submitting PR.

**Comment by oscarotero** [comment]
That's great. I'll keep an eye on it. Thank you

**Comment by tmli3b3rm4n** [comment]
:+1:

**Comment by oscarotero** [comment]
Fixed in the next release, using oembed.
