### ISSUE TITLE
How to check BEFORE if the URL is an EMBED and how to check its Type (check if it is audio, image or video Type) ???

### ISSUE THREAD

**Issue by chegmarco1989** [oscarotero/Embed#487]
Hi.

**How to find Embed URL type, that is to say check if it is an `audio`, a `photo` or even a `video` ???**

How to check first if the media supports the `embed` format and secondly if it is audio, image or video type ???

I searched the PHP.NET documentation in vain to see if there is a checkoEmbed function but nowhere did I find such a function that could help me check if the URL of a media is `embed`.

**Another word, I want to know if is there a way to check if URL is an Embed before to crawl it and How to get its Type (audio, video or image). So, how to check it in PHP ???**

Thank you please help me.

**Comment by oscarotero** [comment]
> How to find Embed URL type, that is to say check if it is an audio, a photo or even a video ???

There's no reliable way to detect this. Some sites supporting oEmbed can provide this info in the type value: 
```php
$oembed = $info->getOEmbed();
$type = $oembed->get("type");
```
But most sites don't provide this info.

> Another word, I want to know if is there a way to check if URL is an Embed before to crawl it and How to get its Type (audio, video or image). So, how to check it in PHP ???

This library need to crawl the site to detect this. If you want to know this info only by the url, this is not the library for you.
