### ISSUE TITLE
"Undefined variable" yet I declared the variable "$description"

### ISSUE THREAD

**Issue by chegmarco1989** [oscarotero/Embed#490]
Hello.

Having indeed declared my variable $description, when I try to display it with echo $description, I see an error return:

`Notice: Undefined variable: description in C:\laragon\www\testdoc\test.php on line 22`

```
<?php
require("vendor/autoload.php");
use Embed\Embed;
 
$embed = new Embed();
 
//Load any url:
$embedInfo = $embed->get('https://fr.wikipedia.org/wiki/YouTube');
 
//Get content info
 
$embedInfo->title; //The page title
$embedInfo->description; //The page description
$embedInfo->url; //The canonical url
$embedInfo->keywords; //The page keywords
 
 
if ($embedInfo == true && !empty($embedInfo->description)) {
	$description = rawurldecode($embedInfo->description);
}
 
echo $description."<br /><br />";
```

Everything seems correct to me, but the error, I do not understand why?
Thank you for helping me.

**Comment by oscarotero** [comment]
The variable is declared inside an `if`, so maybe this condition is not true.
Anyway, this is not a Embed issue, so I'm closing this.

**Comment by chegmarco1989** [comment]
I tried to correct the error at my level. 
But of course there is a bug. Here is my Code:

```
<?php
require("vendor/autoload.php");
use Embed\Embed;

$embed = new Embed();

//Load any url:
$embedInfo = $embed->get('https://fr.wikipedia.org/wiki/YouTube');

//Get content info

$embedInfo->title; //The page title
$embedInfo->description; //The page description
$embedInfo->url; //The canonical url
$embedInfo->keywords; //The page keywords

$description = "";
$title = "";
$keywords = "";
if (!isset($embedInfo->description)) {
	$description = rawurldecode($embedInfo->description);
}
```

**The DESCRIPTION DISPLAYED IS:** "_YouTube (en français : [ jutyb] ou [ jutjub], en anglais : ..._".

It only displays the beginning of the sentence without ever ending the complete sentence ???
It only displays a few strings from the description.
How to correct it ???

**Comment by oscarotero** [comment]
This is not an error, it's what Wikipedia returns from this API. (See: https://fr.wikipedia.org/w/api.php?action=query&format=json&continue=&titles=YouTube&prop=extracts&exchars=1000)

**Comment by chegmarco1989** [comment]
Okay. Thanks
