### ISSUE TITLE
Can Embed be used with proxies, and custom headers? Including for getMulti() requests?

### ISSUE THREAD

**Issue by solkad** [oscarotero/Embed#493]
I was wondering if Embed can be used with proxies, and custom headers for each request, like the setting of user agents, "Accept", "Accept-Language", etc.

And if these can be different for different URLs in a getMulti() request.

**Comment by oscarotero** [comment]
For proxies, you can configure the curl client (See this: https://github.com/oscarotero/Embed#settings).
For default header, the `crawler` class has an [addDefaultHeaders](https://github.com/oscarotero/Embed/blob/master/src/Http/Crawler.php#L30) function.

**Comment by solkad** [comment]
Great thank you very much :)
