### ISSUE TITLE
Youtube option choose_bigger_image no longer works/removed

### ISSUE THREAD

**Issue by RVXD** [oscarotero/Embed#500]
It seems the choose_bigger_image option was removed? How can I get large preview images?

For now I replace the result 'hqdefault.jpg' in the thumbnail_url with 'maxresdefault.jpg', not sure if this is the way to go.

**Comment by oscarotero** [comment]
Yes, in the version 4, the logic to choose the image was simplified.
Choosing the bigger image requires to get all images, get their sizes and pick the bigger.
See this with more info: https://github.com/oscarotero/Embed/issues/343

**Comment by RVXD** [comment]
Thanks for the explanation!
