### ISSUE TITLE
The path of a URI with an authority must start with a slash "/" or be empty

### ISSUE THREAD

**Issue by grandeljay** [oscarotero/Embed#501]
Not sure if this is an issue for Guzzle, but I'll start here since I am curious of your opinion on this.

When fetching this URL: https://kipli.com/fr/product/matelas-bebe-bio/ (https://oscarotero.com/embed/demo/index.php?url=https%3A%2F%2Fkipli.com%2Ffr%2Fproduct%2Fmatelas-bebe-bio%2F&settings=)

My app returns a warning: `The path of a URI with an authority must start with a slash "/" or be empty`. After some digging, I found that the source code of the site seems to be invalid. In particular the alternative languages:
```html
<link data-n-head="ssr" rel="alternate" hreflang="en_dk" href="undefined">
```
The locale for `en_dk` has `undefined` set for the `href`. And I believe this is the cause of the warning I am getting. Your demo seems to work fine but I have
```php
$foo = $embedInfo->languages
```
inside a try/catch which is then failing. Because `undefined` is not a valid URL/URI. 

My question is if you can/should handle this and determine if the `href` is valid?

**Comment by oscarotero** [comment]
The problem is `undefined` is a valid value for the href attribute, this is an issue in the website side.

A solution would be assume the "undefined" value as an empty value, but this opens the door to other values that must be considered empty like "null", "nil", etc. I don't know if make such assumptions is a good idea.

**Comment by grandeljay** [comment]
Hmmm... Are the values `null`, `nil` etc also valid? My assumption is that there was some issue with JavaScript and the value has `undefined` which surely isn't intentional. I mean, why would anybody want `undefined`, etc here? I think it would be best if you handle it.

In this case, this small change should fix the issue:

```php
'undefined' === $href
```
in `/vendor/embed/embed/src/Detectors/Languages.php:21`
```php
<?php

declare(strict_types=1);

namespace Embed\Detectors;

class Languages extends Detector
{
    /**
     * @return \Psr\Http\Message\UriInterface[]
     */
    public function detect(): array
    {
        $document  = $this->extractor->getDocument();
        $languages = array();

        foreach ($document->select('.//link[@hreflang]')->nodes() as $node) {
            $language = $node->getAttribute('hreflang');
            $href     = $node->getAttribute('href');

            if (!$language || !$href || 'undefined' === $href) {
                continue;
            }

            $languages[$language] = $this->extractor->resolveUri($href);
        }

        return $languages;
    }
}
```

Alternatively is there something I can do to handle this case? I really don't know what the beast solution would be here.

**Comment by oscarotero** [comment]
In this case, I'd create a helper, so it can be used in other places. Something like:

```php
function isEmpty($value) {
    return empty($value) || $value === "undefined";
}
```

If you want to work on a PR, I'll review and merge it.
