### ISSUE TITLE
How to display only html.description and html.tags

### ISSUE THREAD

**Issue by sakirsa** [oscarotero/Embed#505]
Hi. I'm sorry for the probably stupid question, but how to display the value from the html provider only html.description and html.tags for example?

**Comment by oscarotero** [comment]
You can use the `metas` object:

```php
$metas = $info->getMetas();

$metas->str('og:title'); //Return the og:title meta tag
$metas->str('og:description'); 
```

More info: https://github.com/oscarotero/Embed#metas

**Comment by sakirsa** [comment]
Thank you!! one more small clarification, how to display, for example, description if it is an array and you need 3 value

$metas->str('description'); - outputs the first

**Comment by oscarotero** [comment]
Use `$metas->get("description")` to get an array of values

**Comment by sakirsa** [comment]
thanks a lot
