### ISSUE TITLE
Particular Website Shows Different URL contents

### ISSUE THREAD

**Issue by parrycarry** [oscarotero/Embed#510]
There's a particular explicit website... and for some reason, it displays the same wrong URL contents for every possible link. I know this issue isn't directly related to Embed, because the link works just fine on your Demo Page, but I can't find any explanation for why this happens anywhere, maybe I don't know what to look for. Maybe it is host related, IDK... I'd love to fix it, so all links work properly, but I am completely at a loss right now...

**Comment by oscarotero** [comment]
There are several sites that detect the request ip or user agent and block them if they are from suspicious origins.

**Comment by parrycarry** [comment]
I don't believe the User Agent is the problem, cause it did it whether I used your default or set my own...

I have a Cloud Hosted Dedicated IP... but I notice when going to your Remote IP Address with port 443, it doesn't redirect to https and remove port 443 like mine does... I wonder if that might be the cause. Which would mean I'd probably need to move to a VPS eventually... cause this isn't a behavior I can change as far as I can see... Though, this is pure speculation.... was hoping I wouldn't need to fork over more money to fix problems I come across.

**Comment by parrycarry** [comment]
I didn't change anything, but it seems this issue is now gone on it's own.
