### ISSUE TITLE
request's locale change support

### ISSUE THREAD

**Issue by korhaninjotform** [oscarotero/Embed#513]
The locale of request should be changeable by app and it will be English as default.

![image](https://user-images.githubusercontent.com/117642887/234028315-c5496ba9-367f-49b9-953b-c1643a5f6e99.png)

**Comment by oscarotero** [comment]
You can configure Embed to send http headers or pass additional parameters to oembed https://github.com/oscarotero/Embed#settings

**Comment by korhaninjotform** [comment]
Oh, ok, thank you.
