### ISSUE TITLE
Maximum redirects followed instagram

### ISSUE THREAD

**Issue by JurreTH** [oscarotero/Embed#516]
When requesting an instagram post you get the following error (tested on https://oscarotero.com/embed/demo/index.php with correct instagram key):

`Embed\Http\NetworkException: Maximum (10) redirects followed in /var/www/oscarotero.com/www/embed/src/Http/CurlDispatcher.php:157
Stack trace:
#0 /var/www/oscarotero.com/www/embed/src/Http/CurlDispatcher.php(120): Embed\Http\CurlDispatcher->error()
#1 /var/www/oscarotero.com/www/embed/src/Http/CurlDispatcher.php(31): Embed\Http\CurlDispatcher->exec()
#2 /var/www/oscarotero.com/www/embed/src/Http/CurlClient.php(31): Embed\Http\CurlDispatcher::fetch()
#3 /var/www/oscarotero.com/www/embed/src/Http/Crawler.php(56): Embed\Http\CurlClient->sendRequest()
#4 /var/www/oscarotero.com/www/embed/src/Embed.php(24): Embed\Http\Crawler->sendRequest()
#5 /var/www/oscarotero.com/www/embed/demo/index.php(230): Embed\Embed->get()
#6 {main}`

**Comment by maetthu** [comment]
Apparently, instagram redirects certain IPs to the login page and ends up in an endless loop (the login page itself redirects to the login page and so on). I couldn't reproduce this on my notebook but it happens in github actions as well as in our production environment. 

Workaround which worked for me is to disable following redirects for instagram (oEmbed is hitting a Facebook Graph API endpoint anyway, it doesn't need to scrape the site, at least as far as I'm aware)

```php
$url = 'https://www.instagram.com/....';

$client = new CurlClient();
$client->setSettings([
    // Disable redirects for instagram because sometimes they redirect to login page
   //  but we fetch from facebook.com oembed endpoint anyway
    'follow_location' => !str_contains($url, 'instagram.com'),
]);

$embed = new Embed(new Crawler($client));
$embed->setSettings([
    'facebook:token' => $facebookAccessToken,
    'instagram:token' => $facebookAccessToken,
]);
```

**Comment by arifje** [comment]
Looks like it's working again, maybe Instagram did an update?
