### ISSUE TITLE
The demo site is offline

### ISSUE THREAD

**Issue by MackSix** [oscarotero/Embed#522]
The demo site is offline. 

https://oscarotero.com/embed/demo/

```
This site can’t be reached oscarotero.com refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED
```

**Comment by oscarotero** [comment]
Thanks for warning, it's live again.
FYI I'm planning to shut down the demo site at some point.

**Comment by ValdikSS** [comment]
It's 404 now.

**Comment by oscarotero** [comment]
Yes, I removed it some time ago due too many requests.
you can run it in your computer with `php -S localhost:8888 demo/index.php`
