### ISSUE TITLE
Setting user agent for request does not seem to work

### ISSUE THREAD

**Issue by grandeljay** [oscarotero/Embed#526]
I'm experiencing a lot of 403 responses and start playing around to see if the default user agent (`"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:73.0) Gecko/20100101 Firefox/73.0"`) might be at fault here.

This is the code I am using:
```php
$client = new \Embed\Http\CurlClient();
$client->setSettings(
    array(
        'user_agent' => 'pls work',
    )
);

$embed     = new \Embed\Embed(new \Embed\Http\Crawler($client));
$embedInfo = $embed->get($this->url);
```
As far as I can tell this is ignored and the default is used instead. Can you reproduce this? What am I doing wrong?

**Comment by oscarotero** [comment]
It works fine to me. The `pls work` user agent is sent.
You can use `var_dump` to make sure it works for you here: https://github.com/oscarotero/Embed/blob/master/src/Http/CurlDispatcher.php#L102

**Comment by grandeljay** [comment]
Thanks! It was working all along, I was just looking wrong. Unfortunately I am still getting blocked. Do you have any tips to handle this?

Either way, thanks for your help and this repository!
