### ISSUE TITLE
Large quantities of embed-cookies-{uid} are being created, but not deleted?

### ISSUE THREAD

**Issue by tim-digitalastronaut** [oscarotero/Embed#534]
I've recently run into issues where no user sessions were being created on the server due to the fact that the /temp folder used up all available memory. After inspecting the contents of the folder, we noticed a huge quantity (0.5 mln) files names embed-cookie-{uid}.txt.

After reviewing the code for your plugin, and after taking a look at the `\embed\src\Http\CurlDispatcher.php` file's constructor, it would seem that this is the source of the issue. I'm assuming that these .txt files are being created in the temporary storage, but are never being deleted, or maybe only after a very long time?

For now we've cleared out the excess of files in our /temp folder. But obviously we'll encounter the same issue again in the foreseeable future.

**Comment by oscarotero** [comment]
yes, cookies file is created here: https://github.com/oscarotero/Embed/blob/8632aaa00b35de05de89988632bee7e7392b032e/src/Http/CurlDispatcher.php#L93 but it's not deleted.

But this is just one file with a specific name "embed-cookies.txt", not  a bunch of files with `uid`. So I don't know why do you get that.
