### ISSUE TITLE
aspectRatio returns null if we don't access width and height first

### ISSUE THREAD

**Issue by F21** [oscarotero/Embed#57]
To reproduce:

```php
<?php
require ('embed/src/autoloader.php');

$info = Embed\Embed::create('https://www.youtube.com/watch?v=dd7sV6SAEAU');
//var_dump($info->width);
//var_dump($info->height);
var_dump($info->aspectRatio);
```

Notice that `aspectRatio` returns null. However, if we uncomment the 2 `var_dump`s for `width` and `height`, `apectRatio` returns a value.

Tested with PHP `5.6.7` and `5.6.8`

**Comment by oscarotero** [comment]
Thank you for your feedback. Fixed
