### ISSUE TITLE
Redirects and says No Data Received

### ISSUE THREAD

**Issue by rohit49khatri** [oscarotero/Embed#59]
When i try to fetch a specific url ('http://t.co/VcPr1O8O6h') which contains:

<noscript><META http-equiv="refresh" content="0;URL=http://www.bloomfieldchristian.com/five-common-misconceptions-about-the-common-core/"></noscript><title>http://www.bloomfieldchristian.com/five-common-misconceptions-about-the-common-core/</title><script>window.opener = null; location.replace("http:\/\/www.bloomfieldchristian.com\/five-common-misconceptions-about-the-common-core\/")</script>

redirects to a page and says No Data Received.

**Comment by oscarotero** [comment]
Hi. This should be fixed in [2.2.4](https://github.com/oscarotero/Embed/releases/tag/v2.2.4)
