### ISSUE TITLE
Wikipedia support

### ISSUE THREAD

**Issue by npanasenko** [oscarotero/Embed#61]
We could use the extracts and images props.

https://en.wikipedia.org/w/api.php?action=help&modules=query%2Bextracts
https://www.mediawiki.org/wiki/API:Images

**Comment by oscarotero** [comment]
I didn't know the wikipedia api, but it's a good idea. Thank you

**Comment by oscarotero** [comment]
The new version has support for wikipedia:
http://oscarotero.com/embed2/demo/index.php?url=https://en.wikipedia.org/wiki/Albert_Einstein

**Comment by npanasenko** [comment]
Great stuff!
