### ISSUE TITLE
Giving false

### ISSUE THREAD

**Issue by rohitkhatri** [oscarotero/Embed#62]
When I try to fetch embed of a YouTube url, It gives false.

Here is my code:

		error_reporting(E_ALL);
		ini_set('display_errors', 1);

		$url = 'https://www.youtube.com/watch?v=kUylIQy-IgI';
		require_once 'inc/class/lib/Embed/src/autoloader.php';
		$embed = Embed\Embed::create($url);
		var_dump($embed);
		echo '<pre>'.print_r($embed,true).'</pre>';

Please help me with this.

**Comment by oscarotero** [comment]
Hi.
I don't see any problem. It works fine in my computer and in the online demo: http://oscarotero.com/embed2/demo/index.php?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DkUylIQy-IgI
Maybe your computer has some requirements missing? (curl extension or any configuration that avoid create https requests?)

**Comment by rohitkhatri** [comment]
It was working perfectly earlier, but now It's giving false don't know why ? But when I try to fetch vimeo,facebook,vine embed It does fetch. It's giving false for instagram and vimeo.

And yes curl is installed.

**Comment by oscarotero** [comment]
Can you do a `var_dump` of `$this->resut` [here?](https://github.com/oscarotero/Embed/blob/master/src/RequestResolvers/Curl.php#L145), so we can see the info about the curl request.

**Comment by rohitkhatri** [comment]
I got the following output by doing var_dump

	array(26) { ["url"]=> string(43) "https://www.youtube.com/watch?v=kUylIQy-IgI" ["content_type"]=> string(24) "text/html; charset=utf-8" ["http_code"]=> int(429) ["header_size"]=> int(465) ["request_size"]=> int(193) ["filetime"]=> int(-1) ["ssl_verify_result"]=> int(0) ["redirect_count"]=> int(0) ["total_time"]=> float(0.180564) ["namelookup_time"]=> float(0.004171) ["connect_time"]=> float(0.012106) ["pretransfer_time"]=> float(0.030642) ["size_upload"]=> float(0) ["size_download"]=> float(33043) ["speed_download"]=> float(182998) ["speed_upload"]=> float(0) ["download_content_length"]=> float(-1) ["upload_content_length"]=> float(0) ["starttransfer_time"]=> float(0.172199) ["redirect_time"]=> float(0) ["redirect_url"]=> string(0) "" ["primary_ip"]=> string(14) "173.194.33.129" ["certinfo"]=> array(0) { } ["primary_port"]=> int(443) ["local_ip"]=> string(13) "172.31.42.173" ["local_port"]=> int(42737) }

**Comment by oscarotero** [comment]
I see the http code result is 429, that means "Too many requests" (https://en.wikipedia.org/wiki/List_of_HTTP_status_codes)
Maybe you're executing to many requests to youtube and it blocks you temporary.

**Comment by rohitkhatri** [comment]
Is there any solution for that ? And Instagram was not working, but now it's working fine.

Thanks for your help.

**Comment by oscarotero** [comment]
I guess this depends of each service. Youtube and instagram may have a limited number of request in a time interval. Maybe executing the requests using different ips, but this is something out of the scope of this library.

**Comment by rohitkhatri** [comment]
Thanks for your help.

**Comment by abelkbil** [comment]
I too get false for youtube. All other works fine. Youtube works fine with localhost, But not in server. How to debug?

**Comment by rohitkhatri** [comment]
@abelkbil do a var_dump of $this->resut here?, so we can see the info about the curl request.

**Comment by oscarotero** [comment]
The [latest version](https://github.com/oscarotero/Embed/releases/tag/v2.3.0) throws an exception instead simply returns `true`, so you can see why the curl request failed.

**Comment by rohitkhatri** [comment]
I have changed my IP and have taken another ec2 instance with different ip but still it gives the same error even It's my first call to twitter with this IP, any solution ?

**Comment by rohitkhatri** [comment]
With updated library, It throws this error.

Fatal error: Uncaught exception 'Embed\Exceptions\InvalidUrlException' with message 'The url 'https://www.youtube.com/watch?v=PP1xn5wHtxE' returns the http code '429'' in /var/www/newsroom/public_html/app/inc/class/lib/Embed1/src/Embed.php:21 Stack trace: #0 /var/www/newsroom/public_html/app/test.php(3): Embed\Embed::create('https://www.you...') #1 {main} thrown in /var/www/newsroom/public_html/app/inc/class/lib/Embed1/src/Embed.php on line 21

**Comment by oscarotero** [comment]
It's a bit odd. Can you try to change some [curl parameters](http://php.net/manual/en/function.curl-setopt.php)? Maybe the user agent or something like that.

Another aproach is to try to execute the curl request outside of the library:

```php
$connection = curl_init();
curl_setopt_array($connection, [
    CURLOPT_RETURNTRANSFER => false,
    CURLOPT_FOLLOWLOCATION => true,
    CURLOPT_URL => 'https://www.youtube.com/watch?v=kUylIQy-IgI',
    CURLOPT_MAXREDIRS => 20,
    CURLOPT_CONNECTTIMEOUT => 10,
    CURLOPT_TIMEOUT => 10,
    CURLOPT_SSL_VERIFYPEER => false,
    CURLOPT_SSL_VERIFYHOST => false,
    CURLOPT_ENCODING => '',
    CURLOPT_AUTOREFERER => true,
    CURLOPT_USERAGENT => 'Embed PHP Library',
    CURLOPT_IPRESOLVE => CURL_IPRESOLVE_V4,
]);

$content = curl_exec($connection);
var_dump(curl_getinfo($connection));
```

**Comment by rohitkhatri** [comment]
When I tried curl request outside the library [this](http://i.imgur.com/05xYVB3.png) content was shown.

**Comment by oscarotero** [comment]
I don't know why this happens, seems like youtube detects the same network, no matter the specific ip.

**Comment by rohitkhatri** [comment]
How can it be possible to detect a network instead of IP ? Have any idea ?

**Comment by oscarotero** [comment]
From [google's documentation](https://support.google.com/websearch/answer/86640?hl=en)
> Google Search blocks IPs, IP ranges, and in some cases, whole ISPs, when a large percent of the traffic entering our networks is abusive.

Maybe your ip is in an ip range that it's blocked. I've [googled](https://encrypted.google.com/search?safe=off&hl=gl&q=sorry+for+the+interruption.+we+have+receiving+a+large+volume+of+request+from+your+network&oq=sorry+for+the+interruption.+we+have+receiving+a+large+volume+of+request+from+your+network&gs_l=serp.3...71577.72431.0.72655.0.0.0.0.0.0.0.0..0.0....0...1c.1.64.serp..0.0.0.sfgL-b8v91k) this and they say the same in all results. I don't think much can be done, except wait for the overload goes away.

**Comment by rohitkhatri** [comment]
You have been very supportive all the time, thank you so much for that. :-) I would try it with a totally different IP and let you know..!!

**Comment by cadavre** [comment]
Shouldn't we use dedicated methods to fetch thumbnails like https://developers.google.com/youtube/v3/docs/thumbnails ?

**Comment by oscarotero** [comment]
I'm not using the youtube API because oembed is enought to get all needed data, not only thumbnail but also the author, title, embed code, etc. [For example this](http://www.youtube.com/oembed?url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DkUylIQy-IgI&amp;format=json) So I don't see much benefits of using another http request to get the same information.

**Comment by cadavre** [comment]
So basically it's not server with installed Embed library requesting for YouTube thumbnail but oembed so why this problem exists?

**Comment by oscarotero** [comment]
Sorry but I don't understand what you mean.

**Comment by oscarotero** [comment]
Embed always load the main url in the first place (for example https://www.youtube.com/watch?v=kUylIQy-IgI).
Then, it may execute other http requests depending of the page. For youtube videos, loads the data using the oembed API.
The problem here is youtube returns 429 error in the first call (the main url).

**Comment by cadavre** [comment]
So in this case I guess Embed should continue on error from main URL because it can fetch necessary data from other source (oembed). This will work for future services too. Is it possible?

**Comment by oscarotero** [comment]
Embed doesn't work like that. The main url is loaded because many reasons:
* To be sure the url exists and is valid (it must returns http code 200)
* To resolve possible redirections (for url shorteners like bit.ly or even youtube has its own short url: https://youtu.be/)
* To load data from the html (opengraph, twitter cards, etc)
* A lot of services includes the url of the oembed service in the head. Youtube is one of these services. In the html code there is a link element like `<link rel="alternate" type="application/json+oembed" href="http://www.youtube.com/oembed?format=json&amp;url=http%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DkUylIQy-IgI">`. So this library does not need to include a huge list of oembed endpoits for all possible services (hard to maintain) because they are taken from the html. It just need a small list with the services than does not provide this information in the html.
