### ISSUE TITLE
Most common color(s) in images/favicon

### ISSUE THREAD

**Issue by g5400658** [oscarotero/Embed#63]
I think it would be handy to return an array of the most common colors (like a color palette) of the images and favicons, much like embed.ly does:

http://embed.ly/docs/explore/extract?url=http%3A%2F%2Ftechcrunch.com%2F2013%2F03%2F26%2Fembedly-now-goes-beyond-embedding-with-new-products-extract-display-for-making-sense-of-links-resizing-images%2F

**Comment by oscarotero** [comment]
There are some libraries that already do that, so I think it's better to use them:
* https://github.com/humanmade/Colors-Of-Image
* https://github.com/thephpleague/color-extractor
