### ISSUE TITLE
Autoplay embed code?

### ISSUE THREAD

**Issue by g5400658** [oscarotero/Embed#64]
Is there an option to set the autoplay property for the embed code.

For example, the YouTube embed code by default looks like this:

`<iframe width="480" height="270" src="https://www.youtube.com/embed/jbM9uCxEJDM?feature=oembed" frameborder="0" allowfullscreen></iframe>`

Is it possible to add the `autoplay` parameter, like this:

`<iframe width="480" height="270" src="https://www.youtube.com/embed/jbM9uCxEJDM?feature=oembed&autoplay=1" frameborder="0" allowfullscreen></iframe>`

**Comment by oscarotero** [comment]
I'm not sure about this. The purpose of Embed is to be platform agnostic and work with any webpage, not only with popular services such youtube. So platform-specific options like autoplay only makes sense for youtube.
Embed uses oembed to get the data from youtube and it has some extra parameters that you can use. For example `iframe=0` that returns a flash's `<object>` as embed code instead an `<iframe>`  ([example](http://www.youtube.com/oembed?url=http%3A//www.youtube.com/watch%3Fv%3DbDOYN-6gdRE&format=json&iframe=1)). To add extra parameters to the oembed provider: 

```php
$info = Embed::create($url, [
    'providers' => [
        'oembed' => [
            'parameters' => ['iframe' => 0]
        ]
    ]
]);
```
Anyway, I don't know if there is an autoplay option.

**Comment by plakhin** [comment]
Does anyone found out how to enable autoplay at least for platforms that support it (i.e. Youtube, Vimeo, SoundCloud, Twitch, Dailymotion)?
