### ISSUE TITLE
Undefined offset: 20 in Adapters/Adapter.php(372)

### ISSUE THREAD

**Issue by younes0** [oscarotero/Embed#70]
Using dev-master branch, I got `Undefined offset: 20 in Adapters/Adapter.php(372)` while getting image() from a bunch of links.

**Comment by oscarotero** [comment]
I do not recomend using dev-master because it's non stable yet. Anyway, can I get the url you are using?

**Comment by younes0** [comment]
Okay I will tell you soon if it happens with the stable branch and which url causes the error (with the dev-master branch)

**Comment by younes0** [comment]
So it happened with the latest stable branch and the url is <http://www.eu-startups.com/startup-jobs/>

**Comment by younes0** [comment]
:+1: thanks

**Comment by oscarotero** [comment]
you're welcome :smile:
