### ISSUE TITLE
HTML: check all meta values to find published_time

### ISSUE THREAD

**Issue by younes0** [oscarotero/Embed#75]
Meta properties to get publication time are often missing or different, it's a mess.
What about checking all meta values to find if it's a date or not (with `Carbon::parse`) 
After some observations, most of the time the date values correspond to publication time

**Comment by younes0** [comment]
```php
public function getPublishedTime()
{
    $date = $this->bag->get('pub_date')
        ?: $this->bag->get('date')
        ?: $this->bag->get('pagerender')
        ?: $this->bag->get('datepublished');
    
    if ( !$date) {
        foreach ($this->bag->getAll() as $key => $value) {
            try {
                if ($date = new \DateTime(trim(html_entity_decode($value))) ) {
                    break;
                }

            } catch (\Exception $e) {
                continue;
            }
        }
    }

    return $date;
}

**Comment by oscarotero** [comment]
Are you saying to check all values to test whether they are valid time values or not, regardless the key?
I don't think this is a good idea because random values can be parsed as valid Datetime values. If you know about other meta names that can be added after `pub_date`, `date`, `pagerender` and `datepublished` its great, but I do not would check all names.

**Comment by younes0** [comment]
After some investigations, you are right, all numerical values such as `fb:app-id` are parsed. 
Still you can check if date is an abberation by checking the year.

I think we can't be exhaustive/accurate, so I agree with you that we should add meta names instead of guessing date meta values. This is what I found (excluding OpenGraph & Sailthru):

>
article:published_time
datePublished
dc.date
dc.date.issued
dc:date.created
dcterms:created
newsrepublic:publish_date
publication-date
rc.datecreation
shareaholic:article_published_time
article:modified_time
eomportal-lastupdate

Should I add these keys to check in `HTML::getPublishedTime()` ?

**Comment by oscarotero** [comment]
Great, thank you!

Some of the keys provided should be added to Dcterms provider (https://github.com/oscarotero/Embed/blob/master/src/Providers/Dcterms.php). By the way, I see some inconsistencies in dc terms: some keys use dot (`dc.*`) others colon (`dc:*`) and other (`dcterm:*`). Currently only [the first case is taking into consideration](https://github.com/oscarotero/Embed/blob/master/src/Providers/Dcterms.php#L24) so maybe we should change this.

**Comment by younes0** [comment]
Got it! I'll make a PR soon

**Comment by oscarotero** [comment]
:+1:
