### ISSUE TITLE
Request in oembedImplementation

### ISSUE THREAD

**Issue by zyuhel** [oscarotero/Embed#88]
Some sites have oembed data available, but not according standard. For exaple 
www.url.com/photo/id/name
will have oembed data in
www.url.com/photo/id/oembed.json

OEmbedImplementation for getEndpoint for such sites need to know about requested url. 
So, i have a question should i write what in fact will be a copy of oembed provider. Or should i modify OEmbedImplementation, and classes implementing it so that getEndpoint method has optional url parameter like the one in params.

**Comment by oscarotero** [comment]
I think changing OEmbedImplementation to accept the url as argument is a better aproach.
