### ISSUE TITLE
[Insight] User specific files should not appear in .gitignore - in .gitignore, line 3

### ISSUE THREAD

**Issue by zyuhel** [oscarotero/Embed#89]
I also think, that adding this to project gitignore, not the best way .
maybe only composer.lock and vendor should be there?
Someone also suggests that composer.lock should be added to git. it has benefits and disadvantages. But platform specific files and editor options files generally should be in global gitignore.

**[in .gitignore, line 3](https://github.com/oscarotero/Embed/blob/3f9b807bac6935acb05d1d1da637600589c5d6c9/.gitignore#L3)**

> `.DS_Store` is user-specific and should not appear in a project `.gitignore`. Consider adding it to the user global `.gitignore` instead.

```
# MACOSX

.DS_Store
.AppleDouble
.LSOverride
._*
.Spotlight-V100
.Trashes
```

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/f0beab9f-fe41-47db-8806-373f80c50f9e/analyses/43?status=violations)_

**Comment by oscarotero** [comment]
Abot the gitignore, yes, you're right.
About composer.lock, I include it in php projects but not php libraries. For example, on create a php project that uses some libraries (Embed and others), it's good to add composer.lock to git, to ensure that the project uses the same versions of the dependencies in all installations and there's no conflicts.
In case of libraries, this is not needed (and imo, no recomended).
