### ISSUE TITLE
possible error in docs

### ISSUE THREAD

**Issue by zyuhel** [oscarotero/Embed#92]
May be i'm mistaken. but shouldn't resolver be implementing RequestResolvers interface, not ImageInfo? 

```php
$config = [
    'resolver' => [
        'class' => 'Embed\\ImageInfo\\Guzzle5',

        'config' => [
            'client' => $myGuzzleClient,
        ]
    ]
];
````

**Comment by oscarotero** [comment]
Yep, now it's fixed. (this is the configuration of image not resolver)
