### ISSUE TITLE
Big files links

### ISSUE THREAD

**Issue by zyuhel** [oscarotero/Embed#94]
Image info according to documentation has support to drop requests  fetching only first bytes. What about file links. For example if we put a link to debian iso as link. we will hang until timeout. May be resolver should also look for available headers, so that if they are not in allowed (text/html, application/json etc...) and size is bigger than X (1 megabyte for example) it should drop request. returning only base info (last part of path, providerurl, mimetype)

**Comment by oscarotero** [comment]
That's what is doing. There's a list of available mime types (https://github.com/oscarotero/Embed/blob/master/src/ImageInfo/Curl.php#L12) and on receive the first bytes and get the mimetype, check if it's a valid mimetype (https://github.com/oscarotero/Embed/blob/master/src/ImageInfo/Curl.php#L154).
The Content-Type http header is not reliable.
