### ISSUE TITLE
Redirects break content type analysis

### ISSUE THREAD

**Issue by zyuhel** [oscarotero/Embed#95]
If file use redirects content-type analysis is broken. It says that file is not binary. even if it is. :) 
Example: http://cdimage.debian.org/debian-cd/8.2.0/amd64/iso-dvd/debian-8.2.0-amd64-DVD-2.iso

**Comment by zyuhel** [comment]
This file has unsupported binary content type, but if you add it to binary content type list you will see a bug. Same will be for other binary files with redirects.

**Comment by oscarotero** [comment]
Great. I had not realized this.
